### ISSUE TITLE
many connections can't be established问题如何诊断?

### ISSUE THREAD

**Issue by wangbin579** [session-replay-tools/tcpcopy#173]
测试服务器没有设置iptables相应命令的时候，先在在线服务器端telnet到测试服务器的端口，看看网络路径是是否是通的，如果不通，先解决掉这个问题再继续下面的诊断。

假设tcpcopy测试过程中，测试服务器上面的上层应用没有收到任何请求

传统架构检测方法:
判断第一次握手数据包,即syn数据包,能否到达测试服务器

1) 如果syn数据包能够到达测试服务器,分为两种情况:

1.1) 抓包仅仅只有syn数据包
     在测试服务器利用tcpdump 抓包，能看到被复制的syn数据包都过来了，说明已经到达了测试服务器的数据链路层。
     如果利用netstat 查看是否有应用的连接，如果没有，说明数据包在IP 层给drop 掉
了，请查看是否有rpfilter 设置，如果有，去掉此设置，一般即可解决此问题。
如果没有设置rpfilter，那么确认一下iptables 设置有没有冲突，如果有，请先整理
好iptables 相关规则。

1.2) syn数据包后面紧跟reset数据包(同一个session中,syn和reset数据包相隔不到1s)
       说明iptables设置有问题或者有冲突,导致了响应包直接返回给真实的客户端了.

2)  如果不能到达测试服务器,又分为两个部分:

2.1)  在在线服务器利用tcpdump抓包,能抓到tcpcopy转发的数据包
      如果能够抓到,参考文档的QA 5部分
         "跨网段机器之间无法复制请求"
      虚拟机之间的访问类似于跨网断

2.2) 在在线服务器利用tcpdump抓包,不能抓到tcpcopy转发的数据包
     说明在在线机器的ip层被过滤掉了,检测iptables对output chain的限制等内容
     如果是iptables的问题,而在线又不允许修改,采用--enable-dlinject从数据链路层的方式来发包.

**Comment by qqibrow** [comment]
Hi,

I have this problem now. I cannot telnet from online server to target server. During telnet, I ran `netstat` and it did show that status of the connection is SYN_RECV.  On my target server:

```
sudo iptables -L -n -v # nothing
Chain INPUT (policy ACCEPT 11113 packets, 859K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 5782 packets, 478K bytes)
 pkts bytes target     prot opt in     out     source               destination

sysctl net.ipv4.conf.default.rp_filter # Loss
net.ipv4.conf.default.rp_filter = 2
```

On my assistant server, I ran `tcpdump` and find out it did receive all packets with header: <target> => <online>`.

Finally, on the online server, I did the same tcpdump thing and find out no response packets from target server has been received. 

The problem now looks clear. Why online server received nothing from assistant server? do u have any suggestion how I should continue the investigation in order to telnet succeed?

**Comment by wangbin579** [comment]
Hi， 
  sorry about the delays in responding.
  Could you please provide more detail such as commands, error_tcpcopy.log and error_intercept.log?

2015-04-24






发件人：qqibrow <notifications@github.com>
发送时间：2015-04-22 06:35
主题：Re: [tcpcopy] many connections can't be established问题如何诊断? (#173)
收件人："session-replay-tools/tcpcopy"<tcpcopy@noreply.github.com>
抄送："Bin Wang"<wangbin579@gmail.com>

Hi,
I have this problem now. I cannot telnet from online server to target server. During telnet, I ran netstat and it did show that status of the connection is SYN_RECV. On my target server:
sudo iptables -L -n -v # nothing
Chain INPUT (policy ACCEPT 11113 packets, 859K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 5782 packets, 478K bytes)
 pkts bytes target     prot opt in     out     source               destination

sysctl net.ipv4.conf.default.rp_filter # Loss
net.ipv4.conf.default.rp_filter = 2

On my assistant server, I ran tcpdump and find out it did receive all packets with header: => `.
Finally, on the online server, I did the same tcpdump thing and find out no response packets from target server has been received. 
The problem now looks clear. Why online server received nothing from assistant server? do u have any suggestion how I should continue the investigation in order to telnet succeed?

**Comment by wangbin579** [comment]
新架构解决方案：

先在在线服务器端telnet到测试服务器的端口，看看网络路径是是否是通的，如果不通，先解决掉这个问题再继续下面的诊断。

假设tcpcopy测试过程中，测试服务器上面的上层应用没有收到任何请求

判断第一次握手数据包,即syn数据包,能否到达测试服务器

1) 如果syn数据包能够到达测试服务器,分为如下几种情况:

1.1) 抓包仅仅只有syn数据包
     在测试服务器利用tcpdump 抓包，能看到被复制的syn数据包都过来了，说明已经到达了测试服务器的数据链路层。
     如果利用netstat 查看是否有应用的连接，如果没有，说明数据包在IP 层给drop 掉
了，请查看是否有rpfilter 设置，如果有，去掉此设置，一般即可解决此问题。
如果没有设置rpfilter，那么确认一下iptables 设置有没有冲突，如果有，请先整理
好iptables 相关规则。

1.2) syn数据包后面紧跟reset数据包(注意：同一个session中,syn和reset数据包相隔不到1s)
       说明路由设置有问题或者有冲突,导致了响应包直接返回给真实的客户端了.

1.3）测试服务器有响应包（第二次握手数据包）
       去辅助服务器进行抓包，看看第二次握手数据包有没有到达辅助服务器：a）如果没有到达，也说明路由设置没有生效，因此intercept捕获不到第二次握手数据包，回放就无法继续下去，通常可以采用的方案是让intercept直接运行在测试服务器上面  b）如果捕获到了第二次握手数据包，查看是否有ip forward设置，如果设置了，需要关掉此设置，否则这些响应包会直接返回客户端，干扰测试的进行

2)  如果不能到达测试服务器,又分为两个部分:

2.1)  在在线服务器利用tcpdump抓包,能抓到tcpcopy转发的数据包
      如果能够抓到，说明路途过程中被干掉了，可以尝试利用tcpcopy的-c参数，修改客户端ip地址成合法的ip地址，最极端一点的就是修改成tcpcopy所在机器的ip地址（存在nat的问题）

2.2) 在在线服务器利用tcpdump抓包,不能抓到tcpcopy转发的数据包
     说明在在线机器的ip层被过滤掉了,检测iptables对output chain的限制等内容
     如果是iptables的问题,而在线又不允许修改,采用--pcap-send从数据链路层的方式来发包（有一定难度，可以参考http://jishu.y5y.com.cn/wangbin579/article/details/10148247）.
