### ISSUE TITLE
tcp_copy 必须得sudo 用户么？

### ISSUE THREAD

**Issue by zztztt** [session-replay-tools/tcpcopy#177]
我执行client, server端都可以，但是执行后，进程就执行完退出了。
当我用sudo用户时，进程在后台一直执行。
是我方法有问题还是必须是sudo用户？

**Comment by lazio579** [comment]
可以采用CAP_NET_RAW capability来达到你的需求，如果os支持的话

比如：
sudo setcap CAP_NET_RAW=ep tcpcopy
sudo setcap CAP_NET_RAW=ep intercept

设置以后，就可以用普通用户来执行了
