### ISSUE TITLE
0.9.0版本重复复制，0.9.8版本会丢包

### ISSUE THREAD

**Issue by wwwfza** [session-replay-tools/tcpcopy#180]
Hi, 
最近在调研tcpcopy, 
最开始使用0.9.8版本，采用传统模式，流量可以复制，但是会发现有明显的丢包率，大概30%，系统负载不大，tcpcopy的日志不断在刷
[warn] frag_off is not IP_DF,use raw socket instead of pcap
然后，我们根据网上的教程，换成0.9.0版本，流量正常复制，且从日志上观察不出丢包，但是感觉复制的流量要比线上的流量多，从日志分析有的时候一个线上请求会复制成两个线上请求，大概有10%的这种情况。
麻烦你了

**Comment by lxylzxc** [comment]
Hi，我也出现了同样的问题，
[warn] frag_off is not IP_DF,use raw socket instead of pcap
流量一直复制不过来，按照上面的说法修改成了0.9.6版本解决了问题
但是在复制另外一类数据时，原先使用0.9.8是正常的，但是使用0.9.6出现了请求复制了2~3份的情况。
在0.9.6版本删除了上面说的代码，流量稍微小了一点点，但是还是2倍多，方便帮忙分析一下吗？
