### ISSUE TITLE
利用tcpcopy测试mysql代理（Atlas）遇到的问题

### ISSUE THREAD

**Issue by flike** [session-replay-tools/tcpcopy#194]
你好！
    最近在用tcpcopy测试mysql代理，遇到一个问题。我通过以下方式搭建了一个tcpcopy：
git clone git://github.com/session-replay-tools/tcpcopy.git
cd tcpcopy
git clone git://github.com/session-replay-tools/mysql-replay-module.git
./configure --set-protocol-module=mysql-replay-module
make
make install
并在Assistant server上安装了intercept：
git clone git://github.com/session-replay-tools/intercept.git
cd intercept
./configure --with-resp-payload
make
make install

在搭建的环境中，我将线上的流量引入测试机器上，在测试机器上抓包出现如下日志（不是正确的mysql包）：
09:45:06.670908 IP *.139.170.189.15612 > *.139.100.214.13113: Flags [R.], seq 2349679116, ack 0, win 65535, length 0
09:45:06.674887 IP *.139.171.241.15680 > *.139.100.214.13113: Flags [R.], seq 2370611496, ack 0, win 65535, length 0
09:45:06.677876 IP *.139.170.187.15612 > *.139.100.214.13113: Flags [R.], seq 2353017455, ack 0, win 65535, length 0
（*是一个数字，我抹掉了，*.139.100.214是proxy机器，前面的IP是客户端）
在tcpcopy的机器上日志如下：
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:29 +415 [info] pool:285723792,block:285740192,len:44 occupy
2015/01/12 16:38:59 +415 [notice] active:1799,rel:4260,obs del:0,tw:1207
2015/01/12 16:38:59 +415 [notice] conns:0,resp:0,c-resp:0
2015/01/12 16:38:59 +415 [notice] resp fin:0,resp rst:0
2015/01/12 16:38:59 +415 [notice] send:11526,send content:0
2015/01/12 16:38:59 +415 [notice] send syn:6059, fin:0,reset:5467
2015/01/12 16:38:59 +415 [notice] reconnect:0,for no syn:0
2015/01/12 16:38:59 +415 [notice] retransmit:0
2015/01/12 16:38:59 +415 [notice] recv packs after retransmission:0
2015/01/12 16:38:59 +415 [notice] syn cnt:6059,all clt:82486,clt cont:38650
2015/01/12 16:38:59 +415 [notice] total cont retransmit:0, frag:0
2015/01/12 16:38:59 +415 [notice] total captured packets:259320
2015/01/12 16:38:59 +415 [warn] many connections can't be established
2015/01/12 16:39:14 +606 [warn] sig 2 received
2015/01/12 16:39:14 +606 [notice] active:1889,rel:7235,obs del:0,tw:1237
2015/01/12 16:39:14 +606 [notice] conns:0,resp:0,c-resp:0
2015/01/12 16:39:14 +606 [notice] resp fin:0,resp rst:0
2015/01/12 16:39:14 +606 [notice] send:17596,send content:0
发现所有的content都是0.线上机器的流量大概是7Mbps-10Mbps

我通过手动将流量引入同样的测试环境，tcpcopy是可以正确复制请求的。将线上环境的流量引入测试环境，就不能正确复制请求。请问这是什么原因？（是不是流量太大，导致抓包失败？）谢谢！

**Comment by wangbin579** [comment]
路由设置的问题，导致intercept捕获不到应答包，并且不该回客户端的数据包回去了
