### ISSUE TITLE
is it able to save the load to a file and replay it later?

### ISSUE THREAD

**Issue by qqibrow** [session-replay-tools/tcpcopy#195]
I find tcpcopy today through stackoverflow and I think it's such an amazing tool! my question is as the topic. I checked the documentation, it seems to me it could redirect the flow to a test server. But I am not sure if it's able to save the load to a file and replay it later.

**Comment by wangbin579** [comment]
You could use many tools to save the load to a pcap file such as wireshark, tcpdump, pfring, netmap,etc.
If you already have such a pcap file, you could use tcpcopy(configure --offline) to replay it later.

**Comment by qqibrow** [comment]
I found socat might be able to achieve same goal compared with tcpcopy. I don't know whether you compared the difference between them, such as usage scenario or performance overhead?

**Comment by wangbin579** [comment]
Socat aims to focus on relay while tcpcopy aims to focus on session replay or session duplication. So they have different usage scenarios.

If you want to know more about session replay, you could see the following paper:
www.vldb.org/pvldb/2/vldb09-588.pdf

**Comment by qqibrow** [comment]
Cool! Thank you very much!
