### ISSUE TITLE
tcpcopy遇到websocket以后

### ISSUE THREAD

**Issue by BoneLee** [session-replay-tools/tcpcopy#196]
如下是待上线服务器里nginx的日志，（tcpcopy引入了流量，但是可以看到有些异常的URL）：
159.226.162.143:44425 - - [14/Mar/2015:14:33:50 +0800] "POST /res HTTP/1.1" 200 213 "-" "node-urllib/2.0.1 node/v0.11.13-pre (win32 6.1.7601; ia32)" "-"
124.16.131.65:4933 - - [14/Mar/2015:14:33:50 +0800] "\x00" 400 323 "-" "-" "-"
159.226.162.143:44427 - - [14/Mar/2015:14:33:50 +0800] "\x81\xFE\x00\x86<\xF0\xFD\xB0G\xD2\x9E\xDFR\x9E\x98\xD3H\xD2\xC7\x80\x10\xD2\x89\xDFW\x95\x93\x92\x06\xD2\xCC\x81\x0F\xC7\xCC\x87\x0C\xC3\xCE\x81\x05\xC2\xC8\x89" 400 323 "-" "-" "-"
222.66.175.157:56646 - - [14/Mar/2015:14:33:50 +0800] "\x81\x8A\x97\x14\x93\xDE\xEC6\xE7\xA7\xE7q\xB1\xE4\xAEi" 400 323 "-" "-" "-"
125.39.145.3:23549 - - [14/Mar/2015:14:33:52 +0800] "GET /download_resource?user=14262660632280&file_hash=3828316067&private=0&cookie=&from=client&token=285293844814481312145315139517390066510 HTTP/1.1" 200 252 "-" "node-urllib/2.0.1 node/v0.11.13-pre (win32 6.3.9600; ia32)" "-"
可以看到里面有\x00,\x81一堆不正常的请求。请问这个可能是什么原因呢？
web服务器里面有http请求和websocket，会不会是websocket导致的？
Thanks in advance.

**Comment by BoneLee** [comment]
TcpCopy版本号: 0.7
内核版本号: 3.5
安装规则（即configure选项）: ./configure --enable-nfqueue --enable-single
启动命令（包括intercept和tcpcopy执行命令）:
1) # iptables -I OUTPUT -p tcp --sport 8881 -j NFQUEUE
2) # ./intercept
Then:
tcpcopy -x 8880-211.149.223.64:8881
iptables设置（传统架构）或者route设置（新架构）：iptables -I OUTPUT -p tcp --sport 8881 -j NFQUEUE

**Comment by wangbin579** [comment]
原因可能有很多种，最好的分析方法是通过抓包分析。

如果是1.0版本，出现这种状况，一般是丢包导致的

**Comment by BoneLee** [comment]
我们用过1.0，也是出现一样的问题！那1.0有什么方法解决这样的问题呢？谢谢！

**Comment by wangbin579** [comment]
未必是tcpcopy的问题，跟环境是相关的，如果压力大，丢包严重，必然会出现这种状况。
tcpcopy是回放工具，只有提供好的环境，才能很好的回放。

**Comment by BoneLee** [comment]
我尝试直接用80端口、http的tcpcopy，没有出现所说的乱码问题。但是在另外的项目中因为有websocket，才导致\x00出现，那么会不会是websocket导致的问题？按照tcpcopy底层来看，它会返回header，如果是websocket的话，没有这个header tcpcopy底层会做怎样的处理呢？谢谢！

**Comment by wangbin579** [comment]
最大可能：
websocket是有状态协议，不像http是无状态协议，所以半路截获的请求，由于缺乏之前的信息，导致被服务器认为是非法的请求，于是报400错误。

当然我也不知道websocket协议是否时可回放的协议，如果是，只要有完整的捕获过程，应该是能够回放的。

**Comment by wangbin579** [comment]
比如
mysql协议，是不可回放的协议，如果利用线上的数据包发送过去，mysql服务器就会直接拒绝，需要做应用层面的二次开发，才能让mysql服务器认为请求是合法的。

如果websocket也这样，那出现这种状况就很正常了。

tcpcopy解决的是tcp层面的交互过程，但如果上层应用协议有更强的控制，tcp层面就解决不了，需要二次开发，可以参考mysql的二次开发过程；
https://github.com/session-replay-tools/mysql-replay-module

下周我尝试一下websocket是否和mysql协议一样，具有不可回放性。

**Comment by BoneLee** [comment]
多谢多谢！期待你们的新版本！

**Comment by wangbin579** [comment]
新版本不会为了某种上层协议做特殊处理的。

**Comment by wangbin579** [comment]
感谢你的反馈。

经过分析：
https://tools.ietf.org/html/rfc6455
我们发现websocket协议类似于mysql协议，即不可回放的协议。

以后有空会考虑写一个tcpcopy module，用来满足websocket的请求复制
