### ISSUE TITLE
tcpcopy1.0版本在测试mysql流量copy时提示unauth...

### ISSUE THREAD

**Issue by beebol** [session-replay-tools/tcpcopy#197]
tcpcopy1.0版本在测试mysql流量copy时提示unauthenticated user。测试机启动时加了skip-grant-tables参数了。在用tcpdum 能正常抓到包，但在测试机无法看到应用正常访问到mysql

**Comment by wangbin579** [comment]
mysql是有状态的协议，且不可回放。

所以直接利用tcpcopy，未必就能够行得通。
这种场景，请参考这个：
https://github.com/session-replay-tools/mysql-sgt-replay-module

**Comment by beebol** [comment]
使用mysql-sgt-replay-module，已经可以正常使用了
