### ISSUE TITLE
many connections can't be established

### ISSUE THREAD

**Issue by feidaodalian** [session-replay-tools/tcpcopy#199]
这个是线上服务器的tcpcopy的log
2015/03/17 16:24:49 +992 [notice] session size:239
2015/03/17 16:24:49 +992 [notice] activate_dead_sessions
2015/03/17 16:24:55 +001 [notice] active:260,rel reqs:0,obs del:0
2015/03/17 16:24:55 +001 [notice] conns:0,resp packs:0,c-resp packs:0
2015/03/17 16:24:55 +001 [notice] send Packets:260,send content packets:0
2015/03/17 16:24:55 +001 [notice] send fin Packets:0,send reset packets:0
2015/03/17 16:24:55 +001 [notice] reconnect for closed :0,for no syn:3
2015/03/17 16:24:55 +001 [notice] retransmit:0
2015/03/17 16:24:55 +001 [notice] successful retransmit:0
2015/03/17 16:24:55 +001 [notice] syn cnt:258,all clt packs:1765,clt cont:264
2015/03/17 16:24:55 +001 [notice] total client content retransmit:0
2015/03/17 16:24:55 +001 [notice] total captured pakcets:8410
2015/03/17 16:24:55 +001 [notice] no responses after 30 secends
2015/03/17 16:24:55 +001 [warn] many connections can't be established
2015/03/17 16:24:55 +001 [notice] session size:260
2015/03/17 16:24:55 +001 [notice] activate_dead_sessions
2015/03/17 16:25:00 +001 [notice] active:293,rel reqs:0,obs del:0
2015/03/17 16:25:00 +001 [notice] conns:0,resp packs:0,c-resp packs:0
2015/03/17 16:25:00 +001 [notice] send Packets:293,send content packets:0
2015/03/17 16:25:00 +001 [notice] send fin Packets:0,send reset packets:0
2015/03/17 16:25:00 +001 [notice] reconnect for closed :0,for no syn:3
2015/03/17 16:25:00 +001 [notice] retransmit:0
2015/03/17 16:25:00 +001 [notice] successful retransmit:0
2015/03/17 16:25:00 +001 [notice] syn cnt:291,all clt packs:1982,clt cont:296
2015/03/17 16:25:00 +001 [notice] total client content retransmit:0
2015/03/17 16:25:00 +001 [notice] total captured pakcets:9767
2015/03/17 16:25:00 +001 [notice] no responses after 35 secends
2015/03/17 16:25:00 +001 [warn] many connections can't be established
2015/03/17 16:25:00 +001 [notice] session size:293

这个是测试机收集包的日志

2015/03/17 16:25:19 +574 [notice] cache hit:0,missed:0,lost:2
2015/03/17 16:25:19 +574 [notice] search:2,extra compared:0,all sessions:431
2015/03/17 16:25:19 +574 [notice] delay total:0
2015/03/17 16:25:19 +574 [notice] delay delete obsolete :0
2015/03/17 16:25:24 +574 [notice] total resp packs:2, all:2, route:431
2015/03/17 16:25:24 +574 [notice] cache hit:0,missed:0,lost:2
2015/03/17 16:25:24 +574 [notice] search:2,extra compared:0,all sessions:431
2015/03/17 16:25:24 +574 [notice] delay total:0
2015/03/17 16:25:24 +574 [notice] delay delete obsolete :0
2015/03/17 16:25:29 +574 [notice] total resp packs:2, all:2, route:431
2015/03/17 16:25:29 +574 [notice] cache hit:0,missed:0,lost:2
2015/03/17 16:25:29 +574 [notice] search:2,extra compared:0,all sessions:431
2015/03/17 16:25:29 +574 [notice] delay total:0
2015/03/17 16:25:29 +574 [notice] delay delete obsolete :0
2015/03/17 16:25:34 +574 [notice] total resp packs:2, all:2, route:431
2015/03/17 16:25:34 +574 [notice] cache hit:0,missed:0,lost:2
2015/03/17 16:25:34 +574 [notice] search:2,extra compared:0,all sessions:431
2015/03/17 16:25:34 +574 [notice] delay total:0
2015/03/17 16:25:34 +574 [notice] delay delete obsolete :0
2015/03/17 16:25:39 +574 [notice] total resp packs:2, all:2, route:431
2015/03/17 16:25:39 +574 [notice] cache hit:0,missed:0,lost:2
2015/03/17 16:25:39 +574 [notice] search:2,extra compared:0,all sessions:431
2015/03/17 16:25:39 +574 [notice] delay total:0
2015/03/17 16:25:39 +574 [notice] delay delete obsolete :0

线上机器A C  测试机器B
现在是这样的一个情况，线上机器A发包，在测试机B中用tcpdump是能够收到包的。但是在测试机B中的nginx日志却得不到请求，但是我换了一台线上机器C确是没问题的。
我的配置如下
tcpcopy 0.9.6
测试机器
 iptables -I OUTPUT -p tcp --sport 80 -j QUEUE 
请问大神many connections can't be established 是什么原因？A B C机器都不在一个网段。

**Comment by wangbin579** [comment]
请参考相应版本的文档中的QA部分
