### ISSUE TITLE
调整内核参数后连接建立的很慢，tcpburn一直打印日志recv rst from back:34838

### ISSUE THREAD

**Issue by ystyleb** [session-replay-tools/tcpcopy#202]
对tcp读写缓存大小进行了调整，目的节约内容，调整如下
net.ipv4.tcp_rmem=2048 2048 2048
net.ipv4.tcp_wmem=1024 1024 1024
调整后连接建立的很慢，tcpburn一直打印日志：
2015/04/10 11:19:30 +290 [notice] recv rst from back:35755
2015/04/10 11:19:30 +290 [notice] recv rst from back:33950
2015/04/10 11:19:30 +295 [notice] recv rst from back:34033
2015/04/10 11:19:30 +299 [notice] recv rst from back:36316
2015/04/10 11:19:30 +306 [notice] recv rst from back:36693
2015/04/10 11:19:30 +308 [notice] recv rst from back:36495
2015/04/10 11:19:30 +319 [notice] recv rst from back:35933
2015/04/10 11:19:30 +324 [notice] recv rst from back:36253
2015/04/10 11:19:30 +329 [notice] recv rst from back:34214
2015/04/10 11:19:30 +345 [notice] recv rst from back:34858
2015/04/10 11:19:30 +358 [notice] recv rst from back:34659
2015/04/10 11:19:30 +361 [notice] recv rst from back:36553
2015/04/10 11:19:30 +365 [notice] recv rst from back:33247
2015/04/10 11:19:30 +365 [notice] recv rst from back:33739
2015/04/10 11:19:30 +372 [notice] recv rst from back:33622

**Comment by lazio579** [comment]
这个应该问os吧
