### ISSUE TITLE
说明文档写错了。

### ISSUE THREAD

**Issue by Txxk** [session-replay-tools/tcpcopy#210]
On the target server which runs server applications 这个步骤里面说的ip是61.135.233.161。但是下面命令的ip是65.135.233.161

**Comment by wangbin579** [comment]
多谢

**Comment by just2d** [comment]
您好，我想请教一个关于notrack问题。在微博上问过的一个问题。
“而线上连接比较多的场合，最好关闭ip_conntrack或者对线上应用系统端口设置NOTRACK”。

如果有两个机器：
一个机器在前边专做防火墙和外网到内网的转发。
一个机器在防火墙后边的内网里，上边有nginx的80。
在防火墙机器上的iptables上关闭80的notrack，那从防火墙到后边nginx的DNAT怎么实现的呢？也需要在防火墙机器上加上负载均衡一类的服务吗？

我是在压测java的时候发现了这个问题，但是我找了一圈google，没找到答案。

**Comment by lazio579** [comment]
不了解dnat是如何实现的。
连接数比较多，也可以加大ip conntrack max的数量，但这个会影响整体的性能。

**Comment by just2d** [comment]
@wangbin579 请问能帮忙解答一下我上边的问题吗？谢谢

**Comment by just2d** [comment]
@lazio579 wangbin579 这个是你的老号吗？
增大max，QPS高了，总会有个极限的。所以考虑关闭conntrack，或者可以降低time_wait的time_out时间。当然最好的应该是关闭conntrack，我先试试吧。
