### ISSUE TITLE
Is it possible to modify application data when using TCPCopy

### ISSUE THREAD

**Issue by forhappy** [session-replay-tools/tcpcopy#212]
Hi we would like to use TCPCopy to duplicate ad requests from our production server to our staging server, which the application protocol is HTTP, but we need to modifies HTTP query parameter a little to tell that staging server the request is magnified(e.g. adding _dm=100 in the original HTTP query).

My question is, is it possible to modify application data when using TCPCopy, we need to reassemble these packets and parse the HTTP data and modify the HTTP request and replay these request ?

**Comment by lazio579** [comment]
You could use tcpcopy to duplicate requests to a web proxy(such as nginx) to modify HTTP queries and then send these modified requests to your staging server.

**Comment by lazio579** [comment]
You could use tcpcopy to duplicate requests to a web proxy(such as nginx) to modify HTTP queries and then send these modified requests to your staging server.
