### ISSUE TITLE
tcpcopy错误填充tcp segment内容

### ISSUE THREAD

**Issue by baolisheng** [session-replay-tools/tcpcopy#213]
环境描述：
tcp mss: 1460

问题描述：
对于大的post请求包（超过1460），tcpcopy进行了tcp segment分片，第一个分片正常；但是后续的分片的tcp segment内容为post xxxx，导致最终在被测server端重新组合分片的时候，最终的请求变成了如下的格式：
post /url?a=1&... 
<a>xxx</a>post xxx
也就是请求内容是第一分片的内容加上第二个分片错误的内容
最终服务端大量返回http 400 bad request的错误

**Comment by wangbin579** [comment]
上面描述的内容，应该不会发生，而可能是其它原因导致的

有抓包内容吗？
正常请求抓包内容和tcpcopy发过去的对应内容。

有的发过来吧 wangbin579@gmail.com

**Comment by wangbin579** [comment]
这个bug，是1.0改造过程中新带来的bug。
1.0之前的0.9系列老版本没有这个问题。
