### ISSUE TITLE
最新的1.0版本如何使用离线模式？

### ISSUE THREAD

**Issue by xixi521874** [session-replay-tools/tcpcopy#215]
首先感谢作者的无私分享:)
已成功部署tcpcopy1.0.0，想使用新版本的offline模式，能否简单提点或者在贵博客更新？是否介意鄙人发表tcpcopy部署使用的相关博客（注明作者您并加入贵博客链接）

**Comment by wangbin579** [comment]
对于tcpcopy，configure的时候加上--offline
--offline                   replay TCP streams from the pcap file

执行的时候，加上-i参数，用来指定pcap文件地址

对于intercept，不用变化

欢迎发表相关博客，如果用户能从用户的角度来写文档，可能更加贴近用户。
