### ISSUE TITLE
TCPCOPY 在线服务器注册，支付操作。会同步到测试服务器吗？

### ISSUE THREAD

**Issue by wubin1213** [session-replay-tools/tcpcopy#216]
tcocopy版本 1.0.0
系统:centos 6.5 x64
内核:2.6.32-504.23.4.el6.x86_64
安装:#./configure && make && make install
在线服务器:192.168.0.100
测试服务器:192.168.0.101
应用:discuz
辅助服务器:无

在线服务器
#./tcpcopy -x 80-192.168.0.101:80 -s 192.168.0.101 -d

测试服务器
#./intercept -i eth0 -F tcp and src port 80 -d

1、测试服务器和intercept服务器，可台在1台上使用吗？
2、当在线服务器流量，连接导入测试服务器时，在线上服务器上的操作会同步到测试服务器吗？
比如:以discuz为例，在线服务器注册了一个用户，A1。测试服务器上也同样会创建A1用户吗？

**Comment by wangbin579** [comment]
1）测试服务器和intercept服务器，如果在同一台服务器，还是需要设置路由，目的是黑洞掉测试服务器的应答包，否则会干涉测试的进行。

2）在线上服务器上的操作会同步到测试服务器，前提是测试服务器能够认为这些请求是合法的

**Comment by wubin1213** [comment]
我按上面的条件测试了。在线服务器注册了一个用户user1，在测试服务器上发现并没有user1用户。nginx访问日志都是200，注册用户POST也是200。不知道是哪里弄错了。感觉访问请求同步到了测试服务器，注册操作，并没有同步到测试服务器。

**Comment by wangbin579** [comment]
抓包分析一下吧

**Comment by wubin1213** [comment]
请问下，辅助服务器环境是否也要与测试服务器环境相同？
比如：测试服务器环境:Nginx PHP 
辅助服务器也要配置相应的Nginx，PHP
