### ISSUE TITLE
如何在nat环境下应用tcpcopy？

### ISSUE THREAD

**Issue by wangbin579** [session-replay-tools/tcpcopy#217]
如果客户端ip地址没有变化，而服务器ip地址变化了，可以添加configure选项：--dnat

btw，tcpcopy和intercept都需要设置configure选项

如果客户端ip地址都变化了，那目前还不支持

**Comment by kys1230** [comment]
复制的包经过公司外网网关 做了目标和源地址转换 这算不算客户端IP变化...

**Comment by wangbin579** [comment]
客户端ip地址没有必要变化吧。

抓包分析一下吧

**Comment by kys1230** [comment]
只需要编译的时候加上--dnat就行了么 在启动的时候还有什么需要指定的么?

**Comment by wangbin579** [comment]
其它一样

**Comment by kys1230** [comment]
尝试了多次 没成功. 最后是通过在线上搭建一个新的nginx 把流量引入nginx在反向代理到公司内部测试机的...

**Comment by wangbin579** [comment]
要不哪天，抓个包，我来分析为啥失败
