### ISSUE TITLE
我想通过tcpcopy 将线上的web流量引入公司的测试服务器

### ISSUE THREAD

**Issue by kys1230** [session-replay-tools/tcpcopy#218]
遇到的问题是 公司出口是个路由器 这里设置了两个端口转换
1. 将公司外网IP的80端口映射到内网测试服务器的80端口
2. 将公司外网IP的36524端口映射到内网的辅助服务器(intercept)的36524端口

在服务服务器上启动intercept服务 
# ./intercept -i eth0 -F 'tcp and src port 80'

在测试环境的web 服务器上添加路由条目
# route add -host 内网网关 gw 辅助服务器

在线上环境的web服务器启动tcpcopy服务
# ./tcpcopy -x 80-公司外网IP:80 -s 公司外网IP

上面操作是这样做的 但是效果没出来
不知道是哪里配置错了 请大家帮忙看一下..感觉应该是路由那的问题 但是调整过几次 也都不好使.

**Comment by wangbin579** [comment]
https://github.com/session-replay-tools/tcpcopy/issues/217
