### ISSUE TITLE
run offline mode and not work 

### ISSUE THREAD

**Issue by cway** [session-replay-tools/tcpcopy#219]
./intercept
./tcpcopy -i online.pcap -x 9090-127.0.0.1:9090
i use  this tow command to execute tcpcopy and intercept.
use nginx listen 9090 on local server. but nginx not receive any request.

the error_intercept is : 
2015/07/28 17:39:09 +397 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:09 +397 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:09 +397 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:09 +397 [notice] delay total:0
2015/07/28 17:39:09 +398 [notice] delay delete obsolete :0
2015/07/28 17:39:14 +398 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:14 +398 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:14 +398 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:14 +398 [notice] delay total:0
2015/07/28 17:39:14 +399 [notice] delay delete obsolete :0
2015/07/28 17:39:19 +399 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:19 +399 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:19 +399 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:19 +399 [notice] delay total:0
2015/07/28 17:39:19 +400 [notice] delay delete obsolete :0
2015/07/28 17:39:24 +400 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:24 +400 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:24 +400 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:24 +400 [notice] delay total:0
2015/07/28 17:39:24 +401 [notice] delay delete obsolete :0
2015/07/28 17:39:29 +401 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:29 +401 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:29 +401 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:29 +401 [notice] delay total:0
2015/07/28 17:39:29 +402 [notice] delay delete obsolete :0
2015/07/28 17:39:34 +402 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:34 +402 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:34 +402 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:34 +402 [notice] delay total:0
2015/07/28 17:39:34 +403 [notice] delay delete obsolete :0
2015/07/28 17:39:39 +403 [notice] total resp packs:14, all:14, route:0
2015/07/28 17:39:39 +403 [notice] cache hit:0,missed:0,lost:14
2015/07/28 17:39:39 +403 [notice] search:14,extra compared:0,all sessions:0
2015/07/28 17:39:39 +403 [notice] delay total:0
2015/07/28 17:39:39 +404 [notice] delay delete obsolete :0

the error_tcpcopy.log is : 
2015/07/28 17:38:39 +481 [notice] session size:0
2015/07/28 17:38:39 +482 [notice] activate_dead_sessions
2015/07/28 17:38:44 +482 [notice] session size:0
2015/07/28 17:38:44 +483 [notice] activate_dead_sessions
2015/07/28 17:38:49 +483 [notice] session size:0
2015/07/28 17:38:49 +484 [notice] activate_dead_sessions
2015/07/28 17:38:54 +484 [notice] session size:0
2015/07/28 17:38:54 +485 [notice] activate_dead_sessions
2015/07/28 17:38:59 +485 [notice] session size:0
2015/07/28 17:38:59 +486 [notice] activate_dead_sessions
2015/07/28 17:39:04 +486 [notice] session size:0
2015/07/28 17:39:04 +487 [notice] activate_dead_sessions
2015/07/28 17:39:09 +487 [notice] session size:0
2015/07/28 17:39:09 +488 [notice] activate_dead_sessions
2015/07/28 17:39:10 +611 [notice] user time used:19
2015/07/28 17:39:10 +611 [notice] sys  time used:18
2015/07/28 17:39:10 +611 [notice] max memory size:8012
2015/07/28 17:39:14 +488 [notice] session size:0
2015/07/28 17:39:14 +489 [notice] activate_dead_sessions
2015/07/28 17:39:19 +489 [notice] session size:0
2015/07/28 17:39:19 +490 [notice] activate_dead_sessions
2015/07/28 17:39:24 +490 [notice] session size:0
2015/07/28 17:39:24 +491 [notice] activate_dead_sessions
2015/07/28 17:39:29 +491 [notice] session size:0
2015/07/28 17:39:29 +492 [notice] activate_dead_sessions
2015/07/28 17:39:34 +492 [notice] session size:0
2015/07/28 17:39:34 +493 [notice] activate_dead_sessions
2015/07/28 17:39:39 +493 [notice] session size:0
2015/07/28 17:39:39 +494 [notice] activate_dead_sessions
2015/07/28 17:39:44 +494 [notice] session size:0
2015/07/28 17:39:44 +495 [notice] activate_dead_sessions
2015/07/28 17:39:45 +000 [notice] offline replay is complete
2015/07/28 17:39:45 +001 [warn] sig 64 received
2015/07/28 17:39:45 +001 [notice] remove timer over
2015/07/28 17:39:45 +001 [notice] enter destroy_for_sessions
2015/07/28 17:39:45 +008 [notice] total visit hash_find_node:0,compared:0
2015/07/28 17:39:45 +008 [notice] destroy items 0 in table name:transfer port table
2015/07/28 17:39:45 +008 [notice] leave destroy_for_sessions
2015/07/28 17:39:45 +008 [notice] tc_event_loop_finish over
2015/07/28 17:39:45 +008 [notice] it close socket:4
2015/07/28 17:39:45 +008 [notice] it close socket:5
2015/07/28 17:39:45 +008 [notice] it close socket:6
2015/07/28 17:39:45 +008 [notice] destroy addr table
2015/07/28 17:39:45 +008 [notice] total visit hash_find_node:4,compared:2

**Comment by cway** [comment]
版本0.9

**Comment by wangbin579** [comment]
抓个包分析一下吧

**Comment by cway** [comment]
抓哪个端口的包？
