### ISSUE TITLE
测试服务器收不到请求

### ISSUE THREAD

**Issue by kelsogit1986** [session-replay-tools/tcpcopy#222]
问题描述：测试服务器没有收到请求

tcpcopy版本1.0
内核 linux2.6
安装规则 ./configure
启动命令
10.16.10.145测试服务器：route add -net 10.16.10.0 netmask 255.255.255.0 gw 10.16.10.65
10.16.10.65 辅助服务器：/usr/local/intercept/sbin/intercept -i eth0 -F tcp and src port 80 -l /tmp/intercept.log -d
10.16.10.121线上服务器：/usr/local/tcpcopy/sbin/tcpcopy -x 80-10.16.10.145:80 -s 10.16.10.65 -l /tmp/tcpcopy.log -d

辅助服务器日志：
2015/08/03 16:01:35 +134 [notice] from bak:192.168.106.202:80-->10.16.10.65:44437,len 635,seq=2780193141,ack=3520302157
2015/08/03 16:01:35 +136 [notice] fd is null after session is created
2015/08/03 16:01:35 +136 [notice] from bak:192.168.106.202:80-->10.16.10.65:44437,len 40,seq=2780193736,ack=3520302158
2015/08/03 16:02:04 +391 [notice] total resp packs:1451, all:1451, route:0, sock write cnt:0
2015/08/03 16:02:04 +391 [notice] cache hit:0,missed:0,lost:1451
2015/08/03 16:02:04 +391 [notice] search:1451,extra compared:0,all sessions:0

线上服务器日志：
2015/08/03 16:14:40 +392 [notice] user time used:0
2015/08/03 16:14:40 +392 [notice] sys  time used:0
2015/08/03 16:14:40 +392 [notice] max memory size:0
2015/08/03 16:14:40 +392 [notice] voluntary ctx switches:21792
2015/08/03 16:14:40 +392 [notice] involuntary ctx switches:0
2015/08/03 16:15:40 +392 [notice] user time used:0
2015/08/03 16:15:40 +392 [notice] sys  time used:0
2015/08/03 16:15:40 +392 [notice] max memory size:0
2015/08/03 16:15:40 +392 [notice] voluntary ctx switches:21987
2015/08/03 16:15:40 +392 [notice] involuntary ctx switches:0
2015/08/03 16:16:10 +399 [notice] active:2,rel:1,obs del:0,tw:2
2015/08/03 16:16:10 +399 [notice] conns:0,resp:0,c-resp:0
2015/08/03 16:16:10 +399 [notice] resp fin:0,resp rst:0
2015/08/03 16:16:10 +399 [notice] send:6,send content:0
2015/08/03 16:16:10 +399 [notice] send syn:3, fin:0,reset:3
2015/08/03 16:16:10 +399 [notice] reconnect:0,for no syn:1
2015/08/03 16:16:10 +399 [notice] retransmit:0
2015/08/03 16:16:10 +399 [notice] recv packs after retransmission:0
2015/08/03 16:16:10 +399 [notice] syn cnt:2,all clt:17,clt cont:10
2015/08/03 16:16:10 +399 [notice] total cont retransmit:0, frag:0
2015/08/03 16:16:10 +399 [notice] total captured packets:15884
2015/08/03 16:16:10 +399 [warn] many connections can't be established

线上服务器和测试服务器的80端口均为nginx服务，用openresty启动，在nginx.conf内的lua语句直接返回<p>hello world!</p>

测试服务器route信息：
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.16.10.0      10.16.10.65     255.255.255.0   UG    0      0        0 eth0
10.16.10.0      *               255.255.255.0   U     0      0        0 eth0
169.254.0.0     *               255.255.0.0     U     0      0        0 eth0
192.168.0.0     10.16.10.254    255.255.0.0     UG    0      0        0 eth0
10.0.0.0        10.16.10.254    255.128.0.0     UG    0      0        0 eth0

**Comment by wangbin579** [comment]
在测试服务器抓个包分析一下吧
如果不会分析，把抓包内容贴出来

**Comment by wangbin579** [comment]
在测试服务器抓个包分析一下吧
如果不会分析，把抓包内容贴出来

**Comment by kelsogit1986** [comment]
谢谢回复，这里是抓包结果
抓包选项指定主机为线上机tcpdump host 10.16.10.121
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 96 bytes
19:11:29.908387 arp who-has test.company.com tell 10.16.10.121
19:11:29.909481 arp reply test.company.com is-at 00:23:7d:a7:e8:14 (oui Unknown)

**Comment by caosiyang** [comment]
10.16.10.121线上服务器
/usr/local/tcpcopy/sbin/tcpcopy -x 80-10.16.10.145:80 -s 10.16.10.65 -c 10.16.10.x -l /tmp/tcpcopy.log -d

**Comment by kelsogit1986** [comment]
线上服务器加上-c 10.16.10.x 后解决了问题!
