### ISSUE TITLE
网络镜像下的tcpcopy数据发送不成功问题

### ISSUE THREAD

**Issue by wenjq** [session-replay-tools/tcpcopy#224]
之前做了一个网络镜像下的tcpcopy长连接数据拷贝的实施方案，遇见了一些问题（网卡混杂模式、长连接丢包、网卡大包问题）并解决了，形成了一个可执行的方案并做了稳定性测试。目前实际应用的时候，出现了一个之前没遇到过的问题，请帮忙分析一下可能是什么问题。
我有两台机器 10.110.60.52 、10.110.60.51
52上部署了intercept和tcpcopy，编译使用pcap-capture和pf_ring
 ./intercept -i eth1 -F 'tcp and src port 20017' -l intercept.log -d
 ./tcpcopy -x 7890-10.110.60.51:20017 -l tcpcopy.log -s 10.110.60.52 -F  'tcp and  port 7890'  -i eth1 -c 192.168.200.1
51上部署了我的目标应用，端口20017
配置路由route add -net 192.168.200.0 netmask 255.255.255.0 gw 10.110.60.52
均使用iptables -F关闭了防火墙

开启tcpcopy后，可以看到抓到了大量7890端口的包，但是却很少的发送至20017端口，抓包20017端口交互的报文可以看见频繁的“rst,ack”tcp重连操作，源流量交互正常无重连操作。在目标机60.51上可以看见连接ESTABLISHED已经建立，但是由于tcp重连或别的原因，只有少量的协议数据进行了发送

tcpcopy日志如下：
2015/08/19 14:28:25 +125 [notice] tcpcopy version:1.0.0
2015/08/19 14:28:25 +125 [notice] tcpcopy internal version:6
2015/08/19 14:28:25 +125 [notice] target:7890-10.110.60.51:20017
2015/08/19 14:28:25 +125 [notice] pcap version:libpcap version 1.6.2
2015/08/19 14:28:25 +125 [notice] HAVE_SET_IMMEDIATE_MODE is true
2015/08/19 14:28:25 +125 [notice] TC_PCAP mode
2015/08/19 14:28:25 +125 [notice] TC_COMBINED mode
2015/08/19 14:28:25 +125 [notice] epoll mode
2015/08/19 14:28:25 +125 [notice] TC_HAVE_PF_RING is true
2015/08/19 14:28:25 +125 [notice] TC_DETECT_MEMORY is true
2015/08/19 14:28:25 +125 [notice] session timeout:120
2015/08/19 14:28:25 +125 [notice] keepalive timeout:240
2015/08/19 14:28:25 +125 [notice] min sess pool size:576
2015/08/19 14:28:25 +125 [notice] sess pool size:1024
2015/08/19 14:28:25 +125 [notice] set global port for tcpcopy
2015/08/19 14:28:25 +125 [notice] raw_clt_tf_ip:192.168.200.1
2015/08/19 14:28:25 +125 [notice] parallel connections per target:2
2015/08/19 14:28:25 +125 [notice] device:eth1
2015/08/19 14:28:25 +125 [notice] user filter:tcp and  port 7890
2015/08/19 14:28:25 +125 [notice] s parameter:10.110.60.52
2015/08/19 14:28:25 +125 [notice] set only ip for tcpcopy
2015/08/19 14:28:25 +125 [debug] pool:19133616, add timer:19133780
2015/08/19 14:28:25 +125 [debug] pool:19133616, add timer:19133860
2015/08/19 14:28:25 +125 [info] pool:19170528,block:19186928,len:44 occupy
2015/08/19 14:28:25 +125 [info] pool:19170528,block:19186928,len:44 occupy
2015/08/19 14:28:25 +125 [info] connect to remote server(10.110.60.52:36524)
2015/08/19 14:28:25 +125 [info] connect to remote server(10.110.60.52:36524)
2015/08/19 14:28:25 +125 [notice] pcap open,device:eth1
2015/08/19 14:28:25 +125 [notice] pcap_set_buffer_size:16777216
2015/08/19 14:28:25 +178 [info] pl:22412080, p:33384
2015/08/19 14:28:25 +178 [debug] pool:22412080, add timer:22412444
2015/08/19 14:28:25 +178 [info] nev:22412420,p:33384
2015/08/19 14:28:25 +178 [debug] pool:22412080, add timer:22412524
2015/08/19 14:28:25 +178 [notice] session key:1961336268930, p:33384
2015/08/19 14:28:25 +178 [debug] recv clt:192.168.200.1:33384-->221.176.2.123:7890,len 73,seq=9253292,ack=3321549161
2015/08/19 14:28:25 +178 [info] ln:22412740, pkt:22412644, save:9253292,p:33384
2015/08/19 14:28:25 +178 [info] slide_win_packs size:1, p:33384
2015/08/19 14:28:25 +178 [debug] proc clt pack:33384
2015/08/19 14:28:25 +178 [debug] fake syn:33384
2015/08/19 14:28:25 +178 [debug] to bak:192.168.200.1:33384-->10.110.60.51:20017,len 44,seq=9253291,ack=0
2015/08/19 14:28:25 +178 [info] rtt:1,p:33384
2015/08/19 14:28:25 +178 [debug] resp packets:1
2015/08/19 14:28:25 +178 [debug] from bak:10.110.60.51:20017-->192.168.200.1:33384,len 44,seq=2364714809,ack=9253292
———————————————————————————————————

2015/08/19 14:28:25 +197 [debug] from bak:10.110.60.51:20017-->192.168.200.1:35972,len 40,seq=2361073384,ack=4219945673
2015/08/19 14:28:25 +197 [info] prev=nul:35972
2015/08/19 14:28:25 +197 [debug] win forward:35972
2015/08/19 14:28:25 +226 [debug] recv clt:192.168.200.1:33384-->221.176.2.123:7890,len 115,seq=9253334,ack=3321549886
2015/08/19 14:28:25 +226 [info] ln:22413052, pkt:22412916, save:9253334,p:33384
2015/08/19 14:28:25 +226 [info] slide_win_packs size:2, p:33384
2015/08/19 14:28:25 +226 [debug] proc clt pack:33384
2015/08/19 14:28:25 +226 [info] con:21,p:33384
2015/08/19 14:28:25 +226 [debug] a new req,p:33384
2015/08/19 14:28:25 +226 [debug] stop req,p:33384
2015/08/19 14:28:25 +257 [debug] recv clt:192.168.200.1:38222-->221.176.2.123:7890,len 294,seq=532333039,ack=1047217217
2015/08/19 14:28:25 +257 [info] ln:22416300, pkt:22413820, save:532333039,p:38222
2015/08/19 14:28:25 +257 [info] slide_win_packs size:1, p:38222
2015/08/19 14:28:25 +257 [debug] proc clt pack:38222
2015/08/19 14:28:25 +257 [info] con:242,p:38222
2015/08/19 14:28:25 +257 [debug] a new req,p:38222
2015/08/19 14:28:25 +257 [debug] stop req,p:38222
2015/08/19 14:28:25 +258 [debug] recv clt:192.168.200.1:35972-->221.176.2.123:7890,len 115,seq=4219945673,ack=524143494
2015/08/19 14:28:25 +258 [info] ln:22416036, pkt:22415900, save:4219945673,p:35972
2015/08/19 14:28:25 +258 [info] slide_win_packs size:1, p:35972
2015/08/19 14:28:25 +258 [debug] proc clt pack:35972
2015/08/19 14:28:25 +258 [info] con:63,p:35972
2015/08/19 14:28:25 +258 [debug] a new req,p:35972
2015/08/19 14:28:25 +258 [debug] stop req,p:35972
2015/08/19 14:28:25 +268 [debug] recv clt:192.168.200.1:38222-->221.176.2.123:7890,len 94,seq=532333281,ack=1047217362
2015/08/19 14:28:25 +268 [info] ln:22416452, pkt:22416340, save:532333281,p:38222
2015/08/19 14:28:25 +268 [info] slide_win_packs size:2, p:38222
2015/08/19 14:28:25 +268 [debug] proc clt pack:38222
2015/08/19 14:28:25 +268 [info] con:242,p:38222
2015/08/19 14:28:25 +268 [debug] a new req,p:38222
2015/08/19 14:28:25 +268 [debug] stop req,p:38222
2015/08/19 14:28:25 +270 [debug] recv clt:192.168.200.1:35972-->221.176.2.123:7890,len 73,seq=4219945736,ack=524143639
2015/08/19 14:28:25 +270 [info] ln:22416172, pkt:22416076, save:4219945736,p:35972
2015/08/19 14:28:25 +270 [info] slide_win_packs size:2, p:35972
2015/08/19 14:28:25 +270 [debug] proc clt pack:35972
—————————之后基本都是7890端口的包—————————————
2015/08/19 14:28:58 +166 [debug] recv clt:192.168.200.1:33384-->221.176.2.123:7890,len 323,seq=9574277,ack=3321733840
2015/08/19 14:28:58 +166 [info] ln:24108052, pkt:24107708, save:9574277,p:33384
2015/08/19 14:28:58 +166 [info] slide_win_packs size:1200, p:33384
2015/08/19 14:28:58 +166 [debug] proc clt pack:33384
2015/08/19 14:28:58 +166 [info] con:21,p:33384
2015/08/19 14:28:58 +166 [debug] a new req,p:33384
2015/08/19 14:28:58 +166 [debug] stop req,p:33384
2015/08/19 14:28:58 +170 [debug] recv clt:192.168.200.1:38222-->221.176.2.123:7890,len 987,seq=532560160,ack=1047393760
2015/08/19 14:28:58 +170 [info] ln:24104324, pkt:24112436, save:532560160,p:38222
2015/08/19 14:28:58 +170 [info] slide_win_packs size:925, p:38222
2015/08/19 14:28:58 +170 [debug] proc clt pack:38222
2015/08/19 14:28:58 +170 [info] con:242,p:38222
2015/08/19 14:28:58 +170 [debug] a new req,p:38222
2015/08/19 14:28:58 +170 [debug] stop req,p:38222
2015/08/19 14:28:58 +176 [debug] recv clt:192.168.200.1:35972-->221.176.2.123:7890,len 1132,seq=4220247679,ack=524325794
2015/08/19 14:28:58 +176 [info] ln:24106492, pkt:24113460, save:4220247679,p:35972
2015/08/19 14:28:58 +176 [info] slide_win_packs size:976, p:35972
2015/08/19 14:28:58 +176 [debug] proc clt pack:35972
2015/08/19 14:28:58 +176 [info] con:63,p:35972
2015/08/19 14:28:58 +176 [debug] a new req,p:35972
2015/08/19 14:28:58 +176 [debug] stop req,p:35972
2015/08/19 14:28:58 +178 [debug] del timer:22412500
2015/08/19 14:28:58 +178 [info] sess key:1961336268930, check timeout:33384
2015/08/19 14:28:58 +178 [warn] slide win:too many packs:1200,p:33384
2015/08/19 14:28:58 +178 [debug] sess post disp:33384
2015/08/19 14:28:58 +178 [debug] send passive rst:33384
2015/08/19 14:28:58 +178 [debug] to bak:192.168.200.1:33384-->10.110.60.51:20017,len 40,seq=9253313,ack=2364714810
2015/08/19 14:28:58 +178 [info] cont unsend:33384,ack:9253313,max:9574277
2015/08/19 14:28:58 +178 [debug] pool:22412080, up timer:22412500
2015/08/19 14:28:58 +178 [debug] recv clt:192.168.200.1:38222-->221.176.2.123:7890,len 364,seq=532561095,ack=1047393760
2015/08/19 14:28:58 +178 [info] ln:24104748, pkt:24104364, save:532561095,p:38222
2015/08/19 14:28:58 +178 [info] slide_win_packs size:926, p:38222
2015/08/19 14:28:58 +178 [debug] proc clt pack:38222

间隔才会向20017发送部分包

=======================================================
intercept日志
2015/08/19 14:26:48 +718 [notice] intercept version:1.0.0
2015/08/19 14:26:48 +718 [notice] intercept internal version:6
2015/08/19 14:26:48 +718 [notice] TC_COMBINED mode
2015/08/19 14:26:48 +718 [notice] TC_ADVANCED mode
2015/08/19 14:26:48 +718 [notice] device:eth1
2015/08/19 14:26:48 +718 [notice] user filter:tcp and src port 20017
2015/08/19 14:26:48 +718 [notice] msg listen socket:4
2015/08/19 14:26:48 +718 [notice] pcap open,device:eth1
2015/08/19 14:26:48 +718 [notice] pcap_set_buffer_size:16777216
2015/08/19 14:27:18 +718 [notice] total resp packs:0, all:0, route:0, sock write cnt:0
2015/08/19 14:27:18 +718 [notice] cache hit:0,missed:0,lost:0
2015/08/19 14:27:18 +718 [notice] search:0,extra compared:0,all sessions:0
2015/08/19 14:27:48 +718 [notice] total resp packs:0, all:0, route:0, sock write cnt:0
2015/08/19 14:27:48 +718 [notice] cache hit:0,missed:0,lost:0
2015/08/19 14:27:48 +718 [notice] search:0,extra compared:0,all sessions:0
2015/08/19 14:28:18 +718 [notice] total resp packs:0, all:0, route:0, sock write cnt:0
2015/08/19 14:28:18 +718 [notice] cache hit:0,missed:0,lost:0
2015/08/19 14:28:18 +718 [notice] search:0,extra compared:0,all sessions:0
2015/08/19 14:28:25 +138 [notice] it adds fd:6
2015/08/19 14:28:25 +138 [notice] it adds fd:7
2015/08/19 14:28:25 +178 [info] malloc memory for fd:6
2015/08/19 14:28:25 +183 [info] malloc memory for fd:7
2015/08/19 14:28:48 +718 [notice] total resp packs:8, all:8, route:4, sock write cnt:8
2015/08/19 14:28:48 +718 [notice] cache hit:8,missed:0,lost:0
2015/08/19 14:28:48 +718 [notice] search:8,extra compared:0,all sessions:4
2015/08/19 14:29:18 +718 [notice] total resp packs:16, all:16, route:8, sock write cnt:16
2015/08/19 14:29:18 +718 [notice] cache hit:16,missed:0,lost:0
2015/08/19 14:29:18 +718 [notice] search:16,extra compared:0,all sessions:8
2015/08/19 14:29:39 +118 [notice] recv length 0,fd:6
2015/08/19 14:29:39 +118 [notice] release tunnel resources, fd:6
2015/08/19 14:29:39 +118 [notice] enter tc_event_destroy:6
2015/08/19 14:29:39 +118 [notice] destroy event:6
2015/08/19 14:29:39 +118 [notice] recv length 0,fd:7
2015/08/19 14:29:39 +118 [notice] release tunnel resources, fd:7
2015/08/19 14:29:39 +118 [notice] enter tc_event_destroy:7
2015/08/19 14:29:39 +118 [notice] destroy event:7
2015/08/19 14:29:48 +718 [notice] total resp packs:25, all:25, route:12, sock write cnt:25
2015/08/19 14:29:48 +718 [notice] cache hit:25,missed:0,lost:0
2015/08/19 14:29:48 +718 [notice] search:25,extra compared:0,all sessions:12
============================================================
PS：
1.我在60.52使用本地端口20007复制本地流量，不会出现该问题，使用相同的命令只更改端口即可正常使用，但复制镜像流量就会出现tcp重连现象。
2.在验证方案时使用上述两台实体机器在测试环境进行镜像部署，未出现该问题

**Comment by wangbin579** [comment]
“抓包20017端口交互的报文可以看见频繁的“rst,ack”tcp重连操作”
能贴出session抓包样例吗？

想看看rst数据包是tcpcopy发的还是客户端发的？

还有看看辅助服务器是否设置了ip forward功能？

**Comment by wenjq** [comment]
在wangbin大拿的给力分析下，已找到问题，是长连接双工交互的特有问题，如果是短连接交互，交互报文是固定的，不会出现改问题。长连接交互时，由于双方都会通过连接发送数据，A-->B,B-->A。当进行流量复制后，A-->B侧的数据可以正常响应，但是由于B-->A的数据由于行为的不确定性，在测试服务器上无法进行模拟，导致ack回应不一致，不一致后tcpcopy将进行等待，直至重连。所以表现出只有少量的协议数据进行了发送。
流量复制只需要单侧的流量即可工作，不知道大拿能否出个版本或者开关来支持这种长连接双工交互的流量拷贝，忽略另一侧的流量，只保持一侧流量发送应该就能正常工作了

**Comment by wenjq** [comment]
问题已解决，当长连接双工双方都有数据进行发送交互时，由于有一侧的数据可能无法进行模拟。而tcpcopy客户端到服务器端，不同数据包之间有应答，复制这些数据包过去以后，也必须满足中间有应答这个条件，否则不支持，也就是说ack的length不能为0。当长连接A->B发送数据,B->A回响应时，同时携带了B->A的请求数据，就会出现该问题。解决这个问题的办法有些取巧，也就是使用的测试服务器，无论受到了任何报文（即使那个报文是一个response响应报文，不需要回数据），也给session写回一段段小的数据，造成有数据发送的事实（即ack长度!=0）即可
