### ISSUE TITLE
tc_sess_t::target_ack_seq 字节序问题

### ISSUE THREAD

**Issue by caosiyang** [session-replay-tools/tcpcopy#225]
struct tc_sess类型定义，target_ack_seq注释为主机字节序；
编码过程中，target_ack_seq以网络字节序的方式使用。
只是声明与使用上的不统一，对packet的处理逻辑没有问题。

参考文件 tcpcopy/src/tcpcopy/tc_session.h
struct tc_sess_s {
    ...
    /* ack sequence that is sent to backend (host byte order) */
    uint32_t target_ack_seq;
    ...
}

**Comment by wangbin579** [comment]
非常感谢
