### ISSUE TITLE
tcpcopy udp模式 -n参数 coredump

### ISSUE THREAD

**Issue by ylroki** [session-replay-tools/tcpcopy#227]
![qq 20150901214125](https://cloud.githubusercontent.com/assets/962848/9605777/3c18243a-50f2-11e5-9298-afffbf59383f.png)

tc_proc_ingress中调用get_test_pair检查ip、port是否为online机器，是则返回test机器ip、port，否返回NULL，然后修改原始报文

![qq 20150901214701](https://cloud.githubusercontent.com/assets/962848/9605915/0197650e-50f3-11e5-8b6a-30a1e4e8d519.png)

tcpcopy转发包时先调用一次tc_proc_ingress，修改了报文，复制模式下又拿该报文重复发送，replicate_packs会再次调用tc_proc_ingress，继而get_test_pair失败返回NULL，导致coredump

**Comment by wangbin579** [comment]
非常感谢你的反馈

2015-09-02






发件人：ylroki <notifications@github.com>
发送时间：2015-09-01 21:50
主题：[tcpcopy] tcpcopy udp模式 -n参数 coredump (#227)
收件人："session-replay-tools/tcpcopy"<tcpcopy@noreply.github.com>
抄送：


tc_proc_ingress中调用get_test_pair检查ip、port是否为online机器，是则返回test机器ip、port，否返回NULL，然后修改原始报文

tcpcopy转发包时先调用一次tc_proc_ingress，修改了报文，复制模式下又拿该报文重复发送，replicate_packs会再次调用tc_proc_ingress，继而get_test_pair失败返回NULL，导致coredump
