### ISSUE TITLE
线上机器请求较多时无法复制流量

### ISSUE THREAD

**Issue by ylroki** [session-replay-tools/tcpcopy#228]
线上机器tcp请求每秒1000+，每个请求大小500B左右，无法复制流量

log如下：

2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2015/09/08 11:40:52 +191 [error] send timeout,fd:6
2015/09/08 11:40:52 +191 [error] fd:6, msg send error
2015/09/08 11:41:19 +116 [warn] sig 2 received
2015/09/08 11:41:19 +116 [notice] active:13488,rel:26700,obs del:0,tw:9002
2015/09/08 11:41:19 +116 [notice] conns:19,resp:76,c-resp:19
2015/09/08 11:41:19 +116 [notice] resp fin:19,resp rst:0
2015/09/08 11:41:19 +116 [notice] send:35797,send content:19
2015/09/08 11:41:19 +116 [notice] send syn:19, fin:19,reset:35683
2015/09/08 11:41:19 +116 [notice] reconnect:0,for no syn:1
2015/09/08 11:41:19 +116 [notice] retransmit:0
2015/09/08 11:41:19 +116 [notice] recv packs after retransmission:0
2015/09/08 11:41:19 +116 [notice] syn cnt:40187,all clt:241542,clt cont:40188
2015/09/08 11:41:19 +116 [notice] total cont retransmit:0, frag:0
2015/09/08 11:41:19 +116 [notice] total captured packets:292363
2015/09/08 11:41:19 +116 [warn] many connections can't be established
2015/09/08 11:41:19 +116 [info] session table, size:65536, total:13488
2015/09/08 11:41:19 +116 [notice] user time used:3
2015/09/08 11:41:19 +116 [notice] sys  time used:2
2015/09/08 11:41:19 +116 [notice] max memory size:34824
2015/09/08 11:41:19 +116 [notice] voluntary ctx switches:186848
2015/09/08 11:41:19 +116 [notice] involuntary ctx switches:525
2015/09/08 11:41:19 +116 [notice] tc_epoll_destroy, close fd:5
2015/09/08 11:41:19 +116 [notice] tc_epoll_destroy, close fd:6
2015/09/08 11:41:19 +116 [notice] tc_epoll_destroy, close fd:8
2015/09/08 11:41:19 +116 [notice] tc_event_loop_finish over

**Comment by wangbin579** [comment]
建议采用pf_ring辅助的方式来运行tcpcopy
