### ISSUE TITLE
压力大时稳定丢包，定时日志每次都刷出大量unsend日志

### ISSUE THREAD

**Issue by ijasonjiang** [session-replay-tools/tcpcopy#229]
流量大的时候，出现大量丢包。

这里的packaget num上限我看是程序里宏定义设置的MAX_UNSEND_THRESHOLD=32768

缓存的package数目过大导致的丢包该如何fix

可以调大哪些参数限制试试？

ps，manual里虽然提到了unsend日志的问题，但是未找到解法方法。

日志如下：

2015/10/19 17:28:42 +507 [warn] unsend:candidate erased:20874,p:38663
2015/10/19 17:28:42 +507 [warn] unsend:candidate erased:9308,p:46899
2015/10/19 17:29:12 +507 [notice] active:4,rel reqs:1809,obs del:0
2015/10/19 17:29:12 +507 [notice] conns:1813,resp packs:68756,c-resp packs:0
2015/10/19 17:29:12 +507 [notice] send Packets:74868,send content packets:67626
2015/10/19 17:29:12 +507 [notice] send fin Packets:2,send reset packets:1806
2015/10/19 17:29:12 +507 [notice] reconnect for closed :0,for no syn:1811
2015/10/19 17:29:12 +507 [notice] retransmit:0
2015/10/19 17:29:12 +507 [notice] successful retransmit:0
2015/10/19 17:29:12 +507 [notice] syn cnt:2,all clt packs:65962,clt cont:47061
2015/10/19 17:29:12 +507 [notice] total client content retransmit:0,frag:0
2015/10/19 17:29:12 +507 [notice] total captured pakcets:847758
2015/10/19 17:29:12 +507 [notice] no responses after 60 secends
2015/10/19 17:29:12 +507 [notice] session size:4
2015/10/19 17:29:12 +507 [warn] unsend:crazy number of packets:40354,p:38663
2015/10/19 17:29:12 +507 [warn] unsend:too many packets:18714,p:46899
2015/10/19 17:29:12 +507 [warn] unsend:candidate erased:8296,p:34383
2015/10/19 17:29:12 +507 [warn] unsend:candidate erased:4131,p:57333

**Comment by wangbin579** [comment]
如果流量小的时候不丢包，而流量大的时候出现大量丢包，那么是抓包接口的问题。

从日志来看，c-resp packs:0，代表测试服务器上面的应用没有任何应答（除非应用本身没有应答），最好还是抓包分析一下，为啥这样

如果真如描述的那样，压力大稳定丢包，是很正常的，需要有机制来解决抓包接口的问题，tcpcopy本身不直接解决高压抓包接口的问题，而是利用现成的机制来解决。
解决方案有两个：
1）利用pcap兼容的pf_ring来辅助抓包
2）利用交换机镜像来复制线上的大量数据包

**Comment by ijasonjiang** [comment]
能否给个联系方式，具体咨询下
