### ISSUE TITLE
是否考虑支持windows服务器？

### ISSUE THREAD

**Issue by guillaume-lin** [session-replay-tools/tcpcopy#230]
我们的服务是运行在windows上面的，是否考虑支持windows系统呢？

**Comment by wangbin579** [comment]
可以参考：
https://github.com/session-replay-tools/tcpcopy/issues/39

通俗地讲，只要你能够做到以下几点，就可以对windows系统进行回放
1）流量镜像到运行tcpcopy的linux机器或者在winodows下，进行抓包，然后放到linux机器上面运行离线功能的tcpcopy

2）在windows被测试系统上面正确设置路由，把测试服务的应答包路由给运行intercept的linux机器

做到上面两点，即可回放windows服务，当然对其它os也是适用的
