### ISSUE TITLE
1.0新架构，测试机与辅助机没法同一个网段

### ISSUE THREAD

**Issue by xuke1668** [session-replay-tools/tcpcopy#231]
需要将业务数据双写测试新项目，但是测试机与辅助机没法在一个网段，想把测试机与辅助机集合在一起。但是不成功。
看日志有一条：[warn] many connections can't be established

不知道新架构怎么设置两个功能模块放在一台机器上，并发不大，所以影响不会太大，测试的目标不是压力，是数据。

**Comment by wangbin579** [comment]
如果在测试机器能够路由给一个没有路由转发功能的服务器或者具有流量黑洞功能的交换机，那么intercept就可以运行在测试机器上面，无需辅助机器了

**Comment by xuke1668** [comment]
我现在是这么做的：
1、我有一台机器上面有内网和外网IP，部署的haproxy，外网IP会有在线数据请求到haproxy的2222，然后我又起一个测试端口3333,。
2、先在机器上运行intercept -F 'tcp and src port 3333'
3、然后再运行tcpcopy -x 原服务端口2222-本机内网IP:测试端口3333 -s 本机内网IP -d 

这样好像也可以
