### ISSUE TITLE
target server接收不到任何数据

### ISSUE THREAD

**Issue by zerocoolys** [session-replay-tools/tcpcopy#232]
### 当前的情况 ###
1. 线上机 Centos6，内核版本3.10.0
    测试机和intercept机器是Ubuntu14.04
1. 2个机房，线上机一个，目标机和intercept在同一个
2. 网络是连通的，不管是ping，还是通过nc通讯都没有问题
3. tcpcopy和intercept运行起来之后可以看到有链接
intercecept机器是通过路由建立端口映射，所以IP是内网IP
![image](https://cloud.githubusercontent.com/assets/2757581/10935075/8d0620b4-831e-11e5-96c0-a00f7d7240d2.png)

4. tcpcopy运行之后没有error日志，但是有很多timeout
![image](https://cloud.githubusercontent.com/assets/2757581/10935224/9bac426e-831f-11e5-820a-120884fdf8f9.png)

 另外还有 unsend
![image](https://cloud.githubusercontent.com/assets/2757581/10935241/c2f669a8-831f-11e5-8b54-635e02ab1bb9.png)

在目标机跑tcpdump对应的端口，一直没有收到数据。

### 疑问 ###
1. tcpcopy的-c参数只要是和target机器的网关配置一致就行了吗？ 
2. 会是机房的问题吗？网络是连通的

如果有需要的话可以提供日志（太大了只有截图）

@wangbin579 非常感谢了

**Comment by wangbin579** [comment]
网络是复杂的，-c参数的ip地址，关键是能够通过各个网络设备（比较交换机）。

网络连通跟tcpcopy能够转发是两码事情。

抓包分析是关键，分析出为啥tcpcopy转发的数据包，为啥不能到达测试机器
