### ISSUE TITLE
是否支持多个tcpcopy实例连接intercept？或者多个intercept监听不同端口？

### ISSUE THREAD

**Issue by houcy** [session-replay-tools/tcpcopy#234]
我是按老的架构编译的，tcpcopy连接intercpet，没有用到辅助server，我是用的offline方式回放流量包，运行正常可以回放流量包压测，我想运行多个tcpcopy实例连接intercept，以增大流量，但是没起作用；另外我也尝试了运行多个intercept实例监听不同的端口，也不起作用，貌似只能运行一个Intercept实例才能正常从收包。

请问这个是什么问题呢？如何才能加大压测流量(offline方式)呢？tcpcopy的-n参数对我不起作用，我的应用程序只允许有一个来自同一个客户端IP的连接，不能简单地增大几倍流量。

谢谢！

**Comment by wangbin579** [comment]
如果只允许有一个来自同一个客户端IP的连接，那么就采用-c参数（如果版本支持这个参数的话，不支持的话，更新成支持此参数的版本）来修改客户端源ip地址，这样运行多个tcpcopy实例应该就可以了。
