### ISSUE TITLE
ＨＴＴＰＳ　协议支持吗　？

### ISSUE THREAD

**Issue by zerolugithub** [session-replay-tools/tcpcopy#236]

**Comment by wangbin579** [comment]
tcpcopy是基于tcp层面的copy，是不考虑上层应用协议的破解的，所以一切不具备回放特性的协议（包括ssl类的协议），都是不能支持的，除非二次开发

**Comment by bluesky129** [comment]
@wangbin579 请教二次开发的思路是什么？
