### ISSUE TITLE
tcpcopy莫名自动退出

### ISSUE THREAD

**Issue by tannoliu** [session-replay-tools/tcpcopy#237]
hi， 遇到一个问题，我想长时间使用tcpcopy来测试服务，所以线上机器将tcpcopy作为后台进程常驻，跑了10几个小时之后突然就退出了，不知道什么原因，辛苦帮忙解答，日志如下：

2015/12/28 20:27:07 +720 [warn] sig 1 received
2015/12/28 20:27:07 +720 [notice] active:486,rel reqs:82,obs del:56
2015/12/28 20:27:07 +720 [notice] conns:567,resp packs:195889842,c-resp packs:111075611
2015/12/28 20:27:07 +720 [notice] send Packets:310546093,send content packets:199469245
2015/12/28 20:27:07 +720 [notice] send fin Packets:22,send reset packets:61
2015/12/28 20:27:07 +720 [notice] reconnect for closed :0,for no syn:519
2015/12/28 20:27:07 +720 [notice] retransmit:0
2015/12/28 20:27:07 +720 [notice] successful retransmit:0
2015/12/28 20:27:07 +720 [notice] syn cnt:49,all clt packs:155119873,clt cont:74230239
2015/12/28 20:27:07 +720 [notice] total client content retransmit:2,frag:0
2015/12/28 20:27:07 +720 [notice] total captured pakcets:261971983
2015/12/28 20:27:07 +720 [notice] remove timer over
2015/12/28 20:27:07 +720 [notice] enter destroy_for_sessions
2015/12/28 20:27:07 +720 [notice] total visit hash_find_node:0,compared:0
2015/12/28 20:27:07 +720 [notice] destroy items 0 in table name:transfer port table
2015/12/28 20:27:07 +720 [notice] leave destroy_for_sessions
2015/12/28 20:27:07 +720 [notice] it close socket:4
2015/12/28 20:27:07 +720 [notice] enter tc_event_destroy:4
2015/12/28 20:27:07 +720 [notice] destroy event:4
2015/12/28 20:27:07 +720 [notice] it close socket:5
2015/12/28 20:27:07 +720 [notice] enter tc_event_destroy:5
2015/12/28 20:27:07 +720 [notice] destroy event:5
2015/12/28 20:27:07 +720 [notice] destroy addr table
2015/12/28 20:27:07 +720 [notice] total visit hash_find_node:571,compared:569
2015/12/28 20:27:07 +720 [notice] destroy items 1 in table name:address-table
2015/12/28 20:27:07 +720 [notice] tc_select_destroy, close fd:7
2015/12/28 20:27:07 +720 [notice] tc_event_loop_finish over

intercept在20:27:07这个时间点的log如下：

2015/12/28 20:27:07 +764 [notice] return -1,fd:6 (Connection reset by peer)
2015/12/28 20:27:07 +764 [notice] release tunnel related resources, fd:6
2015/12/28 20:27:07 +764 [notice] enter tc_event_destroy:6
2015/12/28 20:27:07 +764 [notice] destroy event:6
2015/12/28 20:27:07 +765 [notice] return -1,fd:7 (Connection reset by peer)
2015/12/28 20:27:07 +765 [notice] release tunnel related resources, fd:7
2015/12/28 20:27:07 +765 [notice] enter tc_event_destroy:7
2015/12/28 20:27:07 +765 [notice] destroy event:7

**Comment by wangbin579** [comment]
从log来看，是因为tcpcopy收到了SIGHUP信号导致了退出。

不知道tcpcopy运行的时候有没有加上-d参数？

**Comment by tannoliu** [comment]
没有加，tcpcopy我是使用nohup & 后台启动的， 这个和-d有什么区别么

**Comment by wangbin579** [comment]
先看看加-d，会不会出现上述问题吧

**Comment by wangbin579** [comment]
还这样吗？
