### ISSUE TITLE
下载intercept-1.0.0.tar.gz, 并安装. 在运行make编译的时候, 出现make: *** No rule to make target `build', needed by `default'.  Stop

### ISSUE THREAD

**Issue by jingwangfei** [session-replay-tools/tcpcopy#238]
下载intercept-1.0.0.tar.gz, 并安装. 
在运行make编译的时候, 出现make: *** No rule to make target `build', needed by `default'.  Stop.
这个是什么原因呢? 是因为安装文件没有更新吗?

**Comment by wangbin579** [comment]
这得看configure的 输出信息，是不是有提示哪些组件没有安装，比如pcap相关库

**Comment by jingwangfei** [comment]
thanks very much!
确实是这样, pcap开发库没有安装, 运行一下命令, 安装下即可
yum install libpcap-devel

**Comment by leafonsword** [comment]
'libpcap-devel'这样的依赖能不能在安装指南里说明下需要依赖？
