### ISSUE TITLE
版本0.8，测试服务器未接收到请求

### ISSUE THREAD

**Issue by JiLongQiu** [session-replay-tools/tcpcopy#239]
从tcpdump来看，intercept可以接收到包，client端也可以，
两端的连接是建立了的，而且我请求一次，使用tcpdump时，
两端都是正常的数据交流，一次length大于0的数据传输，
一次length=0的数据确认

但是就是到不了测试机上面的应用，tcpcopy的日志一直是：
[warn] no responses after 3191 secends
[warn] many connections can't be established

我在我们的测试环境，两台测试机上，是成功复制了流量的
但是我用在线上机器就不行，可以帮我推断一下这个问题的原因么？

**Comment by wangbin579** [comment]
这种问题，关键是要抓测试服务器的包，看看tcpcopy复制过去的数据包到哪儿就被干掉了，看intercept的数据包是没有多少用的。

不同的环境，不同的安全限制
