### ISSUE TITLE
tcpcopy离线模式问题

### ISSUE THREAD

**Issue by zhangrandl** [session-replay-tools/tcpcopy#241]
你好，麻烦问下，我从线上tcpdump的pcap文件，放到本地tcpcopy跑，有日志生成
tcpcopy日志
2016/02/01 11:17:53 +709 [notice] tcpcopy version:1.0.0
2016/02/01 11:17:53 +709 [notice] tcpcopy internal version:6
2016/02/01 11:17:53 +709 [notice] target:8087-10.30.0.27:8087
2016/02/01 11:17:53 +709 [notice] TC_OFFLINE mode
2016/02/01 11:17:53 +709 [notice] TC_COMBINED mode
2016/02/01 11:17:53 +709 [notice] epoll mode
2016/02/01 11:17:53 +709 [notice] session timeout:120
2016/02/01 11:17:53 +709 [notice] keepalive timeout:240
2016/02/01 11:17:53 +709 [notice] min sess pool size:576
2016/02/01 11:17:53 +709 [notice] sess pool size:1024
2016/02/01 11:17:53 +709 [notice] set global port for tcpcopy
2016/02/01 11:17:53 +709 [notice] parallel connections per target:2
2016/02/01 11:17:53 +709 [notice] accelerated 1 times,interval:0 ms
2016/02/01 11:17:53 +709 [notice] s parameter:10.30.0.27
2016/02/01 11:17:53 +709 [notice] set only ip for tcpcopy
2016/02/01 11:17:53 +709 [info] pool:17486752,block:17503152,len:44 occupy
2016/02/01 11:17:53 +709 [info] pool:17486752,block:17503152,len:44 occupy
2016/02/01 11:17:53 +709 [info] connect to remote server(10.30.0.27:36524)
2016/02/01 11:17:53 +709 [info] connect to remote server(10.30.0.27:36524)
2016/02/01 11:17:53 +709 [notice] open pcap success:/root/online.pcap
2016/02/01 11:17:53 +709 [notice] send the first packets here
2016/02/01 11:18:13 +144 [notice] stop, null from pcap_next
2016/02/01 11:18:23 +709 [notice] active:0,rel:212,obs del:0,tw:0
2016/02/01 11:18:23 +709 [notice] conns:212,resp:849,c-resp:213
2016/02/01 11:18:23 +709 [notice] resp fin:212,resp rst:0
2016/02/01 11:18:23 +709 [notice] send:1151,send content:212
2016/02/01 11:18:23 +709 [notice] send syn:212, fin:127,reset:85
2016/02/01 11:18:23 +709 [notice] reconnect:0,for no syn:0
2016/02/01 11:18:23 +709 [notice] retransmit:0
2016/02/01 11:18:23 +709 [notice] recv packs after retransmission:0
2016/02/01 11:18:23 +709 [notice] syn cnt:212,all clt:905,clt cont:212
2016/02/01 11:18:23 +709 [notice] total cont retransmit:0, frag:0
2016/02/01 11:18:23 +709 [notice] total captured packets:4284

intercept日志（因为有很多，就截取了最后面一点）

2016/02/01 11:18:13 +024 [notice] from bak:10.171.42.190:53992-->10.30.0.27:8087,len 438,seq=797756471,ack=3063982812
2016/02/01 11:18:13 +027 [notice] fd is null after session is created
2016/02/01 11:18:13 +027 [notice] from bak:10.171.42.190:53992-->10.30.0.27:8087,len 52,seq=797756857,ack=3063982933
2016/02/01 11:18:13 +029 [notice] fd is null after session is created
2016/02/01 11:18:13 +029 [notice] from bak:10.171.42.190:53992-->10.30.0.27:8087,len 52,seq=797756857,ack=3063982934
2016/02/01 11:18:13 +029 [notice] reset from tcp
2016/02/01 11:18:13 +054 [notice] fd is null after session is created
2016/02/01 11:18:13 +054 [notice] from bak:10.171.42.190:53997-->10.30.0.27:8087,len 52,seq=881913709,ack=672865911
2016/02/01 11:18:13 +054 [notice] fd is null after session is created
2016/02/01 11:18:13 +054 [notice] from bak:10.171.42.190:53997-->10.30.0.27:8087,len 438,seq=881913709,ack=672865911
2016/02/01 11:18:13 +057 [notice] fd is null after session is created
2016/02/01 11:18:13 +057 [notice] from bak:10.171.42.190:53997-->10.30.0.27:8087,len 52,seq=881914095,ack=672866032
2016/02/01 11:18:13 +059 [notice] fd is null after session is created
2016/02/01 11:18:13 +059 [notice] from bak:10.171.42.190:53997-->10.30.0.27:8087,len 52,seq=881914095,ack=672866033
2016/02/01 11:18:13 +059 [notice] reset from tcp
2016/02/01 11:18:13 +134 [notice] fd is null after session is created
2016/02/01 11:18:13 +134 [notice] from bak:10.171.42.190:54001-->10.30.0.27:8087,len 52,seq=1529665518,ack=64493704
2016/02/01 11:18:13 +134 [notice] fd is null after session is created
2016/02/01 11:18:13 +134 [notice] from bak:10.171.42.190:54001-->10.30.0.27:8087,len 416,seq=1529665518,ack=64493704
2016/02/01 11:18:13 +137 [notice] fd is null after session is created
2016/02/01 11:18:13 +137 [notice] from bak:10.171.42.190:54001-->10.30.0.27:8087,len 52,seq=1529665882,ack=64493826
2016/02/01 11:18:13 +137 [notice] fd is null after session is created
2016/02/01 11:18:13 +137 [notice] from bak:10.171.42.190:54001-->10.30.0.27:8087,len 52,seq=1529665882,ack=64493826
2016/02/01 11:18:13 +137 [notice] fd is null after session is created
2016/02/01 11:18:13 +137 [notice] from bak:10.30.0.27:8087-->10.30.0.27:54001,len 52,seq=64493826,ack=1529665883
2016/02/01 11:18:15 +875 [notice] total resp packs:2381, all:2381, route:339, sock write cnt:840
2016/02/01 11:18:15 +875 [notice] cache hit:761,missed:0,lost:1620
2016/02/01 11:18:15 +875 [notice] search:2381,extra compared:8,all sessions:339
2016/02/01 11:18:45 +875 [notice] total resp packs:2381, all:2381, route:339, sock write cnt:840
2016/02/01 11:18:45 +875 [notice] cache hit:761,missed:0,lost:1620
2016/02/01 11:18:45 +875 [notice] search:2381,extra compared:8,all sessions:339

./intercept -F "tcp and port 8087"
./tcpcopy -x 8087-10.30.0.27:8087 -s 10.30.0.27  -i /root/online.pcap

pcap文件是dump的nginx反向解析tomcat的包，在tomcat所在的服务器上导出的，但是在本地回放的时候，tomcat没有日志，我不知道这样是否是正常的。

**Comment by wangbin579** [comment]
首先，intercept的过滤条件应该精确地写成”tcp and src port 8087“，因为intercept没有运行在单独的机器上面，而是和tomcat运行在一起，intercept大量的notice log就说明了这一点。


其次，tomcat没有日志，不代表没有请求过来，从tcpcopy的日志已经看出，tomcat已经在处理请求了：
conns:212,resp:849,c-resp:213（tomcat已经回复了213个带有响应内容的数据包）
你可以在tomcat服务器内抓一下包，看看tomcat到底怎么回复了，是拒绝呢，还是有正常响应？


再次，路由有没有设置，如果没有默认黑洞机制的话，应该要设置路由的，否则可能会影响回放的进行。


最后，所有服务器的问题，最好通过抓包来分析出原因，切不可只从应用层的角度来看问题

**Comment by zhangrandl** [comment]
实在不好意思，关于路由方面知识实在是薄弱，不知道该如何去设置，能否告知一下原理？

**Comment by wangbin579** [comment]
设置路由其实不难：
首先要明确测试服务的响应数据包到底回到哪些客户端，找出客户端的ip地址，比如10.171.42.190这些客户端ip地址。如果实在不知道这些ip地址，可以通过tcpcopy的-c参数来修改客户端的ip地址为指定的ip地址，这样更为简单一下。

其次，知道了这些客户端的ip地址后，针对这些客户端ip地址设置路由（具体可以google）到一个不存在路由转发功能的服务器中去，目的是让这些响应数据包消失掉，不能让他们回到真正的客户端，否则会干扰测试的进行

**Comment by zhangrandl** [comment]
多谢，10.171.42.190这台服务器是线上nginx服务器，10.30.0.27是测试环境的tomcat应用服务器，这两台服务器是无法直接连通的。这样的话，响应数据包是不可能到达真正客户端的，是不是就不需要设置路由了？

**Comment by wangbin579** [comment]
得看第二次握手数据包回去后，是否在1s内有相应的reset数据包回来，如果大量存在reset，且间隔时间很短，还得设置路由，如果没有，则说明路途过程中就存在黑洞，这样就无需设置了。
