### ISSUE TITLE
请求在线上服务器就reset 掉了是怎么一个情况

### ISSUE THREAD

**Issue by kukukafei** [session-replay-tools/tcpcopy#242]
我按照说明搭建了下测试环境，我在tcpcopy端抓包能看到请求有复制，但是复制的请求在发送SYN包给测试服务器的时候就被reset掉了，在测试服务器上没有抓到任何请求包，麻烦请问下这个是怎么回事呢？

**Comment by wangbin579** [comment]
如果同一个session内，syn和reset数据包相差3s，那么是tcpcopy自身发送的reset的，不用管这个reset数据包，这种情况说明syn数据包根本就到不了测试服务器。

道路不通，测试必然是失败的，需要查明为啥不通或者避开安全限制，才能继续下去。

**Comment by kukukafei** [comment]
我看了下，reset 包差不多相差3s, 因为是用阿里云的服务器，因此可能是由于服务器都不在同一个网段内造成的。
如果需要跨网段的话，tcpcopy这块我需要怎么配置下呢，能否把辅助和测试放到同一台机器上？

**Comment by wangbin579** [comment]
是复制的数据包到不了测试服务器，跟辅助和测试放到同一台机器没有关系吧

尽量不要跨网段吧，因为一旦遇到问题，不是一般的麻烦

**Comment by yuanmomo** [comment]
@wangbin579 请问下，我这边情况貌似类似，reset 包差3秒，应该怎么排除呢？不好意思，最难刚开始弄这个问题，
![tcpcopy](https://cloud.githubusercontent.com/assets/3326055/13740260/bb2e3a0a-ea0a-11e5-9d33-c868862ed89b.png)

**Comment by yuanmomo** [comment]
@wangbin579 这个是 tcpdump 的文件哈，看了一下，已经ack 了，但是还是要求重传了
[tcpdump.zip](https://github.com/session-replay-tools/tcpcopy/files/171690/tcpdump.zip)
![tcpdump](https://cloud.githubusercontent.com/assets/3326055/13741095/453194dc-ea0f-11e5-8609-1c21479e6633.jpg)

**Comment by wangbin579** [comment]
路由设置了吗或者设置对了吗？
   如果认为没有问题，在辅助服务器上面利用tcpdump查看syn+ack到辅助服务器了吗？
          如果到了，intercept的-F参数是否设置妥当？
                 如果设置妥当，辅助服务器的系统参数ip forward是否设置成了1，如果是，改成默认的0

**Comment by yuanmomo** [comment]
@wangbin579 对不住哈，昨天是急着了，问问题的信息没给好，我今天再看一下好啊，如果有问题，我给个详细的！初步分析的原因：

**Comment by yuanmomo** [comment]
三次握手没有完成，应该阿里云的安全组导致的问题，今天加入同一个安全组再试一下。。


谢谢哈！
