### ISSUE TITLE
工作需要研究整理出来的tcpcopy交互时序图

### ISSUE THREAD

**Issue by zhaoguangnan** [session-replay-tools/tcpcopy#244]
[tcpcopy与TestServer三次握手时序图](https://raw.githubusercontent.com/zhaoguangnan/note/e56071ffaec892956635dae9abdfe4d1c63409fb/images/tcpcopy.png)

**Comment by wangbin579** [comment]
至少我看懂了

**Comment by zhaoguangnan** [comment]
谢谢，官网的图我真的没怎么看懂。我分析的有问题吗？

**Comment by wangbin579** [comment]
没有问题

**Comment by zhaoguangnan** [comment]
有一个问题：如果指定-c参数为单独的ip，好多台nginx同一时间向后端服务发起tcp的端口是一样的，会不会导致测试服务器tcp连接错乱了？

**Comment by wangbin579** [comment]
最好根据情况设置-c
如果客户端ip地址只有一个，-c就设置成单个ip地址；
如果是多个ip地址，则用网段地址来对付。

不同客户端的源端口一般是随机的，如果多个ip地址映射为单个ip地址，那么可能会导致四元组冲突（冲突概率跟连接数量成正比），导致回放失败

**Comment by zhaoguangnan** [comment]
谢谢大神
