### ISSUE TITLE
正式服务器 与测试服务器 三次握手失败

### ISSUE THREAD

**Issue by yuanmomo** [session-replay-tools/tcpcopy#246]
- 环境，阿里云，专有网络 VPC 环境 ：

    - A（正式机）： 10.0.0.4； CentOS 7.2.1511 ；服务端口 3306
    - B（测试机）： 10.0.0.5( slave1 )；CentOS  7.0.1406 ；服务端口 8010
    - C（assistant server）： 10.0.0.6( slave2 )；CentOS 7.0.1406
    - tcpcopy 和 intercept都是最新的 1.0.0 版本

        <img width="265" alt="933524ec-a368-4e07-81af-a6caad3a37cd" src="https://cloud.githubusercontent.com/assets/3326055/13772519/98b9e8fa-eacf-11e5-9086-b3361506c1be.png"><img width="278" alt="7254a48e-b3d1-41a9-817d-96a111b802a9" src="https://cloud.githubusercontent.com/assets/3326055/13772523/9beecea0-eacf-11e5-95cd-46d7d823cc62.png">

- 参考资料：github 文档和 http://blog.csdn.net/wangbin579/article/details/8950282

- C 机器运行：
      <img width="680" alt="3e20dc8b-17ca-41b3-8b84-c5ba76ebe693" src="https://cloud.githubusercontent.com/assets/3326055/13772536/a5c30d4c-eacf-11e5-9d5c-e980892934e7.png">

- B 机器添加路由：
    - route add -net 192.168.100.0/24 gw 10.0.0.6
    <img width="559" alt="8ce35b4e-6d69-42ee-932b-e2e0bd1f165b" src="https://cloud.githubusercontent.com/assets/3326055/13772564/ca31a6fc-eacf-11e5-872d-5b44beca0780.png">

- A 机器执行 tcpcopy：/usr/local/tcpcopy/sbin/tcpcopy -x 3306-10.0.0.5:8010 -s 10.0.0.6 -c 192.168.100.x -l /data/logs/tcpcopy/tcpcopy.log -d

<img width="1190" alt="6055f110-5eea-47ff-b9d2-48239f2fbbdb" src="https://cloud.githubusercontent.com/assets/3326055/13772578/e0f7d104-eacf-11e5-9084-e38d49295828.png">

- A抓包：tcpdump host \( 10.0.0.4 or 192.168.100.1 \)  and \(10.0.0.5 or 10.0.0.6 \) -w a.cap
- B抓包：tcpdump host 10.0.0.5 and \(10.0.0.4 or 10.0.0.6 or 192.168.100.1 \)  -w b.cap
- C抓包： tcpdump host 10.0.0.6 and \(10.0.0.4 or 10.0.0.5\) -w c.cap
- 服务器没有压力，是自测试，手动一条条请求刷。

- 问题：
-

- B 机器的路由表，0.0.0.0 在最开始，匹配时有先后顺序吗？
- 分析 a.cap的日志，发现 A 机器 发送数据包替换了 IP地址，这个时候，B 在三次握手，给替换后的 IP地址，192.168.100.1返回 ack 确认的时候，这个数据包是需要从 B 机器 走路由到 C 机器，然后再由 C 机器转给 A 机器的 tcpcopy 吗？B 机器给 A 机器的 ack 重传了。
<img width="1268" alt="4cd6375a-a24a-41d5-a159-1ce41d88e2f2" src="https://cloud.githubusercontent.com/assets/3326055/13772672/58f146d6-ead0-11e5-99e4-6738655b1701.png">
![94650a03-cf9b-44c8-9768-a8deaa346e2a](https://cloud.githubusercontent.com/assets/3326055/13772686/6a534780-ead0-11e5-928b-f69688951945.png)

- 在  B 机器上tcpdump 所有的包 length 都为 0 。

<img width="1339" alt="4c820709-1075-4700-820d-490a217f6e38" src="https://cloud.githubusercontent.com/assets/3326055/13772697/770aa338-ead0-11e5-8c57-c8ce60de162f.png">

     请帮忙看一下，帮忙提供一下排查方法，万分感谢！网络基础只是薄弱，但是项目赶紧，请见谅！

    A,B,C三台机器的 tcpdump 的数据文件：
[tcpdump.zip](https://github.com/session-replay-tools/tcpcopy/files/173548/tcpdump.zip)

**Comment by wangbin579** [comment]
你应该抓192.168.100网段的数据包，分析才有用，毕竟访问测试服务器的是这个网段的ip地址。

你看看在C上面能不能抓到192.168.100网段的ip地址数据包：
   如果能，说明路由生效了。
   如果不能，intercept直接运行在B上面，看看有没有效果

**Comment by wangbin579** [comment]
如果三次握手问题解决了，可能还有如下问题：
3306端口的应用，一般是MySQL应用，如果要想成功复制这种类型的请求，方法有两个：
1）https://github.com/session-replay-tools/mysql-replay-module
2）https://github.com/session-replay-tools/mysql-sgt-replay-module

**Comment by yuanmomo** [comment]
@wangbin579 端口的问题是因为要外网开放，别的端口有数据干扰。3306是由于之前本机装了数据库，所以对外开放了，后面数据库买了阿里云的 rds，3306后面的服务器是 一个 netty 实现的 http server。
我先判断一下路由有没有生效哈！

还有我想问的就是，三次握手的时候，也是需要走 intercept 的么？

**Comment by yuanmomo** [comment]
@wangbin579 吧 intercept 直接运行到 B 上，成功了，那就是 B 的路由有问题！linux 有什么工具可以排查B 的数据包怎么没有路由到 C 么？今天成功的路由表配置只是修改了  gw 的值。

**Comment by wangbin579** [comment]
路由设置对，未必能够100%到达辅助服务器，也有可能被云平台安全过滤了。

辅助服务器没有抓到，只能推测出路由的设置没有达到目的。
至于为啥没有到达辅助服务器，如果是物理机，那就简单，但是在云平台这个大环境，就不好说了。

**Comment by wangbin579** [comment]
当然如果云平台确实有安全过滤，那也挺好，就不需要辅助服务器来充当黑洞了，intercept直接运行在测试服务器即可。

**Comment by yuanmomo** [comment]
@wangbin579  就是这样过滤了，导致 B 服务器不能到 辅助服务器，必须要把 B 和 辅助放在一台机器！回头我查一下原因！

万分感谢！

**Comment by yuanmomo** [comment]
@wangbin579 对了，还有一个哈，我离线录制的 tcpdump -w 的文件，回放的时候很慢，是正常的么？

**Comment by yuanmomo** [comment]
正式机上tcpdump 了 一个 5G 的文件，回放感觉很慢。

**Comment by wangbin579** [comment]
因为没有上下文，无法分析.

候选改进方法：
1）抓包可以只抓请求方向的流量，比如tcpdump -i any tcp and dst port 3306 -s 1500 -w 3306.pcap，以降低抓包量

2）如果线上压力大，可以辅助pf_ring或者netmap来抓包，确保抓包没有丢包

在上述条件下，不应该回放很慢

**Comment by yuanmomo** [comment]
@wangbin579  找到问题了哈！第一个是挂在了有负载均衡，前段的 lvs 会不停地去扫描服务器的端口！其次，测试机 拿到正式机的 pcap 文件后，测试记的端口和 正式机必须要一致！
由于测试机安装的应用较多，所以端口跟正式机不一致，修改过后，就很快了！

万分感谢, 这个 issue 可以 close 了哈，我今天也开始整理文档了。
