### ISSUE TITLE
src host localost but dst host not

### ISSUE THREAD

**Issue by 12789** [session-replay-tools/tcpcopy#247]
执行命令后日志里内容如下

> 2016/04/04 11:45:29 +498 [warn] src host **localost** but dst host not
> 2016/04/04 11:45:29 +498 [warn] use -H to avoid this warning

两个问题：
1. 上面日志里加粗的内容是否应该是"localhost"?
2. 使用H参数后，

> tcpcopy: illegal argument "H"

**Comment by wangbin579** [comment]
多谢了

**Comment by chaorongguo** [comment]
这个问题解决了吗， 我的应用在docker中也遇到了这个问题
