### ISSUE TITLE
使用tcpcopy指令，-n选项值大于100时流量没有变化

### ISSUE THREAD

**Issue by xuliang5618** [session-replay-tools/tcpcopy#248]
您好：
我在使用tcpcopy工具测试本地服务器时，修改tcpcopy指令-n选项大于100，试图继续放大流量，发现流量没有明显变化。
具体过程是：当-n分别为1、10、100时，可以看到具体接口调用qps的明显变化，当-n为100、1000、10000时，统计到的接口qps基本相同。
请问可能导致该问题的原因会是什么，配置或者是服务器性能的问题？
![](http://weipos.oss-cn-hangzhou.aliyuncs.com/4c4bc0559382e72b95cad2241eabe790.jpg)

**Comment by wangbin579** [comment]
加大倍数，只是尽力模式，未必能够保证放大多少倍。

同一个tcpcopy实例情况下加大倍数，有如下问题：
1）所能修改的只是客户端端口号，而端口号是有限的，倍数越大，冲突的概率越大。
2）tcpcopy是单进程的，所能处理的能力也是有限的

采用多个实例并且采用不同的客户端ip地址，可以缓解上述问题
