### ISSUE TITLE
Tcpcopy mysql大并发下验证问题

### ISSUE THREAD

**Issue by tenato** [session-replay-tools/tcpcopy#250]
问题描述以及tcpcopydebug日志内容详解：http://pan.baidu.com/s/1eRXcauY
请大牛帮忙分析下原因，非常感谢！

**Comment by wangbin579** [comment]
默认tcpcopy是不会去处理MySQL协议相关内容的，比如压力大的时候会出现丢包，从而导致session会话失败，即使tcpcopy努力去重新创建MySQL连接，也会因为缺乏MySQL验证过程而被MySQL拒绝掉。

所以MySQL回放，还得用下面的：

https://github.com/session-replay-tools/mysql-replay-module

或者

https://github.com/session-replay-tools/mysql-sgt-replay-module

**Comment by tenato** [comment]
好的，谢谢！
我用mysql-sgt-replay-module在试一下。

**Comment by tenato** [comment]
使用了mysql-sgt-replay-module就正常了，非常感谢您的支持
