### ISSUE TITLE
关于tcpcopy异常退出的异常，tcpcopy自动关闭

### ISSUE THREAD

**Issue by zealot00** [session-replay-tools/tcpcopy#252]
您好：

再测试过程中发现1.0版本如果client和server不在同一个网络情况下，运行几分钟后自动退出。
日志如下：
tcpcopy.log
2016/04/28 15:46:02 +338 [notice] voluntary ctx switches:197759
2016/04/28 15:46:02 +338 [notice] involuntary ctx switches:423
2016/04/28 15:46:02 +338 [notice] active:2057,rel:18108,obs del:0,tw:2056
2016/04/28 15:46:02 +338 [notice] conns:20165,resp:83133,c-resp:40302
2016/04/28 15:46:02 +338 [notice] resp fin:20164,resp rst:0
2016/04/28 15:46:02 +338 [notice] send:114072,send content:20164
2016/04/28 15:46:02 +338 [notice] send syn:20165, fin:19956,reset:3874
2016/04/28 15:46:02 +338 [notice] reconnect:0,for no syn:0
2016/04/28 15:46:02 +338 [notice] retransmit:2
2016/04/28 15:46:02 +338 [notice] recv packs after retransmission:2
2016/04/28 15:46:02 +338 [notice] syn cnt:20165,all clt:116051,clt cont:20164
2016/04/28 15:46:02 +338 [notice] total cont retransmit:0, frag:0
2016/04/28 15:46:02 +338 [notice] total captured packets:426779
2016/04/28 15:46:17 +112 [error] raw fd:15 (Operation not permitted)
2016/04/28 15:46:17 +112 [warn] to bak:192.168.200.7:9351-->tcpcopy服务器:8080,len 52,seq=753380728,ack=0
2016/04/28 15:46:17 +112 [error] send to back error,tot_len is:52
2016/04/28 15:46:17 +112 [warn] sig 64 received
2016/04/28 15:46:17 +112 [notice] active:2085,rel:23080,obs del:0,tw:2082
2016/04/28 15:46:17 +112 [notice] conns:25163,resp:103492,c-resp:50254
2016/04/28 15:46:17 +112 [notice] resp fin:25162,resp rst:0
2016/04/28 15:46:17 +112 [notice] send:142327,send content:25162
2016/04/28 15:46:17 +112 [notice] send syn:25165, fin:24917,reset:4876
2016/04/28 15:46:17 +112 [notice] reconnect:0,for no syn:0
2016/04/28 15:46:17 +112 [notice] retransmit:4
2016/04/28 15:46:17 +112 [notice] recv packs after retransmission:4
2016/04/28 15:46:17 +112 [notice] syn cnt:25165,all clt:144754,clt cont:25164
2016/04/28 15:46:17 +112 [notice] total cont retransmit:0, frag:0
2016/04/28 15:46:17 +112 [notice] total captured packets:513421
2016/04/28 15:46:17 +112 [info] session table, size:65536, total:2085
2016/04/28 15:46:17 +112 [notice] user time used:6
2016/04/28 15:46:17 +112 [notice] sys  time used:10
2016/04/28 15:46:17 +112 [notice] max memory size:8908
2016/04/28 15:46:17 +112 [notice] voluntary ctx switches:240626
2016/04/28 15:46:17 +112 [notice] involuntary ctx switches:533
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:5
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:6
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:7
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:8
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:9
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:10
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:11
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:12
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:13
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:14
2016/04/28 15:46:17 +112 [notice] tc_epoll_destroy, close fd:16
2016/04/28 15:46:17 +112 [notice] tc_event_loop_finish over

**Comment by wangbin579** [comment]
看看系统日志，是否因为系统限制了复制，比如类似如下的提示：
kernel: nf_conntrack: table full, dropping packet

假设是，我们可以解释如下：
因为采用raw socket（默认）发包方式，在没有关闭nf_conntrack内核模块的情况下，如果报nf_conntrack: table full, dropping packet，那么通过raw socket发包，系统会报出：Operation not permitted错误，这时候tcpcopy会退出。

我们可以采用如下三种方案来避开此问题:
1、关闭nf_conntrack内核模块，这样就不会报内核级别的错误
2、对tcpcopy转发的数据包不track，避开conntrack陷阱
3、采用pcap来发包（--enable-dlinject），避开ip层的检测

**Comment by wangbin579** [comment]
修正一下，1.0版本采用pcap-send来发包，可以避开ip层的各种陷阱

当然在连接数量特别多的时候，才会出现conntrack的陷阱，而且线上环境，即使不用tcpcopy，如果连接特别多，开启conntrack会大大降低系统的性能，所以建议对连接数量多的场合，建议不开启conntrack
