### ISSUE TITLE
做tcpcopy如何带上真实的用户IP到压测服务器？

### ISSUE THREAD

**Issue by lileichinasoft** [session-replay-tools/tcpcopy#253]
./tcpcopy -x 80-61.135.233.160:8080 -s 61.135.233.161 -c 62.135.200.x

比如现在指定的客户端IP是以下网段：62.135.200

如何想获取到线上真实用户请求IP，该如何配置？谢谢~~~

**Comment by wangbin579** [comment]
方法很简单，不带-c参数。

需要注意的是，你需要弄清楚客户端ip地址有哪些，如果是外网应用，那么一般设置默认路由即可

**Comment by lileichinasoft** [comment]
@wangbin579 多谢~，我这边客户端IP是外网，按照你说的方法我试下；在压测服务器反向代理nginx上直接通过remote_addr就可以获取到真实ip了吧？

**Comment by wangbin579** [comment]
应该是吧

btw，tcpcopy用-c参数，是为了方便设置路由，如果为真实性考虑，显然不用-c更好。

**Comment by lileichinasoft** [comment]
OK，多谢~

**Comment by lileichinasoft** [comment]
@wangbin579 不设置-c的话，压测机器的出口流量（响应）是不是会打到线上机器啊，我现在是这样的：

线上机器A（作为tcpcopy的client） ----> 压测机器B（作为tcpcopy的Server） --（route）--> intercept机器

**Comment by wangbin579** [comment]
判断会不会，可以抓包分析一下
