### ISSUE TITLE
tcpcopy启动内核模块ip_queue失败

### ISSUE THREAD

**Issue by lileichinasoft** [session-replay-tools/tcpcopy#254]
modprobe ip_queue

FATAL: Error inserting ip_queue (/lib/modules/2.6.32-573.el6.x86_64/kernel/net/ipv4/netfilter/ip_queue.ko): Device or resource busy

**Comment by lileichinasoft** [comment]
tcpcopy版本0.6.0

**Comment by wangbin579** [comment]
请用最新版本
