### ISSUE TITLE
tcpcopy 可以复制https 流量嘛

### ISSUE THREAD

**Issue by xinghui-hou** [session-replay-tools/tcpcopy#255]
tcpcopy 复制https 端口 流量访问日志都是400 
/usr/local/tcpcopy/sbin/tcpcopy -x 443-192.168.196.147:443 -s 192.168.196.148 -c 192.168.200.x -r 50 -l /disk/ssd1/logs/tcpcopy_443.log

**Comment by wangbin579** [comment]
如果可以轻松复制，那么https协议就是非常不安全的协议了。

基于tcpcopy，需要二次开发才能复制https协议，不过这个二次开发难度非常大。
