### ISSUE TITLE
只能复制部分数据

### ISSUE THREAD

**Issue by chenji-kael** [session-replay-tools/tcpcopy#257]
Hi，最近在研究这个工具，按示例部署了几台，尝试了各种常见的配置，还是有问题，特来求助
环境：3台机器59，60，61
60:
    /usr/local/tcpcopy/sbin/tcpcopy -x 80-42.81.80.61:80 -s 42.81.80.59 -c 42.81.2.200 -d
61:
   42.81.2.0       42.81.80.59     255.255.255.0   UG    0      0        0 eth0
59:
   /usr/local/intercept/sbin/intercept -i eth0 -F 'tcp and src port 80' -d

给60上传10m的文件，每次61要么存不下文件，要么只有几十K

日志文件有点大，老是上传失败，只好放网盘了：http://pan.baidu.com/s/1eRD2JoY

**Comment by chenji-kael** [comment]
@wangbin579 
拿512字节的小文件测试完全没有问题，换成几十M大小的文件上传后，就不能完整复制了
日志里出现了这样的打印
2016/06/22 15:14:22 +717 [warn] slide win:too many packs:35663,p:17113
不知道是什么原因导致的

**Comment by wangbin579** [comment]
这个问题出在抓包环节：对于比较大的文件上传，会导致在短时间内聚集大量数据包，传统抓包是会丢包的，一旦丢包，这个session就无法完成。

采用pf_ring兼容的pcap方式来抓包（需要研究pf_ring相关内容，且tcpcopy端采用configure --with-pfring --pcap-capture来做相应支持），可以解决此问题。

btw，要想运行的好，必须给予tcpcopy良好的工作环境，pf_ring兼容的pcap抓包方式，可以确保抓包一般情况下不丢包

**Comment by chenji-kael** [comment]
好的 谢谢 ，我想办法装下pf_ring试试
