### ISSUE TITLE
流量回放-n参数大于2时，目标机器接收不到流量数据

### ISSUE THREAD

**Issue by duduyuyu** [session-replay-tools/tcpcopy#258]
离线包回放流量：
设置参数 -n 为2，目标机器接收到流量数据，压力测试正常进行。
设置参数 -n 为5，目标机器接收不到流量数据，施压机器上的log报
 [warn] many connections can't be established

**Comment by wangbin579** [comment]
能够详细贴出tcpcopy的log吗？

**Comment by wangbin579** [comment]
tcpcopy类似喂鱼（假设鱼不知道饥饱，能吃虫），当原生就只有一只小虫，喂5倍（5只小虫），小鸟也能接受；但如果原生是一只大虫，喂2倍，可能还能吃得下，喂5倍，鱼主人就来干涉了，说不能喂了。

对于5倍流量接受不到流量数据，首先看看tcpcopy所在的机器，利用tcpdump查看有没有被复制的数据包发出来，如果发出来，而测试机器没有接受到，就说明受到干涉了。
