### ISSUE TITLE
route add问题

### ISSUE THREAD

**Issue by yangguangxu** [session-replay-tools/tcpcopy#259]
route add的时候遇到这个问题，请问是什么原因呢？谢谢。
sudo route add -host 172.31.15.95 gw 172.31.23.142 dev eth0
SIOCADDRT: Network is unreachable

172.31.15.95是client；
172.31.23.142是assistent server；
172.31.15.95是测试机（当前机器）

路由表（三台机器都相同）：
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         ip-172-31-0-1.u 0.0.0.0         UG    0      0        0 eth0
172.31.0.0      \*               255.255.240.0   U     0      0        0 eth0

三个机器的配置：
eth0      Link encap:Ethernet  HWaddr 02:c0:0f:19:ab:63
          inet addr:172.31.23.142  Bcast:172.31.31.255  Mask:255.255.240.0
          inet6 addr: fe80::c0:fff:fe19:ab63/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:116461450 errors:0 dropped:0 overruns:0 frame:0
          TX packets:205755486 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:46275534497 (46.2 GB)  TX bytes:74256677663 (74.2 GB)

eth0      Link encap:Ethernet  HWaddr 06:22:ce:81:32:7d
          inet addr:172.31.15.95  Bcast:172.31.15.255  Mask:255.255.240.0
          inet6 addr: fe80::422:ceff:fe81:327d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:130976913 errors:0 dropped:0 overruns:0 frame:0
          TX packets:127861768 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:114419923671 (114.4 GB)  TX bytes:249855771776 (249.8 GB)

eth0      Link encap:Ethernet  HWaddr 06:d5:e5:37:fa:75
          inet addr:172.31.15.72  Bcast:172.31.15.255  Mask:255.255.240.0
          inet6 addr: fe80::4d5:e5ff:fe37:fa75/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:46572 errors:0 dropped:0 overruns:0 frame:0
          TX packets:27777 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:277795627 (277.7 MB)  TX bytes:9150438 (9.1 MB)

**Comment by wangbin579** [comment]
首先你确信tcpcopy转发的数据包的客户端ip地址是172.31.15.95？

其次tcpcopy所在的机器ip地址跟测试机器在同一台？
如果是同一台，针对自己机器设置路由，显然不合情理。

**Comment by yangguangxu** [comment]
好的多谢，这个问题已经解决了，应该是因为测试机和intercept不是一个网段，后面换了一个同网段的intercept就好了。不过遇到新的问题“many connections can't be established”，我按照QA里面的指示用tcp dump DEBUG了下。
1.   online机器telnet测试机能成功；
2.  在online的机器上，tcpopy确实是有发包的，但是测试机没有收到；
3.  online、intercept、测试机都是在同一网段；
4. 都是aws上的机器，应该是虚拟机。
请问这种情况有什么好的解决办法？谢谢。。

**Comment by testzlx** [comment]
我也和@yangguangxu遇到一样的问题，请问怎么解决？

**Comment by wangfengfly** [comment]
同问

**Comment by qiangguochina** [comment]
[notice] fd is null after session is created    我的assistent设备报了这个日志错误
