### ISSUE TITLE
tcpcopy自动退出

### ISSUE THREAD

**Issue by Scofields** [session-replay-tools/tcpcopy#261]
请教大神  运行几分钟就停了，报错如下，是内存不足么？

2016/07/15 13:03:10 +899 [notice] total captured pakcets:415478
2016/07/15 13:03:10 +899 [warn] many connections can't be established
2016/07/15 13:03:10 +899 [notice] session size:11503
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:929,p:60165
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:1036,p:33036
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:1129,p:13361
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:728,p:32823
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:907,p:34103
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:946,p:33594
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:443,p:13130
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:831,p:13400
2016/07/15 13:03:10 +899 [warn] unsend:too many packets:992,p:12381
2016/07/15 13:03:10 +899 [warn] unsend:candidate erased:578,p:13558
2016/07/15 13:03:10 +899 [notice] activate_dead_sessions
2016/07/15 13:03:10 +949 [warn] num:17664 larger than threshold
2016/07/15 13:03:10 +949 [error] Recv socket(5)error
2016/07/15 13:03:10 +949 [error] server may be closed or
2016/07/15 13:03:10 +949 [error] backend TCP/IP kernel memeory is too low or
2016/07/15 13:03:10 +949 [error] the version of intercept may not be equal to the version of tcpcopy
2016/07/15 13:03:10 +949 [warn] sig 0 received
2016/07/15 13:03:10 +949 [notice] active:11509,rel reqs:685,obs del:9

**Comment by wangbin579** [comment]
大流量下，容易丢包，而且发包收包都不容易，一句话就是环境恶劣。
建议采用交换机镜像的方式来复制流量。

**Comment by cpejlgc** [comment]
我的也是，我写了一个守护进程，来不断重启，交换机镜像复制流量是怎么弄得呢

**Comment by wangbin579** [comment]
@cpejlgc ，tcpcopy的log，是怎么报的呢？
