### ISSUE TITLE
tcpcopy隔一段时间自动退出

### ISSUE THREAD

**Issue by edgarxue** [session-replay-tools/tcpcopy#262]
运行一段时间自动退出，下面是日志：
2016/08/03 16:27:27 +707 [notice] syn cnt:1984709,all clt:8807447,clt cont:2973692
2016/08/03 16:27:27 +707 [notice] total cont retransmit:22996, frag:121153
2016/08/03 16:27:27 +707 [notice] total captured packets:32773895
2016/08/03 16:27:31 +475 [error] raw fd:7 (Message too long)
2016/08/03 16:27:31 +475 [warn] to bak:10.10.xxx.xxx:12507-->10.10.xxx.xxx:8080,len 1458,seq=3925815567,ack=1233295441
2016/08/03 16:27:31 +475 [error] send to back error,tot_len is:1458
2016/08/03 16:27:31 +475 [warn] sig 64 received
2016/08/03 16:27:31 +475 [notice] active:8280,rel:1786648,obs del:7,tw:3010
2016/08/03 16:27:31 +475 [notice] conns:1795002,resp:7991684,c-resp:2684599
2016/08/03 16:27:31 +475 [notice] resp fin:1734285,resp rst:9
2016/08/03 16:27:31 +475 [notice] send:12239757,send content:2687673
2016/08/03 16:27:31 +475 [notice] send syn:1795280, fin:1164690,reset:626834
2016/08/03 16:27:31 +475 [notice] reconnect:80,for no syn:22430
2016/08/03 16:27:31 +475 [notice] retransmit:20
2016/08/03 16:27:31 +475 [notice] recv packs after retransmission:19
2016/08/03 16:27:31 +475 [notice] syn cnt:1986973,all clt:8817580,clt cont:2977140
2016/08/03 16:27:31 +475 [notice] total cont retransmit:23022, frag:121268
2016/08/03 16:27:31 +475 [notice] total captured packets:32811612
2016/08/03 16:27:31 +475 [info] session table, size:65536, total:8280
2016/08/03 16:27:31 +475 [notice] user time used:331
2016/08/03 16:27:31 +475 [notice] sys  time used:629
2016/08/03 16:27:31 +475 [notice] max memory size:15988
2016/08/03 16:27:31 +475 [notice] voluntary ctx switches:17423446
2016/08/03 16:27:31 +475 [notice] involuntary ctx switches:3022
2016/08/03 16:27:31 +475 [notice] tc_epoll_destroy, close fd:5
2016/08/03 16:27:31 +475 [notice] tc_epoll_destroy, close fd:6
2016/08/03 16:27:31 +475 [notice] tc_epoll_destroy, close fd:8
2016/08/03 16:27:31 +475 [notice] tc_event_loop_finish over
有什么好的办法解决这个问题呢?

**Comment by wangbin579** [comment]
看log是因为发送（sendto函数）给内核的包大小（1458）超过了限制（Message too long)

检查一下MTU相关设置，如果确实超过了，尝试改大一些，看看是否还有这个问题。

**Comment by wangbin579** [comment]
或者利用tcpcopy的-M参数来改小tcpcopy的发送包的大小

**Comment by edgarxue** [comment]
修改包大小已经解决问题了，多谢
