### ISSUE TITLE
请教个问题，tcpcopy 复制访问后对日志分析想获取客户端真实IP。

### ISSUE THREAD

**Issue by minminmsn** [session-replay-tools/tcpcopy#265]
是这样的，tcpcopy 复制访问到测试机，测试机上部署了waf，可以分析攻击日志，但是现在客户端IP都是虚拟的，如果想知道真实的IP有什么好的办法吗？

**Comment by wangbin579** [comment]
不用-c就可以了吧，不过路由需要做相应调整
