### ISSUE TITLE
关于应用层报文内容分析的问题

### ISSUE THREAD

**Issue by illidanzen** [session-replay-tools/tcpcopy#267]
当前在做一个项目，在tcpcopy的基础上，对接收到的报文进行应用层数据的分析，转发所需要的报文，但是这里面又涉及到tcp粘连的问题，tcpcopy有没有提供类似的机制来进行应用层的解包拆包，再根据需要重组发送呢？

**Comment by wangbin579** [comment]
你可以先tcpcopy到一台proxy机器，在proxy机器上面进行应用层的分析
