### ISSUE TITLE
1.0版以后的构建系统问题

### ISSUE THREAD

**Issue by hosiet** [session-replay-tools/tcpcopy#269]
如题。1.0版抛弃了 autotools 转向手写的 configure 脚本，为标准化的构建带来了难度。

希望能够考虑使用标准化的构建工具，如 autotools 和 CMake，也能方便发行版进行打包（例如[方便 Debian 提供新版本](https://tracker.debian.org/pkg/tcpcopy)。

谢谢。

**Comment by wangbin579** [comment]
多谢反馈
