### ISSUE TITLE
tcpcopy部署的时候生产机器 与 （测试机器，intercept机器） 之间可以跨路由吗？

### ISSUE THREAD

**Issue by jiaojiao126621** [session-replay-tools/tcpcopy#271]
当前部署是
1.生产机器的路由信息如下：
  路由为 default         x.x.49.1
2.测试机器的路由信息如下(测试机器和intercept机器在同一网段，默认路由是相同的)：
  路由为 default         x.x.160.1
3.intercept的路由信息如下：
  路由为 default         x.x.160.1
以上环境部署完后，测试机器无法收到从生产机器复制的流量

但是我在默认路由都是x.x.160.1的三台机器上，分别部署生产机器，测试机器，intercept机器后，是可以在测试机器上收到生产机器复制来的流量的。

所以，怀疑是不是TCPCOPY不支持跨路由呢？  

希望大神给出回复，万分感谢！

**Comment by wangbin579** [comment]
这个真不是tcpcopy的问题。tcpcopy只是充当媒婆的作用，能不能成功得看环境等各种因素。抓包分析可以分析出问题出在哪个环节
