### ISSUE TITLE
mysql的tcpcopy离线回放失败

### ISSUE THREAD

**Issue by kafkaGTS** [session-replay-tools/tcpcopy#272]
我用的tcpcopy1.0的离线模式
线上tcpdump了mysql端口3306的pcap文件 tset.pacp
在测试环境的mysql，把认证关了
辅助机和测试机在同一网段
测试机的默认网关也改了

辅助机上面运行：
./intercept -i eth0 -F 'tcp and src port 3306' -d

测试机上面运行：
route add -net 192.168.1.0 netmask 255.255.255.0 gw 172.31.0.21
./tcpcopy -i /usr/local/test.pcap -x 3306-172.31.0.94:3306 -s 172.31.0.21 -c 192.168.1.x

**tcpcopy日志如下：**
2017/01/04 06:08:12 +530 [info] pool:38792416,block:36179280,len:160 occupy
2017/01/04 06:08:14 +293 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:14 +446 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:14 +608 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:14 +760 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:14 +923 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +085 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +236 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +388 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +541 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +683 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +855 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:15 +968 [notice] user time used:0
2017/01/04 06:08:15 +968 [notice] sys  time used:0
2017/01/04 06:08:15 +968 [notice] max memory size:11048
2017/01/04 06:08:15 +968 [notice] voluntary ctx switches:25523
2017/01/04 06:08:15 +968 [notice] involuntary ctx switches:10
2017/01/04 06:08:15 +968 [notice] active:40,rel:1132,obs del:0,tw:28
2017/01/04 06:08:15 +968 [notice] conns:0,resp:0,c-resp:0
2017/01/04 06:08:15 +968 [notice] resp fin:0,resp rst:0
2017/01/04 06:08:15 +968 [notice] send:2332,send content:0
2017/01/04 06:08:15 +968 [notice] send syn:1172, fin:0,reset:1160
2017/01/04 06:08:15 +968 [notice] reconnect:0,for no syn:8
2017/01/04 06:08:15 +968 [notice] retransmit:0
2017/01/04 06:08:15 +968 [notice] recv packs after retransmission:0
2017/01/04 06:08:15 +968 [notice] syn cnt:1164,all clt:285961,clt cont:270682
2017/01/04 06:08:15 +968 [notice] total cont retransmit:0, frag:0
2017/01/04 06:08:15 +968 [notice] total captured packets:570194
2017/01/04 06:08:15 +968 [warn] many connections can't be established
2017/01/04 06:08:16 +008 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:16 +160 [info] pool:39033664,block:37045184,len:160 occupy
2017/01/04 06:08:20 +507 [info] pool:38884880,block:39142976,len:160 occupy
2017/01/04 06:08:21 +156 [info] pool:37171664,block:37156352,len:160 occupy
2017/01/04 06:08:21 +309 [info] pool:37171664,block:37156352,len:160 occupy
2017/01/04 06:08:21 +319 [info] pool:36732560,block:36715456,len:160 occupy
2017/01/04 06:08:21 +492 [info] pool:37171664,block:37156352,len:160 occupy
2017/01/04 06:08:21 +655 [info] pool:37171664,block:37156352,len:160 occupy
2017/01/04 06:08:21 +827 [info] pool:37171664,block:37156352,len:160 occupy

**intercept日志如下：**
2017/01/04 06:23:41 +842 [notice] total resp packs:0, all:0, route:6343, sock write cnt:0
2017/01/04 06:23:41 +842 [notice] cache hit:0,missed:0,lost:0
2017/01/04 06:23:41 +842 [notice] search:0,extra compared:0,all sessions:6343
2017/01/04 06:24:11 +842 [notice] total resp packs:0, all:0, route:6518, sock write cnt:0
2017/01/04 06:24:11 +842 [notice] cache hit:0,missed:0,lost:0
2017/01/04 06:24:11 +842 [notice] search:0,extra compared:0,all sessions:6518
2017/01/04 06:24:41 +842 [notice] total resp packs:0, all:0, route:6753, sock write cnt:0
2017/01/04 06:24:41 +842 [notice] cache hit:0,missed:0,lost:0
2017/01/04 06:24:41 +842 [notice] search:0,extra compared:0,all sessions:6753
2017/01/04 06:25:11 +842 [notice] total resp packs:0, all:0, route:6906, sock write cnt:0
2017/01/04 06:25:11 +842 [notice] cache hit:0,missed:0,lost:0
2017/01/04 06:25:11 +842 [notice] search:0,extra compared:0,all sessions:6906
2017/01/04 06:25:31 +749 [notice] recv length 0,fd:8
2017/01/04 06:25:31 +749 [notice] release tunnel resources, fd:8
2017/01/04 06:25:31 +749 [notice] crazy , combined null, fd:8
2017/01/04 06:25:31 +749 [notice] enter tc_event_destroy:8
2017/01/04 06:25:31 +749 [notice] destroy event:8
2017/01/04 06:25:31 +749 [notice] recv length 0,fd:7
2017/01/04 06:25:31 +749 [notice] release tunnel resources, fd:7
2017/01/04 06:25:31 +749 [notice] crazy , combined null, fd:7
2017/01/04 06:25:31 +749 [notice] enter tc_event_destroy:7
2017/01/04 06:25:31 +749 [notice] destroy event:7
2017/01/04 06:25:41 +843 [notice] total resp packs:0, all:0, route:6976, sock write cnt:0
2017/01/04 06:25:41 +843 [notice] cache hit:0,missed:0,lost:0
2017/01/04 06:25:41 +843 [notice] search:0,extra compared:0,all sessions:6976
2017/01/04 06:26:08 +810 [notice] it adds fd:7
2017/01/04 06:26:08 +843 [notice] cache hit:0,missed:0,lost:0
2017/01/04 06:27:11 +843 [notice] search:0,extra compared:0,all sessions:7395
2017/01/04 06:27:41 +843 [notice] total resp packs:0, all:0, route:7553, sock write cnt:0
2017/01/04 06:27:41 +843 [notice] cache hit:0,missed:0,lost:0

**Comment by wangbin579** [comment]
首先看看测试机器的tcp状态，是不是相应的tcp状态处于syn_recv状态，如果是syn_recv状态：
看看辅助服务器上面能不能抓到syn+ack第二次握手数据包，如果不能抓到，那就是路由设置没有起作用，没有把第二次握手数据包路由给辅助服务器

**Comment by kafkaGTS** [comment]
@wangbin579   确认个问题，离线模式， -c 参数生效的么？
一直没看到其他人用这个跑离线模式

**Comment by kafkaGTS** [comment]
测试机确实是syn_recv状态，辅助机貌似抓不到第二次握手数据包
用了route -net    -host    default  等方法添加路由，不知道为何就是不成功

**Comment by wangbin579** [comment]
你可以让intercept运行在测试服务器上面，看看有没有效果

**Comment by wangbin579** [comment]
-c参数跟离线没有关系。

MySQL回放，最好参考如下来编译：
https://github.com/session-replay-tools/mysql-sgt-replay-module

btw，上面的方式，对于测试MySQL服务器，必须要运行在skip-grant-tables模式下

**Comment by kafkaGTS** [comment]
多谢大神指导
