### ISSUE TITLE
如果涉及web业务的回放，该怎么处理？

### ISSUE THREAD

**Issue by kafkaGTS** [session-replay-tools/tcpcopy#273]
rt，例如web的登录时有验证码，回放时是否要将测试机上的验证码屏蔽掉？
如果业务涉及session那些，是否要程序上做些处理才好回放

**Comment by wangbin579** [comment]
解决方案有如下：
1）在web代理服务器内做映射
2）测试系统的验证信息从线上复制，比如测试系统的redis（存放session验证信息）复制了线上的redis验证信息
