### ISSUE TITLE
tcpcopy 运行一段时间流量逐渐降低

### ISSUE THREAD

**Issue by 359274651** [session-replay-tools/tcpcopy#274]
tcpcopy 运行一段时间流量逐渐降低，但是重新 删掉route del ，再次添加route add 之后，又回再次的流量飙升，就好像有东西被清空了一样

![image](https://cloud.githubusercontent.com/assets/13265578/21801213/b232b3e2-d75b-11e6-929f-3d4dda5db864.png)
类似于这种图

**Comment by wangbin579** [comment]
首先，确定是否是route的问题，在测试机器和辅助服务器内同时抓响应包，看看所有时间内是不是都匹配？
其次，如果抓包信息都匹配（数量上），也有可能是tcpcopy所在的机器抓包的时候大量丢包导致，这时候需要采用更强抓包机制（如pfring）来避免丢包问题
最后，如果上面都不成立，需要在测试服务器抓包，看看到底是什么导致了问题所在

**Comment by 359274651** [comment]
换了台机器解决了，怀疑是intercept 和lvs在一台机器的原因造成的 ，换成了没有lvs的机器就很稳定，谢谢大神的关注
