### ISSUE TITLE
在linode的机子上，tcpcopy无法复制流量

### ISSUE THREAD

**Issue by liangyu422** [session-replay-tools/tcpcopy#275]
在本地虚拟机按教程设置是可以正常复制流量的。在linode的机子上，tcpcopy无法复制流量。
补充一下，好像在centos 7下不正常，centos6可以复制流量

**Comment by wangbin579** [comment]
这跟os没有必然关系，跟具体所处的网络环境有关系

**Comment by wangbin579** [comment]
建议抓包分析，不要只看表面

**Comment by liangyu422** [comment]
谢谢作者。已经解决了。
