### ISSUE TITLE
Long connection is unusable

### ISSUE THREAD

**Issue by y123456yz** [session-replay-tools/tcpcopy#276]
I grabbed the bag, the rsp package of the test dest machine has a lot of RST.

**Comment by y123456yz** [comment]
Short connection is OK.

**Comment by wangbin579** [comment]
首先得看应用类型是否具备回放条件，我们可以这样判断：
假设session连接建立开始就被tcpcopy捕获，如果这个session的第一个请求被测试服务器拒绝，一般代表session无法被回放，可能是验证方面的问题；如果没有被拒绝，那是可以被回放的。

如果可以回放，那么具体还得看测试服务器的超时机制和tcpcopy的超时机制是否匹配，具体还得抓包分析，不是一概而论的。

**Comment by wangbin579** [comment]
如果压力比较大，tcpocpy抓包过程中会频繁丢包，长连接过程就会被中断，重建连接的过程中，可能缺乏认证过程，导致连接被拒绝，因此如果是这种情况的话，建议如下：
1、采用pfring的抓包机制，尽量少丢包，这样复制效果才能比较理想
2、二次开发，比如MySQL回放模块（https://github.com/session-replay-tools/mysql-replay-module），重建会话认证过程，这样丢包比较严重的情况下，也会工作比较理想

**Comment by y123456yz** [comment]
@wangbin579 

可能是如下原因，我没有带--single参数
./configure --single --comet

明天去公司试试

**Comment by wangbin579** [comment]
那是为了 百万连接消息推送使用的配置。
最好抓包分析以后再去针对性解决问题

**Comment by y123456yz** [comment]
@wangbin579 

哪里有代码设计文档，能否分享下。

今天实验了下，redis没认证过程，长连接没问题。但是mysql加了mysql-replay-module模块后，短连接没问题，长连接还是大量RST，几乎不能用。

谢谢哈。

**Comment by wangbin579** [comment]
mysql，如果配置合理的话，不应该短链接没有问题，长连接有问题，应该是其它方面的原因导致的。

抓包分析为啥rst呢，是谁发送的rst？

我这边一直在用mysql回放，也没有出现过类似问题
