### ISSUE TITLE
抓包正式机请求到了测试机但实际应用却没有请求日志

### ISSUE THREAD

**Issue by jasonzzz** [session-replay-tools/tcpcopy#278]
阿里云 VPC，ubuntu 14.04
看起来遇到跟 #246 一样的问题，然后尝试：

- 正式机A 192.168.1.152
- assistant server/测试机 B 192.168.1.153

A/B 都开了 nginx 8000 端口

### B

```
$ git clone git://github.com/session-replay-tools/intercept.git /tmp/intercept
$ cd /tmp/intercept && ./configure && make && sudo make install

$ /usr/local/intercept/sbin/intercept -v
intercept version:1.0.0

$ sudo sysctl -p | grep ip_forward
net.ipv4.ip_forward = 0

$ sudo /usr/local/intercept/sbin/intercept -i eth0 -F tcp and src port 8000

$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.253   0.0.0.0         UG    0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0

$ sudo route add -host 192.168.1.152 gw 192.168.1.153

$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.253   0.0.0.0         UG    0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.1.152   192.168.1.153   255.255.255.255 UGH   0      0        0 eth0
```

### A

```
$ git clone git://github.com/session-replay-tools/tcpcopy.git /tmp/tcpcopy
$ cd /tmp/tcpcopy && ./configure && make && sudo make install

$ /usr/local/tcpcopy/sbin/tcpcopy -v
tcpcopy version:1.0.0

$ sudo /usr/local/tcpcopy/sbin/tcpcopy -x 8000-192.168.1.153:8000 -s 192.168.1.153

$ curl 192.168.1.152:8000
```
这时候看 nginx 日志，只有 A 有请求，看起来请求还是没有到 B。。

内网安全策略全部允许
系统 iptables 五表五链全部 ACCEPT

尝试 `sudo tcpdump -i eth0 tcp -w packets.cap`
筛选条件 (ip.src == 192.168.1.152 or ip.src == 192.168.1.153) and (ip.dst == 192.168.1.152 or ip.dst == 192.168.1.153)

A：
![screenshot_2017-02-22_11-48-09](https://cloud.githubusercontent.com/assets/3256083/23196481/e751c544-f8f4-11e6-87d0-f9963e41f814.png)

131 A->B ack 失败了。。
不过看 seq 135 又成功了，请求到了 B，但是 nginx 日志却没有，A->B curl 正常，nginx 配置没有做 ip 限制

B：
![screenshot_2017-02-22_11-48-42](https://cloud.githubusercontent.com/assets/3256083/23196497/fafa467a-f8f4-11e6-97c4-e607983a534f.png)

看起来 http 请求是从 A 复制到了 B，但是为什么 nginx 日志没有？是没有正常返回导致的？也没有类似超时的信息
以及 131 A->B 那个 RST 是否正常？

谢谢

**Comment by wangbin579** [comment]
问题比较多：
1、路由 sudo route add -host 192.168.1.152 gw 192.168.1.153，对于测试服务器的响应，回到测试服务器自身？

2、路由设置没有生效，响应包应该都回到了152机器，从而干扰了tcpcopy测试的进行，这个可以从131的rset数据包可以看出
     一定不要让响应回到真正的客户端，要坚决提前干掉响应包

3、intercept运行，sudo /usr/local/intercept/sbin/intercept -i eth0 -F ‘tcp and src port 8000’，对于-F参数，需要加上引号，否则只认tcp这个过滤条件


对于问题2的解决方案：
方案1、在152机器，上面过滤掉153回来的响应包，比如利用iptables，不要让第二次握手数据包到达152机器的tcp层，否则152的tcp就会发送rst数据包。需要注意的是，这个只对客户端访问测试服务器153的ip地址为152的情况下才能生效

方案2、intercept采用configure --traditional ，在153采用传统的iptables来过滤响应包，tcpcopy运行方式不变，intercept可以参考0.9系列的方法


方案3、条件允许的话，路由设置的时候，尽量走第三台机器，要确保路由生效（路由的目的就是实现流量黑洞，把响应包干掉），满足下列任意一个条件即可：
     a）在第三台机器上面能够抓到路由过来的响应包，说明路由生效
     b）在第三台机器没有抓到，在客户端，也没有响应包回来，说明云环境下，天生就有流量黑洞机制，这个时候intercept运行在测试服务器即可

**Comment by jasonzzz** [comment]
谢谢详细的回复

> 对于测试服务器的响应，回到测试服务器自身？

因为看 [#246](https://github.com/session-replay-tools/tcpcopy/issues/246#issuecomment-197260135) 的结论就直接把 intercept 放在了测试服务器上面，也就是方案3的 b

仍然是主楼的 A/B 两台不变的情况：
基于 iptables 的方案1/2都能正常运行

不过方案3：

### B

> 这个时候intercept运行在测试服务器即可
```
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.253   0.0.0.0         UG    0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

curl 请求 A 外网地址就能正常复制到 B，虽然也有少量去请求 B 外网地址。。
![os_external](https://cloud.githubusercontent.com/assets/3256083/23203773/f1043c3c-f91e-11e6-8d0b-787a3f2551f3.png)

为什么内网地址反而不能正常运行？

**Comment by wangbin579** [comment]
方案3还有什么问题吗

**Comment by jasonzzz** [comment]
使用方案 3 的情况，不太明白为什么在 A 上请求 A 内网地址就没有正常复制到 B，抓包信息就是主楼的描述
在 A 上请求 A 外网地址倒是能正常复制到 B。。

**Comment by wangbin579** [comment]
假设利用内网地址X访问A，复制到B后，第二次握手数据包会回到内网机器X上面去，然后内网机器X一看第二次握手数据包过来，觉得莫名其妙，会立即回送rst数据包给机器B，导致回放连接被干掉

**Comment by jasonzzz** [comment]
不过实际 B 上面跑了 intercept，如主楼描述参数也写了内网地址 `sudo /usr/local/tcpcopy/sbin/tcpcopy -x 8000-192.168.1.153:8000 -s 192.168.1.153`，正常的话返回的数据包应该被 intercept 处理掉了

**Comment by wangbin579** [comment]
intercept 1.0版本，只负责抓响应包，并不负责干掉响应包

**Comment by jasonzzz** [comment]
哦哦谢谢，应该是我理解错了，我以为 intercept 也能跟 iptables 一样丢弃掉响应包

**Comment by wangbin579** [comment]
tcpcopy会根据抓包接口提供的数据包，进行数据包的处理。具体抓包需要依赖于接口，接口好，则抓包抓的好。

**Comment by jasonzzz** [comment]
好的，谢谢
