### ISSUE TITLE
aws ec2海外服务器，tcpcopy复制流量失败，求解！！！

### ISSUE THREAD

**Issue by liulei8072** [session-replay-tools/tcpcopy#280]
一：实验机器（三台机器都是同一网段，aws ec2海外亚马逊）

54.254.175.130  ---- 172.31.11.188 （intercept）
                   
54.169.203.122  ---- 172.31.19.19 （online）

54.255.170.150  ---- 172.31.33.21 （test）

二：步骤
1.先在辅助机器（54.254.175.130）上启动拦截服务intercept，在测试服务器（54.255.170.150）上启动Tomcat服务并设置路由，线上服务器（54.169.203.122）上启动tcpcopy和Tomcat服务。
  结果： 测试服务器上没有来自线上服务器的流量。
  诊断： 猜测是亚马逊云做了某些网络限制，禁止非来自本服务器的数据包发出去。

配置过程：
辅助机器（intercept）：54.254.175.130  (端口：36524)
/usr/local/intercept/sbin/intercept  -i eth0 -F tcp and src port 8066 -d

测试服务器（添加路由）：54.255.170.150
route add -net 99.99.99.2 netmask 255.255.255.0 gw 172.31.11.188

线上服务器（tcpcopy）：54.169.203.122
/usr/local/tcpcopy/sbin/tcpcopy -x 8066-54.255.170.150:8066 -s 54.254.175.130 -c 99.99.99.2 -d -n 1

2.修改tcpcopy启动服务的-c 参数为线上服务器自己54.169.203.122
  结果：通过tcpdump能看到发到测试服务器的流量数据包，但只有收到请求状态，没有处理状态，TCP三次握手没有走完。

[ec2-user@ip-172-31-33-21 ~]$ netstat -apn|grep 8066
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 :::8066                     :::*                        LISTEN      12833/java          
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:14358    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:58684    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:36870    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:14352    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:14328    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:14330    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:14310    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:36874    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:14346    SYN_RECV    -                   
tcp        0      0 ::ffff:172.31.33.21:8066    ::ffff:172.31.19.19:36846    SYN_RECV    -   

三：求助
请大家分析下tcpcopy拷贝流量失败的原因，是aws ec2自身限制造成的，还是tcpcopy部署问题？请给出解决方案，谢谢！

**Comment by wangbin579** [comment]
尝试让intercept运行在测试服务器，看看三次握手能不能完成

**Comment by liulei8072** [comment]
@wangbin579 

一. 放弃方案
首先，三台机器的模式，在aws ec2上无法应用，由于aws自身限制，ip不能更改，这种方案已放弃。

二. 应用方案
试用2台机器，1台（online+tcpcopy），1台（test+intercept），目前采用该方案。
启动tcpcopy：/usr/local/tcpcopy/sbin/tcpcopy -x 8066-54.255.170.150:8066 -s 54.255.170.150 -c 54.169.203.122  -d -n 1
说明：-s 54.255.170.150，是因为合并为同一台test服务器。
           -c 54.169.203.122，是因为aws不允许修改别的ip地址。

三. 实际遇到的问题
test服务器无法复制线上流量，用tcpdump抓包，wireshark解包分析，有5个过程：
1.  online (SYN) -----> test
2.  test (SYN+ACK) -----> online
3.  online (RST) ------> test
4.  online (POST) ------> test
5.  test (RST) ------> online

四. 分析问题
以上5个过程说明，tcp的三次握手失败了，问题出在3，之所以online回复RST，是因为test服务器发包给online，online不知道这个包是什么，所以直接回复RST。

五. 解决问题
在online上把test发来的包丢弃掉，online设置防火墙对端口进行丢包，只要online不收到这个包，就不会回复RST，三次握手也能建立。
命令：iptables -A INPUT -s 172.31.33.21 -p tcp --sport 8066 -j DROP

六. 结果
online设置了防火墙丢包，已成功建立三次握手，online流量可以复制到test服务器。

**Comment by wangbin579** [comment]
上述方案确实在某些场景下可行，但只能适用于线上客户端ip地址比较少的场合。

当然还有其它方案，不过比较复杂，比如测试机器设置两个网卡设备，两个ip地址

**Comment by liulei8072** [comment]
王工，您好：
                    以上成功是建立在2台机器的环境（tcpcopy，test+intercept）搞定的，如果还是在aws上用3台机器（tcpcopy，test，intercept），是否可行？
                    如果可行，需要做哪些配置，才能绕过aws不允许tcpcopy命令-c参数改虚假ip的问题？
                    求解答，谢谢！

**Comment by wangbin579** [comment]
估计也只有vpn才能解决这个问题了

**Comment by linshundong** [comment]
@wangbin579 
我现在也是2台机器的环境（tcpcopy，test+intercept），test有多张网卡，新架构改怎么部署呢

**Comment by elbertwang** [comment]
@liulei8072 EC2 源/目标地址检查关了么

**Comment by wubo0067** [comment]
为什么在online上设置对test的丢包才能让三次握手成功？

**Comment by maomaoguo2017** [comment]
> @liulei8072 EC2 源/目标地址检查关了么

这个方法可以解决问题，关闭对应网络接口的检查，主要是online和intercept 服务器。

**Comment by t1faith** [comment]
> @liulei8072 EC2 源/目标地址检查关了么

赞
