### ISSUE TITLE
关于同时复制多个端口流量的问题

### ISSUE THREAD

**Issue by bichenchen** [session-replay-tools/tcpcopy#281]
前辈，我的业务场景是一台服务器部署多个mysql实例，tcpcopy有同时将多个端口的流量复制到target端的写法吗？如果没有是不是只能同时启动多个tcpcopy线程分别指定不通的端口来进行复制啊，比如：
tcpcopy -x 3306-online:3306 -s assistant -c target -n 3 -d
tcpcopy -x 3307-online:3307 -s assistant -c target -n 3 -d

**Comment by wangbin579** [comment]
按照你的应用场景，可以这样写：
tcpcopy -x 3306-online:3306,3307-online:3307 -s assistant -c target -n 3 -d
