### ISSUE TITLE
抓包日志里无法建立连接

### ISSUE THREAD

**Issue by lgy-dc** [session-replay-tools/tcpcopy#282]
作者您好，我配置后抓包一直有问题，可以帮忙看下吗，非常感谢。

online服务器 （192.168.1.5） /usr/local/tcpcopy/sbin/tcpcopy -x 8080-192.168.1.3:8080 -s 192.168.1.2 -c 192.168.100.x
辅助服务器   （192.168.1.2）  /usr/local/intercept/sbin/intercept -i em2 -F 'tcp and src port 8080'
测试服务器   （192.168.1.3）  route add -net 192.168.100.0 netmask 255.255.255.0 gw 192.168.1.2

抓包截图

![qq 20170425181143](https://cloud.githubusercontent.com/assets/28001007/25380373/a69df80a-29e2-11e7-858d-f42c66e1684f.png)

后来参考了[https://github.com/session-replay-tools/tcpcopy/issues/280](url) 配置后，测试服务器有相关日志了，但是online服务器 也收到了回包，
iptables -I INPUT -s 192.168.1.3 -p tcp --sport 8080 -j DROP 配置防火墙也不行

**Comment by lgy-dc** [comment]
online服务器 8080是tomcat，前面是nginx，客户端地址都是nginx地址（ 192.168.1.5 ）

**Comment by wangbin579** [comment]
相隔3s左右发的rst数据包，是tcpcopy超时发的。

按道理配置防火墙会有效，除非上面信息描述有矛盾之处或者防火墙设置无效


信息要全，尽量避免自己判断，否则容易进入死结

**Comment by wangbin579** [comment]
假设tcpcopy测试过程中，测试服务器上面的上层应用没有收到任何请求

判断第一次握手数据包,即syn数据包,能否到达测试服务器

1、如果syn数据包能够到达测试服务器,分为如下几种情况:

1.1) 抓包仅仅只有syn数据包
在测试服务器利用tcpdump 抓包，能看到被复制的syn数据包都过来了，说明已经到达了测试服务器的数据链路层。
如果利用netstat 查看是否有应用的连接，如果没有，说明数据包在IP 层给drop 掉
了，请查看是否有rpfilter 设置，如果有，去掉此设置，一般即可解决此问题。
如果没有设置rpfilter，那么确认一下iptables 设置有没有冲突，如果有，请先整理
好iptables 相关规则。

1.2) syn数据包后面紧跟reset数据包(注意：同一个session中,syn和reset数据包相隔不到1s)
说明路由设置有问题或者有冲突,导致了响应包直接返回给真实的客户端了.

1.3）测试服务器有响应包（第二次握手数据包）
去辅助服务器进行抓包，看看第二次握手数据包有没有到达辅助服务器：a）如果没有到达，也说明路由设置没有生效，因此intercept捕获不到第二次握手数据包，回放就无法继续下去，通常可以采用的方案是让intercept直接运行在测试服务器上面（注意：路由设置不变，且tcpcopy的-c参数不能设置成tcpcopy连接intercept所用的ip地址，否则tcpcopy连接不上intercept） b）如果捕获到了第二次握手数据包，查看是否有ip forward设置，如果设置了，需要关掉此设置，否则这些响应包会直接返回客户端，干扰测试的进行

2、如果不能到达测试服务器,又分为两个部分:

2.1) 在在线服务器利用tcpdump抓包,能抓到tcpcopy转发的数据包
如果能够抓到，说明路途过程中被干掉了，可以尝试利用tcpcopy的-c参数，修改客户端ip地址成合法的ip地址，最极端一点的就是修改成tcpcopy所在机器的ip地址（注意：存在nat的问题，而且如果intercept运行在测试服务器，需要注意tcpcopy的-c参数不能设置成tcpcopy连接intercept所用的ip地址，否则tcpcopy连接不上intercept）

2.2) 在在线服务器利用tcpdump抓包,不能抓到tcpcopy转发的数据包
说明在在线机器的ip层被过滤掉了,检测iptables对output chain的限制等内容
如果是iptables的问题,而在线又不允许修改,采用--pcap-send从数据链路层的方式来发包（有一定难度，可以参考http://jishu.y5y.com.cn/wangbin579/article/details/10148247）.

**Comment by lgy-dc** [comment]
您好，我参考了您这个方案
1.3）测试服务器有响应包（第二次握手数据包）
去辅助服务器进行抓包，看看第二次握手数据包有没有到达辅助服务器：a）如果没有到达，也说明路由设置没有生效，因此intercept捕获不到第二次握手数据包，回放就无法继续下去，通常可以采用的方案是让intercept直接运行在测试服务器上面（注意：路由设置不变，且tcpcopy的-c参数不能设置成tcpcopy连接intercept所用的ip地址，否则tcpcopy连接不上intercept） b）如果捕获到了第二次握手数据包，查看是否有ip forward设置，如果设置了，需要关掉此设置，否则这些响应包会直接返回客户端，干扰测试的进行


online服务器 （192.168.1.5） /usr/local/tcpcopy/sbin/tcpcopy -x 8080-192.168.1.2:8080 -s 192.168.1.2 -c 192.168.1.5
    配置 iptables -I INPUT -s 192.168.1.2 -p tcp --sport 8080 -j DROP
测试服务器 （192.168.1.2） /usr/local/intercept/sbin/intercept -i em2 -F 'tcp and src port 8080'

这样配置后online服务器有请求  ，测试服器日志也有对应的请求了，但是有回包，net.ipv4.ip_forward = 0 都是关闭的 ，tcpcopy -c 参数是不是不对，应该怎么修改呢

**Comment by lgy-dc** [comment]
并且，如果不配置 iptables -I INPUT -s 192.168.1.2 -p tcp --sport 8080 -j DROP，测试服务器没有任何请求过来，特别奇怪，配置了却有回包

**Comment by lgy-dc** [comment]
![http](https://cloud.githubusercontent.com/assets/28001007/25417477/fd968368-2a76-11e7-8c18-5bcdf9e0cf15.png)

**Comment by wangbin579** [comment]
你说指的回包是上面红色框中的数据包吗？

如果是，也正常：
tcpdump一般抓包是在数据链路层抓的，iptables是在ip层drop掉响应包，而响应包先到数据链路层，再往上到达ip层，所以响应包会经过数据链路层，tcpdump能够抓到也正常，抓不到才不正常

**Comment by lgy-dc** [comment]
哦，原来是这样，但是现在开启tcpcopy后，online服务器的结果受到了测试服务器的影响，比如有个动态验证码，一直输入不正确，关闭tcpdopy后就正常了，所以我感觉可能是回包导致的

**Comment by lgy-dc** [comment]
这个需要怎么抓包判断呢，谢谢

**Comment by wangbin579** [comment]
tcpcopy不会直接影响上层应用，最多影响ip层面的系统配置，从而干涉上层。

得看系统日志是怎么报的

**Comment by lgy-dc** [comment]
谢谢，已经找到问题了，是因为tomcat配置了session共享导致的，现在都已经正常了，之前就一直纠结tcpdump抓到的数据，感谢。

**Comment by lgy-dc** [comment]
不好意思，又碰到问题了，关闭tomcat的session共享后，验证码的问题没有了，应该是online服务器和test服务器同时操作session导致的（session存在redis里），但是有些需要登陆才能访问的页面的请求 copy到test服务器就不能使用了，应该是test服务器没有session导致的，这个目前有好的解决办法吗

**Comment by wangbin579** [comment]
我们一般是利用线上系统的数据库或者缓存系统的备库（只读）来解决的

**Comment by lgy-dc** [comment]
好的，谢谢，可以了。
