### ISSUE TITLE
session的问题

### ISSUE THREAD

**Issue by lgy-dc** [session-replay-tools/tcpcopy#283]
您好，有个session的问题请教下，谢谢
    目前 测试服务器无法copy 线上服务器的登陆状态
    浏览器端只有一个session值（A6359827694EE29B22744C25330849F7），
    但是测试服务器抓包有两个session值，这是为什么呢，
![session](https://cloud.githubusercontent.com/assets/28001007/25477773/419c3cc4-2b71-11e7-88dc-c77d1582264d.png)

**Comment by wangbin579** [comment]
tcpcopy本身不会修改上层应用层数据内容，只会利用线上的数据来访问测试系统。
具体为啥有两个session值，可以查看tcp会话过程

**Comment by lgy-dc** [comment]
目前这个问题解决了
问下您碰到ajax调用post请求时，需要session验证的话这个怎么处理呢，其他请求都正常了，ajax请求就会报用户未登录的错误，谢谢

**Comment by wangbin579** [comment]
我们对于post请求，也是一样的处理方式

**Comment by lgy-dc** [comment]
好吧，谢谢。
