### ISSUE TITLE
tc_free接口内释放large内存后，内存结点从链表中移除了，但该结点本身并没有释放.

### ISSUE THREAD

**Issue by yulsfish** [session-replay-tools/tcpcopy#284]
tc_free接口内释放large内存后，内存结点从链表中移除了，但该结点本身并没有释放.

具体见tc_malloc.c tc_free接口，第347行：

tc_free(l->alloc);
l->alloc = NULL;
if (prev) {
    prev->next = l->next;
} else {
    pool->sh_pt.large = l->next;
}

结合 tc_palloc_large接口，第304行来看：

for (large = pool->sh_pt.large; large; large = large->next) {
    if (large->alloc == NULL) {
        large->alloc = p;
        return p;
    }

    if (n++ > 3) {
        break;
    }
}

在tc_free接口释放large内存后应该不需要释放结点本身，

以便在tc_palloc_large 中复用，

所以tc_free接口内释放large内存后不需要删除内存结点;

**Comment by wangbin579** [comment]
慧眼，感谢你的反馈
