### ISSUE TITLE
tcpcopy流量丢失问题

### ISSUE THREAD

**Issue by wenmoxiao** [session-replay-tools/tcpcopy#286]
三台机器: 使用的1.0.0版本
online: 1.31.x.43                   ./tcpcopy -x 80-111.202.x.73:80 -s 111.202.x.74 -c 1.31.x.43
test: 111.202.x.73                 route add -net 1.31.x.0 netmask 255.255.255.0 gw 111.202.x.74
intercept: 111.202.x.74         intercept -F 'tcp and src port 80' -d

问题1：
   按照上面的流程执行后正常收到数据包并能处理, 但是数据量没达到online的数据量
问题2：
   当在tcpcopy后面用上-n 之后除1之外,所有online->test的请求都是 flags[R.]的状态
问题3 :
   tcpcopy后面的-c 带上的都必须是online的本ip地址，不适用ip或者用其他的ip值都会和问题2一样
问题4:
  online的负载高了，也会出现问题2的情况

**Comment by wangbin579** [comment]
tcpcopy目前只会改变ip地址，不会修改原先的端口号，所以如果线上的客户端ip地址有很多，映射到一个ip地址，就会导致session冲突，压力稍微一大，效果就差，根本解决策略就是-c采用多个ip地址。

由于你的环境比较特殊，不允许除了本机ip地址以外的访问，那么解决策略有如下候选：
1、离线回放，避开数据包跨机器的访问
2、vpn，避开路途过程中的安全过滤
3、除去安全干扰
4、由于是http协议，可以采用应用层回放工具，避开底层问题
