### ISSUE TITLE
关于rst包的解决方法和一些不成熟的问题

### ISSUE THREAD

**Issue by dingding7199** [session-replay-tools/tcpcopy#287]
背景是乐视大数据部接收机tcp协议接收机压力测试，服务端口为9999。采用falcon监控相关性能信息。
解决方式是tcpcopy服务器开启4倍流量时出现大量rst包现象，后来改为两个tcpcopy进程启动1倍流量后,恢复正常。看cpu参数我理解是单tcpcopy进程占用一个cpu核心100%，24核cpu没有完全使用。采用开启两个进程曲线救国。
10.116.95.87 target server
![image](https://user-images.githubusercontent.com/13215312/26964947-4d83c60c-4d26-11e7-8f6e-f115c0a62b83.png)

10.116.95.81 intercept
/usr/local/intercept/sbin/intercept -i eth1 -F 'tcp and src port 9999'  -l /data/intercept.log -d
![image](https://user-images.githubusercontent.com/13215312/26964915-29751ab8-4d26-11e7-8e4e-a43b5ac4dc35.png)
![image](https://user-images.githubusercontent.com/13215312/26964934-42ff3c48-4d26-11e7-8c9e-a123be372a75.png)

10.116.95.82线上
/usr/local/tcpcopy/sbin/tcpcopy -x 80-10.116.95.87:9999 -s 10.116.95.81  -m 20480 -c 192.168.2.x -n 1  -l  /data/tcpcopy.log -d
![image](https://user-images.githubusercontent.com/13215312/26964894-118ef0cc-4d26-11e7-8007-abe76024f7c1.png)
![image](https://user-images.githubusercontent.com/13215312/26964923-395146f0-4d26-11e7-9705-be87bb3f9c6b.png)

**Comment by dingding7199** [comment]
后来采用4个0.5倍测试一段时间后出现rst包
![image](https://user-images.githubusercontent.com/13215312/26964998-84570d38-4d26-11e7-8e2d-51aa2ee186e3.png)
其中有些falcon监控项截图
![image](https://user-images.githubusercontent.com/13215312/26965037-aedec3ac-4d26-11e7-9d81-18ae2b697478.png)
![image](https://user-images.githubusercontent.com/13215312/26965055-c57f0f54-4d26-11e7-9fb9-1ff8a67f8b39.png)
![image](https://user-images.githubusercontent.com/13215312/26965073-cc1cf934-4d26-11e7-9718-a9cdaaeed880.png)
![image](https://user-images.githubusercontent.com/13215312/26965080-d244d0d4-4d26-11e7-95b6-0bbcb1b97610.png)
![image](https://user-images.githubusercontent.com/13215312/26965096-e25b4714-4d26-11e7-822e-d2956bd6179e.png)
![image](https://user-images.githubusercontent.com/13215312/26965103-ea9bc0c0-4d26-11e7-879e-56843a5987f6.png)

**Comment by wangbin579** [comment]
1、如果是外网应用（ip地址比较多的场合）采用多个tcpcopy，是比较好的方案，但容易出现抓包瓶颈（可以考虑采用pfring抓包的方案）；如果采用一个tcpcopy实例，n倍复制，容易导致session冲突，效果就大打折扣。

btw，n倍复制适应于ip地址不多的场合，且压力不大的场合。


2、出现rst，得抓包分析才能知道，可能是抓包出现瓶颈，也有可能是应用响应不及时，具体问题还需要具体分析

**Comment by dingding7199** [comment]
看网络我支持测试0.5倍流量时，其实开启了4倍流量，现在两边流量正常。性能指标也正常，后续我会分析下之前出现瓶颈时的系统性能瓶颈在哪，感谢！
![image](https://user-images.githubusercontent.com/13215312/26965779-dc4298fc-4d29-11e7-91a0-0efc2eaf9804.png)

另外interrupt日志经常报出fd异常，不知道是为啥
![image](https://user-images.githubusercontent.com/13215312/26965793-f4ac3e7a-4d29-11e7-87e2-20b857bc3fa7.png)
![image](https://user-images.githubusercontent.com/13215312/26965858-52c962ee-4d2a-11e7-95c8-66b0ba0e4ab8.png)
![image](https://user-images.githubusercontent.com/13215312/26965948-ab82f5ee-4d2a-11e7-8cfd-2f84d3665c70.png)

**Comment by qingping209** [comment]
后来这个是什么原因呢
