### ISSUE TITLE
腾讯云服务器 无法自定义route这应该怎么用呢?

### ISSUE THREAD

**Issue by chengdashun** [session-replay-tools/tcpcopy#290]
求高手解答~

**Comment by wangbin579** [comment]
有如下方案供选择：
1、采用老方法
      intercept端采用--traditional，利用iptables来截获响应包，方法可以参考1.0之前的版本

2、如果云环境有黑洞机制，可以设置容易被黑洞干掉的ip地址，这样就无需你自己去设置route
     这种需要你自己去尝试，可以通过抓包分析来判断

3、部分场景下（压力小，且客户端ip地址少），可以设置客户端ip地址为tcpcopy所在的ip地址，然后在tcpcopy所在的机器设置iptables来过滤掉响应包

4、离线回放
