### ISSUE TITLE
Tcpcopy use for testing IDS

### ISSUE THREAD

**Issue by ghost** [session-replay-tools/tcpcopy#291]
Hello, thank you this great tool. I have been looking for something like this for a while now. 

I am planning to evaluate an IDS tool for production use on our AWS deployment. I am thinking of using tcpcopy to capture traffic from my loadbalancer VM and send the copies to another VM which is running the IDS. Is this a valid use case?

I am thinking of using traditional architecture for this.

E.g.

vm1 - production online vm - runs tcpcopy on selected interface
vm2 - runs tcpcopy interceptor + IDS

As per my understanding, the flow here would be as follows:

tcpcopy (production vm) --> IDS on vm2 -> tcpcopy (intereptor on vm2) -> response to vm1

Can someone help me understand this?

**Comment by sunny137** [comment]
Is this a valid use case? Please help me understand this.

**Comment by wangbin579** [comment]
If high-level applications which use the same protocol as vm1  on vm2 does not exist, tcpcopy could not be used.
