### ISSUE TITLE
Question : How is tcpcopy different from following tool

### ISSUE THREAD

**Issue by ghost** [session-replay-tools/tcpcopy#292]
Potentially dumb question.

How is tcpcopy different from following tools:

1. Remote packet capture

https://github.com/frgtn/rpcapd-linux

Isnt tcpcopy doing same thing technically? Please educate me on diffrerences between these tools. My use is to copy traffic faithfully and send it over to an IDS for evaluation purpose.

**Comment by wangbin579** [comment]
https://github.com/session-replay-tools/tcpcopy/wiki/TCPCopy-vs-Tcpreplay

**Comment by sunny137** [comment]
Pardon my ignorance here but here are my questions in detail:

1. Is the traditional model of tcpcopy safe to use in production? Here I will be running interceptor and assistant server on same node. Is this less safer than modern architecture?

2. Is there any way to throttle the output of tcpcopy by enabling sampling etc?

**Comment by wangbin579** [comment]
1. Is the traditional model of tcpcopy safe to use in production? 
    safe
   Here I will be running interceptor and assistant server on same node. Is this less safer than modern architecture?
  There's not much difference between them in safety

2. Is there any way to throttle the output of tcpcopy by enabling sampling etc? 
   use -r parameter
