### ISSUE TITLE
2台机器可否在不同网段进行tcpcopy工作？

### ISSUE THREAD

**Issue by liulei8072** [session-replay-tools/tcpcopy#294]
王工，您好：
                      之前在海外aws上用2台同样网段的机器，tcpcopy成功引流。

                      我想问的是：
                      tcpcopy机器在海外aws上，test+intercept机器在公司内网，tcpcopy能成功引流吗？
                      如果可以，需要具体做那些配置？
                      求解答，谢谢！！！

**Comment by wangbin579** [comment]
vpn
