### ISSUE TITLE
tcpcopy online server 无法复制请求给测试服务器，大量链接被reset

### ISSUE THREAD

**Issue by legend1121** [session-replay-tools/tcpcopy#296]
@wangbin579  您好！ 最近在做一个线上引流项目，发现tcpcopy 始终无法向线下测试服务器发送请求包（Flags为[P.]的包）， 经过查看tcpdump包，发现online server 发完SYNC包后，没有发送【ACK】包， 直接发送了【RST】包,  线下测试server 收到了tcpcopy 发来的SYNC包，将应答包[SYNC+ACK]包转发给了辅助服务器，辅助服务器未给online sever 发回响应包

 该问题查询近2周，一直未定位原因，由于项目比较急！  能否麻烦wangbin大拿帮分析一哈可能的原因? 万分感激！
1. 现象如下：
（1） tcpcopy 和 intercept 均未0.9.10版
（2）  docker容器环境
（3） 线上tcpcopy 部署在docker容器里，（虚拟ip为10.0.3.18， 宿主机ip为10.195.197.11（主机名:nj03-jpaas-nj00-dea59.nj03.baidu.com） 启动命令：./tcpcopy -d -x 1031-10.94.50.21:9990 -s 10.94.50.23 -p 36544 -c 10.0.3.18 -r 50 -t 120,  其中-c 10.0.3.18 为docker容器虚拟ip地址, 在宿主机上iptable作为映射， 实际发出去的包地址为: 10.94.50.23 (辅助服务器地址)
（4） 线下测试服务器地址： 10.94.50.21:9990 （主机名: cp01-testing-taas03.cp01.baidu.com）
（5） 辅助服务器地址：10.94.50.23:36544（主机名:cp01-testing-taas05.cp01.baidu.com） ,  启动: ./bin/intercept2 -d -p 36544 -o 10.94.50.21:9990 -l log3/tc.log , 在辅助服务器上设置: /sbin/iptables -I INPUT -p all -s 10.94.50.21 -j DROP, 将测试服务器发过来的响应包丢弃
 【说明】： 在测试服务器上，并没有通过route add 设置流量转发到辅助服务器上，因为在线上的tcpcopy 将已经将发往测试服务器包的地址改成了 -c 10.0.3.18 辅助服务器的地址
2. tcpcopy 和 intercrept日志：
    (1) tcpcopy：
![image](https://user-images.githubusercontent.com/30469365/28751341-8d51aa86-7537-11e7-87d4-847caeedfe33.png)
  (2) intercept：     
![image](https://user-images.githubusercontent.com/30469365/28751344-a7301d48-7537-11e7-9346-37520632e3fb.png)

3. 各个路由上的tcpdump 截包:
     (1) online tcpcopy -> 测试服务器9990端口包 
![image](https://user-images.githubusercontent.com/30469365/28750997-162ca44a-752f-11e7-8d34-9dcd65a2e199.png)

    (2) test sever 收到的online server 包:
![image](https://user-images.githubusercontent.com/30469365/28751039-adc083e4-752f-11e7-96e0-a6cf50877d15.png)

   (3) test server -> intercept 的包:
![image](https://user-images.githubusercontent.com/30469365/28751071-229b388a-7530-11e7-815a-8d9a1ff84047.png)

(4)intercept -> online server的包：
![image](https://user-images.githubusercontent.com/30469365/28751121-da3f8af8-7531-11e7-9eef-ee9858d9251d.png)

**Comment by legend1121** [comment]
@wangbin579  参考之前您的回复相似issue: https://github.com/session-replay-tools/tcpcopy/issues/173
 我现在的情况是，测试服务器返回给客户端的第二次握手包（SYN+ACK）能转发给辅助服务器，辅助服务器上能捕获到， 且测试服务器和辅助服务器上ip_forward 均设置为0，关闭状态

**Comment by wangbin579** [comment]
最大可能原因是iptables做了ip地址映射导致的，你可以加上tcpcopy的debug，就能大致看到原因了。

btw，为了方便，最好利用最新版本的tcpcopy

**Comment by wangbin579** [comment]
如果是1.0.0版本，加上debug日志，都是加上--with-debug。

**Comment by legend1121** [comment]
@wangbin579  使用1.0版本的tcpcopt和intercept一样的现象， 我这online server和test server 不在一个网段，但网络是通的，看wiki应该不影响
tcpcopy 日志：
![image](https://user-images.githubusercontent.com/30469365/28768878-eefdfca6-760b-11e7-89f7-e5a4dad5d103.png)

intercept日志:
![Uploading image.png…]()

**Comment by legend1121** [comment]
tcpcopy所部署的online server 系统是centos6.3 内核是2.6.32_1-18-0-0
test server和辅助server的系统是centos43, 内核是2.6.32_1-17-0-0
这个会有影响么？

**Comment by wangbin579** [comment]
系统内核不会影响

根本原因是tcpcopy是根据客户端ip地址，客户端端口号来定位的，而从log来看，tcpcopy看到的是10.0.3.18这个ip地址，而intercept看到的是10.94.50.23这个客户端ip地址，intercept就无法找到回去的路了，于是回放失败。

解决策略：
在intercept再做地址映射，把10.94.50.23改回到10.0.3.18，这样才能找到回去的路。

**Comment by legend1121** [comment]
线上tcpcopy 部署在docker容器里， 容器用的虚拟ip地址：10.0.3.18，  所以 您说的 《在intercept再做地址映射，把10.94.50.23改回到10.0.3.18，这样才能找到回去的路。》  iptables 规则加不了啊！

**Comment by wangbin579** [comment]
git clone https://github.com/session-replay-tools/intercept -b docker

加上-D参数，在intercept作ip地址映射
