### ISSUE TITLE
tcpcopy默认配置流量丢失问题

### ISSUE THREAD

**Issue by jianghuiyou** [session-replay-tools/tcpcopy#297]
根据github首页的拓扑搭建的三台机器，机器均是在centos上用kvm虚拟化的三台虚拟机
online server: 192.168.122.190
target server:192.168.122.234
assistent server:192.168.122.130
tcpcopy和intercept均默认./configure
运行命令如下：
./tcpcopy -x 8000-192.168.122.234:8000 -s 192.168.122.130  -c 192.168.2.x -d
./intercept -i ens3 -F 'tcp and src port 8000' -d
 用netcat进行不同大小数据传输测试，并用nload检测流量吞吐，比如发送一个20KB的文件，存在着以下的丢包情况，并且FIN包常常不能在target server收到～

网络吞吐      | 丢失数据比例  
------------ | -------------
20KB/s 以下   |       0%      
| 30KB/s        |       5%      |
| 50KB/s        |       45%     |
| 500KB/s       |       60%     |
| 10MB/s        |       90%     |

请问如何尽可能降低丢包率呢？？？
我已经做过如下尝试：
./configure --single 模式也试过，丢包率依然没变～现在在tcpcopy端尝试--pcap-capture 和 --pcap-send配置，看看能不能降低丢包率～还请高手指教

**Comment by jianghuiyou** [comment]
现在tcpcopy配置了--pcap-capture 并运行如下命令
```shell
./tcpcopy -x 192.168.122.190:8000@52:54:00:d0:73:b0-192.168.122.234:8000@52:54:00:76:7d:da -s 192.168.122.130  -c 192.168.2.x -F 'tcp and src port 8000' -d
```

这个时候，target server却无法收到拷贝过来的流量了～请问我在使用上有什么问题吗，PF_RING是需要开启pcap-capture选项就可以使用吗？

**Comment by jianghuiyou** [comment]
刚刚尝试过--pcap-capture 和 --pcap-send配置，tcpcopy端不管是只开启--pcap-capture，还是两者都开启～丢包率并没有什么变化～主页提到的PF_RING需要如何才能使用呢？多谢您宝贵的时间

**Comment by wangbin579** [comment]
先安装pf_ring,然后configure tcpcopy的时候加上--with-pfring=PF_RING源代码目录。

要使用pfring，要注意两点：
1、确保利用pfring自带的tcpdump抓包不丢包，这样说明pfring安装成功了
2、确保pfring自身不会导致机器崩溃，有些内核版本不稳定

**Comment by wangbin579** [comment]
500KB/s丢包就这么严重，是不是环境太脆弱，可以尝试tcpdump抓包，看看丢包率高不高

**Comment by jianghuiyou** [comment]
tcpdump试过的，在target server确实也存在着大流量丢包的情况～明显和online server tcpdump抓到包的数量差距很大～那请问除了pf_ring之外，还有其他方式降低丢包率呢？

**Comment by wangbin579** [comment]
online server tcpdump抓包丢包率情况如何呢，如果500kb/s情况下抓包都不丢包，说明可能是tcpcopy自身的问题

**Comment by jianghuiyou** [comment]
online server tcpdump抓包是完全正常的～我现在已经可以确定是tcpcopy自身的问题，只是想通过tcpcopy一些更高级的配置来尽可能降低丢包率～

**Comment by wangbin579** [comment]
完全正常倒未必，毕竟遇到这种的情况比较多。

只要session丢一个包，这个session就可能无法继续下去了，在测试服务器看到的是大面积丢请求。

得确认500kb/s的情况下，tcpdump抓包没有一个丢包才能说明，如果确实没有丢包，可以开启tcpcopy的configure -with-debug，捕获丢情况状况

**Comment by jianghuiyou** [comment]
非常感谢您的回答～听您这么一说，就是首先要保证到达online server的包完全不丢，测试服务器才可能不丢。
不过比如我刚刚测过用netcat传输文件一个50KB的文件，tcpdump在online server上抓包分析只能看到一个session，也就是文件发送端只使用了一个port和一个tcp session来输送文件～这个时候在online server看到文件是完整的50KB,而在测试服务器看到的就只有28K，这种情况是不是就说明其实还是tcpcopy的问题呢

**Comment by wangbin579** [comment]
不是到达online server的包完全不丢，而是到达tcpcopy的包完全不丢。

tcpcopy是依赖于抓包环境的，默认是ip层传递数据包给tcpcopy，对于上传类服务，往往上传的包比较多，容易在ip层的queue里面丢掉，具体丢不丢，可以看tcpcopy的debug日志（configure -with-debug）

**Comment by jianghuiyou** [comment]
您好～刚刚查过tcpcopy 的debug日志～不知道最科学查看数据包是否丢失的方式是啥？

我的方法是通过日志中[debug] recv clt:192.168.2.1:44510-->192.168.122.190:8000 序列号之差判断tcpcopy收到的包字节数是51097，而通过[debug] to bak:192.168.2.1:44510-->192.168.122.234:8000序列号之差判断发送到测试服务器的包字节数是28464，和我观察到的文件的大小一样～

我认为这样是不是就可以代表是tcpcopy本身的问题了呢？

**Comment by wangbin579** [comment]
是否丢失，tcpcopy debug日志里面会有记录的

**Comment by jianghuiyou** [comment]
您好～抱歉再次打扰您！
我通过开启tcpcopy的pfring模式、-C 11选项，以及提升tcpcopy的进程优先级，确实一定程度上降低了丢包率，尤其是针对传输较大文件的时候～比如500KB，1MB的文件传输时候，流量在500KB到1MB之间丢包率大部分时候很低，维持在1%之内。但是传送更小一些的50KB文件时候丢包率一直基本稳定在45%，自己查看这个时候的log并没有发现任何error或者warn的log~请问为何会出现这种情况呢？

**Comment by wangbin579** [comment]
得看tcpcopy的debug日志+测试服务器的抓包才能分析，没有这些信息，无法分析原因。

可以发送到我邮箱，我来诊断一下

**Comment by jianghuiyou** [comment]
王斌老师～抱歉再次打扰您～
我用python自己写了一个简单的http cs模型来测试，用来不断传输一定大小的数据。客户端的代码大致如下：
```
import requests as r
import time

interval = 100
num_bytes = 5000 //http每次post数据量的大小，可以变化

test_msg = "t"*num_bytes
seq_num = 888

url = "http://192.168.122.190:8000"

while True :
    post_data = {"data":test_msg, "seq_num":str(seq_num)}
    r.post(url, data=post_data)
    seq_num += 1
    print "post %d"%seq_num
    time.sleep(interval/1000.0)
```
现在遇到的问题是当每次post的数据量在5000的时候没有问题，但是当每次post数据量调整为10000的时候通过tcpdump在online server中抓包，并用wireshark进行查看数据包的内容发现，经过tcpcopy复制之后的数据的后部分被**修改**，查看tcpcopy的log并没有发现error和warn的字样。

数据本该是"tttttt.ttttttttt&seq_num=xxx"前面是10000个t后面跟上序号，而抓包看到发往测试服务器上的数据包后边却变成如下，请问王斌老师这是为什么呢，请您指教
![修改](http://oa576fej8.bkt.clouddn.com/%E4%BF%AE%E6%94%B9.jpeg)

online server: 192.168.122.190
target server:192.168.122.234
assistent server:192.168.122.130
