### ISSUE TITLE
tcpcopy运行一段时间后掉量

### ISSUE THREAD

**Issue by urey-hiker** [session-replay-tools/tcpcopy#298]
您好，非常感谢tcpcopy的开发。
最近在使用过程中发现运行一段时间后就没有流量了，需要重启tcpcopy才能产生流量，掉量的时候应该是有个如下日志：

2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [notice] fd:6 EAGAIN (Resource temporarily unavailable)
2017/08/01 18:33:57 +831 [error] send timeout,fd:6
2017/08/01 18:33:57 +831 [error] fd:6, msg send error
请问出现这一错误的原因可能是什么？是否能在配置上解决？

**Comment by wangbin579** [comment]
不好意思这么久才回复

这个问题一般是压力比较大导致的，尤其是短链接应用（需要传递的路由信息过多），解决方案有如下两种：
1、可以通过加大-C参数（大写的C）来加大tcpcopy和intercept之间的连接数量来缓解
2、tcpcopy和intercept都采用configure --single来编译，避开了路由信息的传递，也就是避开上面的问题，缺点是tcpcopy和intercept只能一一对应

**Comment by urey-hiker** [comment]
非常感谢，采用single及非pcap编译后运行48小时都没有问题。
