### ISSUE TITLE
两台机器之间同步不成功

### ISSUE THREAD

**Issue by titan-web** [session-replay-tools/tcpcopy#300]
现在情况是这样的，同一台机器开两个端口的memcache，可以同步成功，但是两台机器的memcache同步不成功。

- 使用tcpdump抓包，targetserver没有收到响应的请求
- rp_filter也是关闭的

能帮忙分析下是哪里可能会出问题么？

**Comment by titan-web** [comment]
同步断日志：
[warn] Mon Aug 14 21:23:21 2017 usec=468365 send Packets:1,send content packets:0
[notice] Mon Aug 14 21:23:21 2017 usec=468369 reconnect for closed :0,for no syn:0
[notice] Mon Aug 14 21:23:21 2017 usec=468373 successful retransmit:0
[notice] Mon Aug 14 21:23:21 2017 usec=468376 syn cnt:1,all clt packs:7, clt cont:3
[notice] Mon Aug 14 21:23:21 2017 usec=468381 session size:1
[warn] Mon Aug 14 21:23:21 2017 usec=468930 no responses after 15 secends
[warn] Mon Aug 14 21:23:21 2017 usec=468935 many connections can't be established
[notice] Mon Aug 14 21:23:21 2017 usec=468937 activate_dead_sessions
[warn] Mon Aug 14 21:23:30 2017 usec=76118 active:1,rel reqs:0,obs del:0
[warn] Mon Aug 14 21:23:30 2017 usec=76142 conns:0,total resp packs:0,c-resp packs:0
[warn] Mon Aug 14 21:23:30 2017 usec=76145 send Packets:1,send content packets:0
[notice] Mon Aug 14 21:23:30 2017 usec=76147 reconnect for closed :0,for no syn:0
[notice] Mon Aug 14 21:23:30 2017 usec=76149 successful retransmit:0
[notice] Mon Aug 14 21:23:30 2017 usec=76167 syn cnt:1,all clt packs:11, clt cont:5
[notice] Mon Aug 14 21:23:30 2017 usec=76170 session size:1
[warn] Mon Aug 14 21:23:30 2017 usec=76726 no responses after 24 secends
[warn] Mon Aug 14 21:23:30 2017 usec=76730 many connections can't be established
[notice] Mon Aug 14 21:23:30 2017 usec=76732 activate_dead_sessions
[warn] Mon Aug 14 21:23:54 2017 usec=905169 active:1,rel reqs:0,obs del:0
[warn] Mon Aug 14 21:23:54 2017 usec=905195 conns:0,total resp packs:0,c-resp packs:0
[warn] Mon Aug 14 21:23:54 2017 usec=905198 send Packets:1,send content packets:0
[notice] Mon Aug 14 21:23:54 2017 usec=905200 reconnect for closed :0,for no syn:0
[notice] Mon Aug 14 21:23:54 2017 usec=905202 successful retransmit:0
[notice] Mon Aug 14 21:23:54 2017 usec=905204 syn cnt:1,all clt packs:13, clt cont:6
[notice] Mon Aug 14 21:23:54 2017 usec=905206 session size:1
[warn] Mon Aug 14 21:23:54 2017 usec=905778 no responses after 48 secends
[warn] Mon Aug 14 21:23:54 2017 usec=905784 many connections can't be established

**Comment by wangbin579** [comment]
参考 https://github.com/session-replay-tools/tcpcopy/issues/173

**Comment by titan-web** [comment]
targetserver抓不到包，sourceserver可以抓到包，按照上文说的利用-c 修改客户端ip，依然收不到包，线上阿里云的机器

**Comment by titan-web** [comment]
抓包发现syn和reset都转过来了，所以可能是以下的情况，这个应该怎么解决呢，iptables已经按文档配置了
> 说明路由设置有问题或者有冲突,导致了响应包直接返回给真实的客户端了

**Comment by wangbin579** [comment]
参考173里面的新架构解决方案

**Comment by titan-web** [comment]
找到原因了 ，因为intercept设置了-x ip，这个ip来源的数据就同步不过去，感谢
