### ISSUE TITLE
测试服务器收不到流量

### ISSUE THREAD

**Issue by wangfengfly** [session-replay-tools/tcpcopy#302]
线上服务器：10.143.48.182
/usr/local/tcpcopy/sbin/tcpcopy -x 80-10.143.48.132:80 -s 10.143.59.201 -p 36525 -c 10.143.48.x -d

测试服务器：10.143.48.132
route add -net 10.143.48.0 netmask 255.255.248.0 gw 10.143.59.201

intercept机器：10.143.59.201
/usr/local/intercept/sbin/intercept -i eth0,eth1 -F “tcp and src port 80” -p 36525 -d

发现测试服务器还是无法接收请求，tcpdump port 80结果：
14:06:57.001981 IP 10.143.48.1.54176 > 10.143.48.132.http: Flags [S], seq 654018505, win 8192, options [mss 1460,nop,wscale 8,nop,nop,sackOK], length 0
14:07:00.002504 IP 10.143.48.1.54176 > 10.143.48.132.http: Flags [R.], seq 654018506, ack 0, win 65535, length 0

这个会是咋回事呢？？？？？

**Comment by wangfengfly** [comment]
[warn] many connections can't be established

**Comment by lazio579** [comment]
请参考 https://github.com/session-replay-tools/tcpcopy/issues/173 新架构部分

**Comment by chenchenmeimei** [comment]
> [warn] many connections can't be established

你好 想问下你这个问题解决了吗
