### ISSUE TITLE
test+intercept在同一台机器怎么部署？

### ISSUE THREAD

**Issue by linshundong** [session-replay-tools/tcpcopy#303]
我现在也是2台机器的环境（tcpcopy，test+intercept），test有多张网卡，新架构该怎么部署呢？相关的命令和路由规则是怎样的？

**Comment by lazio579** [comment]
intercept运行在test机器，其它还是不变

**Comment by linshundong** [comment]
@lazio579 
tcpcopy：10.8.227.47
test机器:eth0:10.8.110.232和eth1:10.8.110.233
执行命令：
tcpcopy机器：./tcpcopy -x 8081-10.8.110.233:8081 -s 10.8.110.233  -c 10.8.110.232 -n 1
test机器 ./intercept -i eth0 -F 'tcp and src port 8081'
错误：
tcpcopy 报 many connections can't be established
test机器 tcpdump port 8081没有数据包

我配置或者命令哪块有问题呢？

**Comment by zmm2016** [comment]
我也是两台机器部署（tcpcopy，test+intercept），test有两张网卡，请问一下两张网卡不是同一个网段的地址可以部署吗？
