### ISSUE TITLE
src mac address is invalid or not set

### ISSUE THREAD

**Issue by baggiocq** [session-replay-tools/tcpcopy#304]
这是为啥。。

**Comment by lazio579** [comment]
从数据链路层发包，为了实现简单，目前需要设置src mac地址和dst mac地址

**Comment by BeSeriously** [comment]
请问src mac地址和dst mac需要怎么设置呢？

**Comment by lazio579** [comment]
http://blog.csdn.net/wangbin579/article/details/10148247
