### ISSUE TITLE
支持ssl协议吗?

### ISSUE THREAD

**Issue by Trree** [session-replay-tools/tcpcopy#305]
我在 https 的 443 端口测试，在 target server 上面会提示 
```
SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol speaking not SSL to HTTPS port!?
```
这个错误的原因是转发的时候 https://10.2.0.2:443 变成了 http://10.2.0.2:443 发送了。端口和ip都是正确的，但是协议被更改了。
请问这个在协议层需要修改什么吗?

**Comment by jengy** [comment]
view it on GitHub<https://github.com/session-replay-tools/tcpcopy/issues/305>


________________________________
发件人: FeilongWu <notifications@github.com>
发送时间: 2017年10月18日 11:12
收件人: session-replay-tools/tcpcopy
抄送: Subscribed
主题: [session-replay-tools/tcpcopy] 支持ssl协议吗? (#305)


我在 https 的 443 端口测试，在 target server 上面会提示

SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol speaking not SSL to HTTPS port!?


这个错误的原因是转发的时候 https://10.2.0.2:443 变成了 http://10.2.0.2:443 发送了。端口和ip都是正确的，但是协议被更改了。
请问这个在协议层需要修改什么吗?

―

**Comment by lazio579** [comment]
TCPCopy does not support replay for server applications which use SSL/TLS

**Comment by jengy** [comment]
view it on GitHub<https://github.com/session-replay-tools/tcpcopy/issues/305#issuecomment-337472822>

发件人: wangbin [mailto:notifications@github.com]
发送时间: 2017年10月18日 14:27
收件人: session-replay-tools/tcpcopy <tcpcopy@noreply.github.com>
抄送: Zhang Shaojun <sj_zhang@msn.com>; Comment <comment@noreply.github.com>
主题: Re: [session-replay-tools/tcpcopy] 支持ssl协议吗? (#305)


TCPCopy does not support replay for server applications which use SSL/TLS
