### ISSUE TITLE
启动后自动关闭

### ISSUE THREAD

**Issue by ysrotciv** [session-replay-tools/tcpcopy#306]
OS:Ubuntu14
命令
sbin/tcpcopy  -x 10.10.11.63:80@00:16:3e:0a:bc:58-10.10.11.65:80@00:16:3e:0a:be:13 -s 10.10.11.64:8080 -c 10.10.200.x -F 'tcp and src 80' -o eth0 -i eth0

tcpcopy日志：
2017/10/31 19:52:15 +666 [notice] tcpcopy version:1.0.0
2017/10/31 19:52:15 +666 [notice] tcpcopy internal version:6
2017/10/31 19:52:15 +666 [notice] target:10.10.11.63:80@00:16:3e:0a:bc:58-10.10.11.65:80@00:16:3e:0a:be:13
2017/10/31 19:52:15 +666 [notice] pcap version:libpcap version 1.7.4
2017/10/31 19:52:15 +666 [notice] HAVE_SET_IMMEDIATE_MODE is true
2017/10/31 19:52:15 +666 [notice] TC_PCAP mode
2017/10/31 19:52:15 +666 [notice] TC_COMBINED mode
2017/10/31 19:52:15 +666 [notice] TC_PCAP_SND mode
2017/10/31 19:52:15 +666 [notice] epoll mode
2017/10/31 19:52:15 +666 [notice] session timeout:120
2017/10/31 19:52:15 +666 [notice] keepalive timeout:240
2017/10/31 19:52:15 +666 [notice] min sess pool size:576
2017/10/31 19:52:15 +666 [notice] sess pool size:1024
2017/10/31 19:52:15 +666 [notice] raw_clt_tf_ip:10.10.200.x
2017/10/31 19:52:15 +666 [notice] parallel connections per target:2
2017/10/31 19:52:15 +666 [notice] output device:eth0
2017/10/31 19:52:15 +666 [notice] device:eth0
2017/10/31 19:52:15 +666 [notice] user filter:tcp and src 80
2017/10/31 19:52:15 +666 [notice] s parameter:10.10.11.64:8080
2017/10/31 19:52:15 +666 [info] connect to remote server(10.10.11.64:8080)
2017/10/31 19:52:15 +666 [info] connect to remote server(10.10.11.64:8080)
2017/10/31 19:52:15 +666 [notice] pcap open,device:eth0
2017/10/31 19:52:15 +666 [notice] pcap_set_buffer_size:16777216
2017/10/31 19:52:15 +741 [warn] num:18516 > threshold
2017/10/31 19:52:15 +741 [error] Recv socket(6)error
2017/10/31 19:52:15 +741 [notice] close sock:6
2017/10/31 19:52:15 +741 [notice] enter tc_event_destroy:6
2017/10/31 19:52:15 +741 [notice] destroy event:6
2017/10/31 19:52:15 +741 [warn] num:18516 > threshold
2017/10/31 19:52:15 +741 [error] Recv socket(5)error
2017/10/31 19:52:15 +741 [notice] close sock:5
2017/10/31 19:52:15 +741 [warn] active num is zero
2017/10/31 19:52:15 +741 [notice] enter tc_event_destroy:5
2017/10/31 19:52:15 +741 [notice] destroy event:5
2017/10/31 19:52:15 +741 [warn] sig 64 received
2017/10/31 19:52:15 +741 [info] session table, size:65536, total:0
2017/10/31 19:52:15 +741 [notice] tc_epoll_destroy, close fd:5
2017/10/31 19:52:15 +741 [notice] tc_epoll_destroy, close fd:6
2017/10/31 19:52:15 +741 [notice] tc_epoll_destroy, close fd:8
2017/10/31 19:52:15 +741 [notice] tc_event_loop_finish over
2017/10/31 19:52:15 +741 [notice] user time used:0
2017/10/31 19:52:15 +741 [notice] sys  time used:0
2017/10/31 19:52:15 +741 [notice] max memory size:39812
2017/10/31 19:52:15 +741 [notice] Total allocated space (bytes): 416
2017/10/31 19:52:15 +741 [notice] Total free space (bytes): 134752
2017/10/31 19:52:15 +741 [notice] Top-most, releasable space (bytes): 130208

intercept日志：
2017/10/31 19:52:15 +670 [notice] fd is null after session is created
2017/10/31 19:52:15 +670 [notice] from bak:10.10.11.64:8080-->10.10.11.63:36274,len 52,seq=4260342668,ack=307738737
2017/10/31 19:52:15 +670 [notice] fd is null after session is created
2017/10/31 19:52:15 +670 [notice] from bak:10.10.11.64:8080-->10.10.11.63:36274,len 389,seq=4260342668,ack=307738737
2017/10/31 19:52:15 +670 [notice] fd is null after session is created
2017/10/31 19:52:15 +670 [notice] from bak:10.10.11.64:8080-->10.10.11.63:36274,len 52,seq=4260343005,ack=307738737
2017/10/31 19:52:15 +670 [notice] fd is null after session is created
2017/10/31 19:52:15 +670 [notice] from bak:10.10.11.64:8080-->10.10.11.63:36276,len 52,seq=3739577950,ack=566221920
2017/10/31 19:52:15 +670 [notice] fd is null after session is created
2017/10/31 19:52:15 +670 [notice] from bak:10.10.11.64:8080-->10.10.11.63:36276,len 389,seq=3739577950,ack=566221920
2017/10/31 19:52:15 +670 [notice] fd is null after session is created
2017/10/31 19:52:15 +670 [notice] from bak:10.10.11.64:8080-->10.10.11.63:36276,len 52,seq=3739578287,ack=566221920
2017/10/31 19:52:15 +992 [notice] total resp packs:89, all:89, route:0, sock write cnt:0
2017/10/31 19:52:15 +992 [notice] cache hit:0,missed:0,lost:89
2017/10/31 19:52:15 +992 [notice] search:89,extra compared:0,all sessions:0
2017/10/31 19:52:45 +992 [notice] total resp packs:89, all:89, route:0, sock write cnt:0
2017/10/31 19:52:45 +992 [notice] cache hit:0,missed:0,lost:89
2017/10/31 19:52:45 +992 [notice] search:89,extra compared:0,all sessions:0

**Comment by lazio579** [comment]
尝试一下
sbin/tcpcopy -x 10.10.11.63:80@00:16:3e:0a:bc:58-10.10.11.65:80@00:16:3e:0a:be:13 -s 10.10.11.64:36524 -c 10.10.200.x -F 'tcp and dst port 80 and dst host  10.10.11.63:' -o eth0 -i eth0 

-s连接的是intercept的监听地址，-F参数设定的是捕获请求的过滤条件

**Comment by lazio579** [comment]
尝试一下
sbin/tcpcopy -x 10.10.11.63:80@00:16:3e:0a:bc:58-10.10.11.65:80@00:16:3e:0a:be:13 -s 10.10.11.64:36524 -c 10.10.200.x -F 'tcp and dst port 80 and dst host 10.10.11.63' -o eth0 -i eth0

-s连接的是intercept的监听地址，-F参数设定的是捕获请求的过滤条件

**Comment by ysrotciv** [comment]
@lazio579 感谢您的回复，不过虽然我现在可以正常启动tcpcopy服务了，但是无法将向63的请求转发到65。从63上是可以正常向65发送请求的。请问接下来我应该从哪些方面排查呢？

**Comment by lazio579** [comment]
请参考之前的issue
