### ISSUE TITLE
os/ts/as是不是要严格限制在同一个网段？

### ISSUE THREAD

**Issue by anbaoyong** [session-replay-tools/tcpcopy#307]
所有的传输都在数据链路层，这个是不是限制了只能在同一个网段呢？

**Comment by lazio579** [comment]
同一个网段，只是容易一些，跨网段，一般比较麻烦，具体还得看情况。
解决方案之一通过vps

**Comment by cnsky2016** [comment]
我们这边as和ts没跨网段，但是跨交换机，结果导致与as同交换机的服务器收到大量广播数据包；

**Comment by lazio579** [comment]
首先intercept部署到ts机器，然后有如下解决方案（未必都能有效，需要看情况）：
 
方案1: 路由设置的时候，路由给同一交换机下面其它机器即可（只要没有路由转发功能即可）
 
方案2: 改变-c ip地址（能够达到B机器的tcp层就行，但这个ip地址对于中途设备是非法的），让中途设备给黑洞掉，比如交换机来干掉这些非法响应数据包
 
方案3: 路由设置的时候，路由给不存在的机器，看看有没有效果

**Comment by lazio579** [comment]
方案4：-c 成tcpcopy所在机器ip地址，让响应包直接回到tcpcopy所在机器，在tcpcopy所在机器设置iptables过滤掉回来的响应包
