### ISSUE TITLE
求解: 无法通过tcpcopy工具复制ssh的流量

### ISSUE THREAD

**Issue by xichy** [session-replay-tools/tcpcopy#308]
目的：现在共两台git服务器，一台生产服务器online，一台测试环境test。想在测试环境对git clone操作借助tcpcopy进行压力测试，把生产服务器的流量引到测试环境。

当前问题：如果是git clone操作走http协议，则能够通过tcpcopy把生产环境的流量实时引到测试环境；但如果git clone走ssh协议（也就是git clone git@AAA.com），tcpcopy就无法实现流量复制，test能收到请求，但无法上报到业务。

根据之前的issue(https://github.com/session-replay-tools/tcpcopy/issues/280) 提示，将intercept部署到test环境，将tcpcopy部署到online，并且在online上加了iptables限制.

结果是日志中（/var/log/messges）能看到有请求过来，但一直报错如下：
sshd[36169]: Bad packet length 1880754098. [preauth]
sshd[36169]: Disconnecting: Packet corrupt [preauth]
sshd[36173]: Bad protocol version identification 'K\226\375\254\365\332\030\230\347\304\361U\021\356I[2[4\316\236\377\304\373\033\215m\341{\337\270' from 192.168.1.123 port 13240

我将系统的sshd-service替换成从源码重新编译的openssh，加了一些日志，看起来像是数据包被破坏了，导致ssh的检验认证失败，但对更进一步的追查没什么头绪。
PS:为了保证尽可能减少干扰因素，我在生产和测试环境，部署了完全相同的sshd-server。

请教@wangbin579 或者其他哪位大神有类似的经验吗？多谢了

**Comment by lazio579** [comment]
安全类的应用（比如ssh，https），一般情况下是无法复制成功的，需要破解才能，tcpcopy只是tcp层面的破解，还远未到应用层的破解

**Comment by xichy** [comment]
多谢了，看来结论是tcpcopy的当前版本就是不支持ssh。
我再想别的办法做测试
