### ISSUE TITLE
[Question] tcpcopy支持SSH协议

### ISSUE THREAD

**Issue by zjkyz8** [session-replay-tools/tcpcopy#309]
从原理上看，tcpcopy为什么不能支持SSH协议的回放呢？

**Comment by lazio579** [comment]
tcpcopy只是基于tcp层面的破解，上层协议管不过来的，就比如针对mysql协议，还需要开发一个 https://github.com/session-replay-tools/mysql-replay-module 模块来支持

**Comment by zjkyz8** [comment]
我的理解是对于ssh，tcpcopy并不对内容进行解析，只负责把tcp包记录下来，再发送的时候把目标地址改掉就好了，这样理解是错误的吗？

**Comment by wangbin579** [comment]
可以这样理解
