### ISSUE TITLE
test+intercept在同一台机器,有两个网卡，但是两张网卡的IP地址不在同一网段，一个是公网IP，一个内网IP怎么部署？

### ISSUE THREAD

**Issue by zmm2016** [session-replay-tools/tcpcopy#310]

**Comment by lazio579** [comment]
部署没有多少区别，除了会影响测试效果以外

**Comment by zmm2016** [comment]
感谢解答，我的online server也有两个网卡，公网和内网的，但是公网IP和test+intercept这个服务器的公网IP平不通，ping test+intercept内网IP是通的，这就导致tcpcopy报错。
2017/12/14 15:44:18 +504 [error] Can not connect to remote server(106.15.58.31:36524) (Connection timed out)
2017/12/14 15:44:18 +504 [warn] sig 0 received

需要online server 的机器必须能够ping通辅助服务器的机器？

**Comment by lazio579** [comment]
telnet 106.15.58.31 36524都不通，那只能从网络找原因了

**Comment by zmm2016** [comment]
还有一个问题请教一下，由于机器不够，目前考虑传统架构的安装方式，Linux系统为14.04.1-Ubuntu，通过./configure --traditional部署1.0.0版本，在make时出现
src/core/xcopy.h:22:51: fatal error: libnetfilter_queue/libnetfilter_queue.h: No such file or directory
 #include <libnetfilter_queue/libnetfilter_queue.h>
最新架构部署方法一切正常，采用传统架构就会出现这个问题

**Comment by lazio579** [comment]
需要安装netfilter相关的开发库
