### ISSUE TITLE
0.9.8版本丢包，0.9.6版本会重复复制

### ISSUE THREAD

**Issue by lxylzxc** [session-replay-tools/tcpcopy#314]
Hi，和之前的[issue 0.9.0版本重复复制，0.9.8版本会丢包](https://github.com/session-replay-tools/tcpcopy/issues/180)一样：
我也出现了同样的问题，
[warn] frag_off is not IP_DF,use raw socket instead of pcap
流量一直复制不过来，按照上面的说法修改成了0.9.6版本解决了问题
但是在复制另外一类数据时，原先使用0.9.8是正常的，但是使用0.9.6出现了请求复制了2~3份的情况。
在0.9.6版本删除了上面说的代码，流量稍微小了一点点，但是还是2倍多，方便帮忙分析一下吗？

**Comment by lazio579** [comment]
请使用1.0版本，之前版本不再维护

**Comment by lxylzxc** [comment]
1.0的版本，intercept和test_server可以运行在一台机器上面吗？因为一直用的老架构，改新架构的话比较麻烦

**Comment by wangbin579** [comment]
可以
