### ISSUE TITLE
阿里云服务器需要到vpc控制台里配置路由，本机配置的不会生效

### ISSUE THREAD

**Issue by ccddd2** [session-replay-tools/tcpcopy#315]
困扰了好几天，真没想查来查去是这个原因。在此留言一下，希望用阿里云的同学能避免这个问题

**Comment by xingfeng1234** [comment]
> 困扰了好几天，真没想查来查去是这个原因。在此留言一下，希望用阿里云的同学能避免这个问题

除了需要运维同学在阿里云上添加一个目标网段地址作为路由地址外，还需要其他操作吗，求大神指教。
