### ISSUE TITLE
机器不支持iptables，有其他方式可以替换这个命令吗？ 

### ISSUE THREAD

**Issue by mengmengpengpeng** [session-replay-tools/tcpcopy#317]
机器不支持iptables，想使用tcpcopy的话还需要进行内核重新编译，不想使用这样的方式。
还有其他方式可以实现下面命令一样的效果吗？
iptables -A INPUT -s 1.1.1.1 -p tcp --sport 8090 -j DROP

**Comment by lazio579** [comment]
1.0版本默认是不需要iptables的

**Comment by peng1v** [comment]
非常感谢您的回复，下面是我的配置，使用的两台机器，intercept没有单机部署，如果没有下面的iptables命令 ，我抓包看了，tcp握手的第三包是被reset的，找了半天没有找到解决办法。。。

被测机器 （ip是10.181.47.125）
./intercept -i eth0 -F 'tcp and src port 8090' -d

线上机器 （ip是172.18.178.69）
iptables -A INPUT -s 10.181.47.125 -p tcp --sport 8090 -j DROP
./tcpcopy -x 8090-10.181.47.125:8090 -s 10.181.47.125 -c 172.18.178.69 -n 4 -d

**Comment by lazio579** [comment]
根据你的特殊环境，如果被测试机器能够设置iptables，那么可以采用tcpcopy传统模式来做，参考地址: https://github.com/session-replay-tools/tcpcopy/issues/279

如果被测试机器也不能够设置iptables，那可以尝试如下方式：
被测试机器，采用双ip的方式，比如IP A和IP B，tcpcopy根据IP A来连接intercept（-s参数），而-c采用ip B，在被测试机器设置路由，把回ip B的响应包路由到非线上机器，也就是不让响应包回到线上机器

**Comment by peng1v** [comment]
赞思路，我尝试下，谢谢指教

**Comment by takakawa** [comment]
我试一下双ip方案，没有成功，求解是哪里配的不对？
线上机器tcpcopy配置一切正常，被测机新加一个ip，如2.2.2.2，使用tcpcopy时指定-c为2.2.2.2,被测机上只能收到syn包，但是无ack，把-c改为其它ip一切恢复正常，为什么呢？
