### ISSUE TITLE
使用离线模式时，发送一半使用Ctl+C中止发送后，无法重新发送

### ISSUE THREAD

**Issue by takakawa** [session-replay-tools/tcpcopy#319]
使用离线模式发送时，发送一半后，使用ctl+c中止发送，这时在target上报错说连接被reset，这时再重新使用tcpcopy发包，target上可以收到syn包，也能正常回应ack包，但是tcpcopy不继续发送下一包，重启intercept后恢复正常。 不知道这种中间中断发送的操作触发了intercept哪里异常？

注：上以问题是概率性的，有时中断发送后可以正常继续发包

**Comment by takakawa** [comment]
发现Log在狂打：

2018/03/19 18:36:43 +572 [notice] fd is null after session is created
2018/03/19 18:36:43 +572 [notice] from bak:10.9.168.160:22-->10.9.97.233:35996,len 464,seq=554908419,ack=2198453042
2018/03/19 18:36:43 +572 [notice] fd is null after session is created
2018/03/19 18:36:43 +572 [notice] from bak:10.9.168.160:22-->10.9.97.233:35996,len 280,seq=554908831,ack=2198453042
2018/03/19 18:36:43 +572 [notice] fd is null after session is created
2018/03/19 18:36:43 +572 [notice] from bak:10.9.97.233:35996-->10.9.168.160:22,len 52,seq=2198453042,ack=554908831
2018/03/19 18:36:43 +572 [notice] fd is null after session is created
2018/03/19 18:36:43 +572 [notice] from bak:10.9.168.160:22-->10.9.97.233:35996,len 464,seq=554909059,ack=2198453042
2018/03/19 18:36:43 +572 [notice] fd is null after session is created
2018/03/19 18:36:43 +572 [notice] from bak:10.9.168.160:22-->10.9.97.233:35996,len 280,seq=554909471,ack=2198453042vvvvv

**Comment by lazio579** [comment]
没有具体的抓包数据和详细log，很难准确得出结论

大致推理如下：
1、intercept报大量的fd is null after session is created，从上面log来看，可能是intercept过滤条件不详细导致的，毕竟还捕获了22端口，35996端口的数据包，带来了判断方面的干扰。

2、由于tcpcopy被终止，可能由于某种原因，target连接还存在，再发送syn数据包过去，target服务器可能会拒绝新建连接，毕竟已经有同样的连接存在了，于是可能回复一个非第二次握手数据包回去。
这个可以通过抓包来确认。

解决方案有如下：
１、等后端连接都没有了（ss -s都没有相应tcp状态即可），再重新启动tcpcopy
2、intercept尝试--single，一个tcpcopy只对应intercept

如果上面都无法解决，请在tcpcopy和intercept端加上--with-debug，把相应debug log发到我邮箱，具体来查看原因。
