### ISSUE TITLE
tcpcopy 转发 http 流量，丢包

### ISSUE THREAD

**Issue by ritayzy** [session-replay-tools/tcpcopy#321]
系统: 2.6.32-504.el6.x86_64
软件版本: tcpcopy version:1.0.0
tcpcopy 编译方式 ./configure --prefix=/opt/app/tcpcopy-1.0.0 --with-debug  --pcap-capture --with-pfring=/opt/soft/PF_RING-7.0.0
intercept 编译方式： ./configure --prefix=/opt/app/intercept-1.0.0 --with-debug --with-pfring=/opt/soft/PF_RING-7.0.0
线上机器: 192.168.33.11（tcpcopy)
辅助机器: 192.168.33.12 (intercept)
测试机器: 192.168.33.13

参考这篇文章的安装方式
[tcpcopy优化实战记录](http://www.jianghuiyou.com/2017/08/06/tcpcopy%E4%BC%98%E5%8C%96%E5%AE%9E%E6%88%98%E8%AE%B0%E5%BD%95/)

tcpcopy 执行方式如下
```
/opt/app/tcpcopy-1.0.0/sbin/tcpcopy -C 11 -x 192.168.33.11:80@08:00:27:6c:cf:1f-192.168.33.13:80@08:00:27:62:81:8f -s 192.168.33.12 -c 192.168.2.2 -F tcp port 80 -i eth1 -l /tmp/tcpcopy.log -d
```

intercept 执行方式如下
```
/opt/app/intercept-1.0.0/sbin/intercept -i eth1 -F tcp and src port 80 -d
```

当像`192.168.33.11` 发送 http 请求时，content-length 超过 15000 左右，开始出现包捕捉不到的问题，

测试机器上面的 nginx 返回 400 ，报错信息如下截图

![image](https://user-images.githubusercontent.com/18484770/38862075-983e7166-4266-11e8-9d8a-6253d143ef52.png)

测试机器上面使用 `tcpdump` 捕捉到的信息如下

![image](https://user-images.githubusercontent.com/18484770/38862204-ecd5e722-4266-11e8-8e62-bc206f9c5ca2.png)

curl 调用信息接 tcpdump 调用信息如下

[curl.txt](https://github.com/session-replay-tools/tcpcopy/files/1919099/curl.txt)

[wireshare 打开.txt](https://github.com/session-replay-tools/tcpcopy/files/1919106/wireshare.txt)

[tcpcopy.log](https://github.com/session-replay-tools/tcpcopy/files/1919110/tcpcopy.log)

希望大家帮忙看看，非常感谢。

**Comment by lazio579** [comment]
非常感谢提供这么详细的资料。

通过log，发现可能的问题原因是：
2037         srv_sk_buf_s = s->target_nxt_seq - s->rep_ack_seq  + cont_len;
2038         if (srv_sk_buf_s > s->peer_window) {
2039             tc_log_debug3(LOG_DEBUG, 0, "wait,srv_sk_buf_s:%u, win:%u, p:%u",
2040                     srv_sk_buf_s, s->peer_window, ntohs(s->src_port));
2041             s->sm.delay_snd = 1;
2042             return PACK_STOP;
2043         }

改成：

2037         srv_sk_buf_s = s->target_nxt_seq - s->rep_ack_seq  + cont_len;
2038         /*if (srv_sk_buf_s > s->peer_window) {
2039             tc_log_debug3(LOG_DEBUG, 0, "wait,srv_sk_buf_s:%u, win:%u, p:%u",
2040                     srv_sk_buf_s, s->peer_window, ntohs(s->src_port));
2041             s->sm.delay_snd = 1;
2042             return PACK_STOP;
2043         }*/

把2038到2043都注释掉，看看效果如何？

**Comment by lazio579** [comment]
方便的话，邮件或者qq联系（5223378）

**Comment by ritayzy** [comment]
已添加好友，你说的方案，我马上尝试一下 @lazio579

**Comment by lazio579** [comment]
你尝试一下最新版本，看看是否修复了这个问题

**Comment by ritayzy** [comment]
已经修复了，感谢感谢啊 @lazio579 👍 😄
