### ISSUE TITLE
tcpcopy怎样使用长连接

### ISSUE THREAD

**Issue by watson-qu** [session-replay-tools/tcpcopy#322]
你好，线上我目前有一台服务器。大约有40个客户端使用长连接调用他，我使用tcpcopy部署在线上 想要复制长连接的流量到测试机上。发现从tcpcopy发往测试服务器的包里的，ip和端口号很少有重复的，这样基本每个请求都会建立一次长连接，由于线上访问量大，很快就就把测试机的连接打满了，请问有什么解决方法吗？

**Comment by wangbin579** [comment]
这个得抓包分析的，得看看连接为啥关闭的。

本身长连接本身是支持的，但不同的场景，可能有不同的干扰因素。

你可以发抓包文件发给我，我看看到底是什么原因导致了连接关闭。

邮箱是wangbin579@gmail.com
