### ISSUE TITLE
测试服务没请求，辅助服务器总是抛出错误

### ISSUE THREAD

**Issue by lx668** [session-replay-tools/tcpcopy#323]
谢谢博主抽出时间帮我查看问题

线上环境模拟故障
Note:
1.内核大于2.6
2.root用户启动
3.ip_forward 禁止

整个网络环境为阿里云大二层网络
线上服务器:172.18.0.215/20  (tcpcopy服务)
测试服务器:172.18.1.58/20
辅助服务器:172.18.0.224/20  (intercpet服务)

每台服务器启动方式
======================
线上服务器
python -m SimpleHTTPServer 80
/usr/local/tcpcopy/sbin/tcpcopy -x 80-172.18.1.58:80 -s 172.18.0.224 -c 62.135.200.0 -d -C 4 -l /var/log/tcpcopy.log

测试服务器
python -m SimpleHTTPServer 80
route add -net 62.135.200.0 netmask 255.255.0.0 gw 172.18.0.224

辅助服务器
/usr/local/intercept/sbin/intercept -i eth0 -l /var/log/intercept.log -F tcp and src port 80 -d

情况一：
我在内网网段发送一个get请求到线上服务器，线上服务器返回结果，但是测试服务器并没有收到packages

下面是我在online机器上面抓取的包，并没有
tcpdump dst 172.18.1.58 and port 80
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes

然后我在测试服务抓包，并没有
tcpdump  src 172.18.0.215 and port 80
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes

情况二：
启动辅助服务器之后不停地刷下面信息
2018/05/21 16:15:53 +777 [notice] from bak:172.18.192.176:9096-->172.18.0.224:55913,len 70,seq=600211903,ack=4196604217
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:55913-->172.18.192.176:9096,len 52,seq=4196604217,ack=600211921
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57233,len 59,seq=3926572276,ack=1184630945
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.209.88:9096-->172.18.0.224:62065,len 70,seq=3672354033,ack=2487251790
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.209.88:9096-->172.18.0.224:62065,len 4235,seq=3672354051,ack=2487251790
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.209.88:9096-->172.18.0.224:62065,len 70,seq=3672358234,ack=2487251790
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57213,len 59,seq=1903457328,ack=1458911050
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:13907-->172.18.209.89:9096,len 159,seq=3334444097,ack=1144790046
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:62065-->172.18.209.88:9096,len 52,seq=2487251790,ack=3672358252
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:57233-->172.18.36.159:9223,len 93,seq=1184630945,ack=3926572283
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:57213-->172.18.36.159:9223,len 66,seq=1458911050,ack=1903457335
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:55913-->172.18.192.176:9096,len 159,seq=4196604217,ack=600211921
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57175,len 61,seq=615948683,ack=251168713
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:62065-->172.18.209.88:9096,len 159,seq=2487251790,ack=3672358252
2018/05/21 16:15:53 +777 [notice] fd is null after session is created
2018/05/21 16:15:53 +777 [notice] from bak:172.18.0.224:57175-->172.18.36.159:9223,len 66,seq=251168713,ack=615948692
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57185,len 56,seq=3755943067,ack=1167687459
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57227,len 56,seq=2517535286,ack=3934055771
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57181,len 59,seq=390470983,ack=2331726722
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57185-->172.18.36.159:9223,len 66,seq=1167687459,ack=3755943071
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57225,len 59,seq=111456887,ack=1777781345
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57181-->172.18.36.159:9223,len 66,seq=2331726722,ack=390470990
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57225-->172.18.36.159:9223,len 106,seq=1777781345,ack=111456894
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57227-->172.18.36.159:9223,len 66,seq=3934055771,ack=2517535290
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:54483-->172.18.36.151:3306,len 100,seq=916103489,ack=1668202465
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:54494-->172.18.36.151:3306,len 223,seq=2414109448,ack=4255555933
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:46637-->172.18.36.151:3306,len 100,seq=1926080686,ack=3368776106
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:54486-->172.18.36.151:3306,len 100,seq=1178035771,ack=187087678
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57205,len 56,seq=3442763040,ack=3463461550
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.192.176:9096-->172.18.0.224:55913,len 68,seq=600211921,ack=4196604324
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:49021-->172.18.36.151:3306,len 93,seq=3297234253,ack=2865983705
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57171,len 59,seq=2023733473,ack=2684736193
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57205-->172.18.36.159:9223,len 66,seq=3463461550,ack=3442763044
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57171-->172.18.36.159:9223,len 92,seq=2684736193,ack=2023733480
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:52968-->172.18.36.151:3306,len 100,seq=4110207121,ack=1424436066
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:54492-->172.18.36.151:3306,len 100,seq=4025490907,ack=3328623358
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.192.176:9096-->172.18.0.224:55913,len 67,seq=600211937,ack=4196604324
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.192.176:9096-->172.18.0.224:55913,len 70,seq=600211952,ack=4196604324
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.192.176:9096-->172.18.0.224:55913,len 4530,seq=600211970,ack=4196604324
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.192.176:9096-->172.18.0.224:55913,len 70,seq=600216448,ack=4196604324
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:55913-->172.18.192.176:9096,len 52,seq=4196604324,ack=600216466
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:55913-->172.18.192.176:9096,len 159,seq=4196604324,ack=600216466
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57213,len 59,seq=1903457335,ack=1458911064
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.156:47343-->172.18.0.224:60008,len 523,seq=1031115860,ack=923826757
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:60008-->172.18.36.156:47343,len 70,seq=923826757,ack=1031116331
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57213-->172.18.36.159:9223,len 108,seq=1458911064,ack=1903457342
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57175,len 59,seq=615948692,ack=251168727
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57181,len 59,seq=390470990,ack=2331726736
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57227,len 59,seq=2517535290,ack=3934055785
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57185,len 59,seq=3755943071,ack=1167687473
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57175-->172.18.36.159:9223,len 66,seq=251168727,ack=615948699
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.36.159:9223-->172.18.0.224:57233,len 57,seq=3926572283,ack=1184630986
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57181-->172.18.36.159:9223,len 108,seq=2331726736,ack=390470997
2018/05/21 16:15:53 +778 [notice] fd is null after session is created
2018/05/21 16:15:53 +778 [notice] from bak:172.18.0.224:57233-->172.18.36.159:9223,len 66,seq=1184630986,ack=3926572288

**Comment by lx668** [comment]
下面是tcpcopy日志
2018/05/21 17:34:12 +389 [notice] user time used:1
2018/05/21 17:34:12 +389 [notice] sys  time used:4
2018/05/21 17:34:12 +389 [notice] max memory size:4720
2018/05/21 17:34:12 +389 [notice] Total allocated space (bytes): 53680
2018/05/21 17:34:12 +389 [notice] Total free space (bytes): 81488
2018/05/21 17:34:12 +389 [notice] Top-most, releasable space (bytes): 81008
2018/05/21 17:34:12 +389 [notice] active:0,rel:1,obs del:0,tw:0
2018/05/21 17:34:12 +389 [notice] conns:0,resp:0,c-resp:0
2018/05/21 17:34:12 +389 [notice] resp fin:0,resp rst:0
2018/05/21 17:34:12 +389 [notice] send:2,send content:0
2018/05/21 17:34:12 +389 [notice] send syn:1, fin:0,reset:1
2018/05/21 17:34:12 +389 [notice] reconnect:0,for no syn:0
2018/05/21 17:34:12 +389 [notice] retransmit:0
2018/05/21 17:34:12 +389 [notice] recv packs after retransmission:0
2018/05/21 17:34:12 +389 [notice] syn cnt:1,all clt:6,clt cont:1
2018/05/21 17:34:12 +389 [notice] total cont retransmit:0, frag:0
2018/05/21 17:34:12 +389 [notice] total captured packets:406924





2018/05/21 17:34:42 +389 [notice] active:0,rel:2,obs del:0,tw:0
2018/05/21 17:34:42 +389 [notice] conns:0,resp:0,c-resp:0
2018/05/21 17:34:42 +389 [notice] resp fin:0,resp rst:0
2018/05/21 17:34:42 +389 [notice] send:4,send content:0
2018/05/21 17:34:42 +389 [notice] send syn:2, fin:0,reset:2
2018/05/21 17:34:42 +389 [notice] reconnect:0,for no syn:0
2018/05/21 17:34:42 +389 [notice] retransmit:0
2018/05/21 17:34:42 +389 [notice] recv packs after retransmission:0
2018/05/21 17:34:42 +389 [notice] syn cnt:2,all clt:12,clt cont:2
2018/05/21 17:34:42 +389 [notice] total cont retransmit:0, frag:0
2018/05/21 17:34:42 +389 [notice] total captured packets:594662

**Comment by lx668** [comment]
目前我已经重新测试了，
tcpcopy机器已经抓包看到有流量出去
![image](https://user-images.githubusercontent.com/16302571/40351158-50f3144a-5dde-11e8-8cdb-7938040f6ed1.png)

在测试服务器上面根本没有抓取到任何跟8000端口包的流量

**Comment by xingfeng1234** [comment]
> 目前我已经重新测试了，
> tcpcopy机器已经抓包看到有流量出去
> ![image](https://user-images.githubusercontent.com/16302571/40351158-50f3144a-5dde-11e8-8cdb-7938040f6ed1.png)
> 
> 在测试服务器上面根本没有抓取到任何跟8000端口包的流量

你好，你的问题解决了吗，是怎么解决的？

**Comment by wangbin579** [comment]
-c参数用-c 192.18.1.X，不要用-c 192.18.1.0

**Comment by wangbin579** [comment]
目前ip网段是以x结尾，没有采用0结尾

**Comment by DongtianA** [comment]
> > 目前我已经重新测试了，
> > tcpcopy机器已经抓包看到有流量出去
> > ![图片](https://user-images.githubusercontent.com/16302571/40351158-50f3144a-5dde-11e8-8cdb-7938040f6ed1.png)
> > 在测试服务器上面根本没有抓取到任何跟8000端口包的流量
> 
> 你好，你的问题解决了吗，是怎么解决的？

请问 问题解决了？遇到了同样的问题，线上服务有流量进入，但是测试机没有抓到任何流量。
![image](https://user-images.githubusercontent.com/33851943/64253716-6e842c80-cf50-11e9-9f3e-9fc4acc24f66.png)

**Comment by BruceLuo33** [comment]
> > > 目前我已经重新测试了，
> > > tcpcopy机器已经抓包看到有流量出去
> > > ![图片](https://user-images.githubusercontent.com/16302571/40351158-50f3144a-5dde-11e8-8cdb-7938040f6ed1.png)
> > > 在测试服务器上面根本没有抓取到任何跟8000端口包的流量
> > 
> > 
> > 你好，你的问题解决了吗，是怎么解决的？
> 
> 请问 问题解决了？遇到了同样的问题，线上服务有流量进入，但是测试机没有抓到任何流量。
> ![image](https://user-images.githubusercontent.com/33851943/64253716-6e842c80-cf50-11e9-9f3e-9fc4acc24f66.png)

请问你的问题解决了吗？我也是同样的问题

**Comment by BruceLuo33** [comment]
> -c参数用-c 192.18.1.x，不要用-c 192.18.1.0

请问大佬，我设置的 -c 192.168.1.x 可以正常导入流量，但是设置 -c 192.18.1.x 测试机器就收不到导入的流量。请问这是怎么回事呢？

**Comment by BruceLuo33** [comment]
![image](https://user-images.githubusercontent.com/38673091/123753484-7d3d8f80-d8ec-11eb-81b9-ea1ae6507597.png)

**Comment by zhaochuhan** [comment]
我也遇到同样的问题，我的测试服务器与intercept在一台，线上环境端口一直有copy流量，但是测试环境偶尔有

**Comment by zhaochuhan** [comment]
具体情况如下:
![Uploading Snipaste_2024-03-08_15-42-47.png…]()
