### ISSUE TITLE
intercept返回的响应包没有剥离body信息

### ISSUE THREAD

**Issue by pymi666** [session-replay-tools/tcpcopy#324]
intercept返回的响应包应该只保留头信息返回给online server。但是我在online上抓包，辅助服务器返回的信息是完整的，没有剥离掉body信息；
是按照github文档直接安装，运行的；
online server: 192.168.39.48
test server : 192.168.39.47
Assistant Server ：192.168.39.49
user ip：10.0.4.174

intercept -i eth3 -F 'tcp and src port 3389' -d
tcpcopy -x 80-192.168.39.47:3389 -s 192.168.39.49 
test server 配置路由：route add -host 10.0.4.174 gw 192.168.39.49

**Comment by lazio579** [comment]
辅助服务器返回的信息，是类似ip tunnel的机制，把响应包头信息封装到body里面返回给tcpcopy处理了

**Comment by lazio579** [comment]
辅助服务器，是不是开启了ip forward功能？如果开启的话，需要关闭，好让响应包不返回给tcpcopy

**Comment by pymi666** [comment]
知道什么问题了，因为是用虚拟机测试，tcpdump抓到的虚拟机网卡的数据包和真实网卡数据包是完全一样的；响应包本是发往真实机的，结果在虚拟机也抓到响应包了；后来换成真实物理机测试，ok了，感谢感谢！！！
