### ISSUE TITLE
王工，请问tcpcopy是否适用以下情况？

### ISSUE THREAD

**Issue by liulei8072** [session-replay-tools/tcpcopy#326]
王工，您好：
                    目前公司想用tcpcopy做服务器引流测试，项目类似于滴滴叫车，假设在同一时间点，有10万用户同时发起订单请求，从用户提交订单开始算，到用户结束订单，这个时间为1小时，在这1小时内每3秒会发起请求上传数据，请问10万的量并1小时内持续多次发请求，tcpcopy可以完成吗？

**Comment by lazio579** [comment]
tcpcopy是基于线上真实数据来做的，自己不会生成数据。
如果线上就有10万，并且持续多次发送请求，只要协议是可回放的，就可以由tcpcopy来完成

**Comment by liulei8072** [comment]
王工，可能有一点我没有描述清楚，这个10万是我要放大到的量，本身真实数据可能只有50，这样应该也可以吧？

**Comment by zhisrc** [comment]
长连接应该是搞不了的吧
