### ISSUE TITLE
使用pcap-capture模式可能出现TS上有一定概览出现重复的一条

### ISSUE THREAD

**Issue by tweyseo** [session-replay-tools/tcpcopy#328]
环境如下:
./configure --pcap-capture
tcpcopy version:1.2.0
OS:ip192.25.103.42
TS:ip 192.25.106.106
AS:ip 192.25.106.105tc
OS:tcpcopy -x 10080-192.25.106.106:10080 -s 192.25.106.105 -c 192.168.2.225 -F 'tcp and dst port 10080' -d
TS:route add -host 192.168.2.225 gw 192.25.106.105
AS:intercept -i ens192 -F 'tcp and src port 10080' -d

一定概率下出现TS收到两条一样的消息:
ngx的log如下有打印时间出来(毫秒):
2018/06/29 15:37:13 [warn] 62250#0: *124 [lua] httpPing.lua:10: **time:1530257833.551**, client: 192.168.2.225, server: , request: "GET /test/httpPing HTTP/1.1", host: "192.25.103.42:10080"
2018/06/29 15:37:13 [warn] 62247#0: *125 [lua] httpPing.lua:10: **time:1530257833.552**, client: 192.168.2.225, server: , request: "GET /test/httpPing HTTP/1.1", host: "192.25.103.42:10080"

还有个疑问就是为什么pcap-capture模式必须指定-F?

**Comment by tweyseo** [comment]
写了会代码再回来 就复现不来了- -

**Comment by lazio579** [comment]
运行一个tcpcopy实例？

重复记录，也得tcp seq配合才行，单个tcpcopy没有碰到过，多个实例因为lvs的问题出现过

**Comment by tweyseo** [comment]
不是tcp层的重复 是业务层的重发 感觉像tcpcopy消息发了两次? 后面再出现了 我抓个包看看

**Comment by lazio579** [comment]
抓包看看吧

按道理是不可能的
