### ISSUE TITLE
tcpcopy需要ip_queue模块吗？

### ISSUE THREAD

**Issue by onebraveman** [session-replay-tools/tcpcopy#329]
自己按照文档，搭建好了tcpcopy, intercept服务，但是TCP连接一直被reset。

按照这个问题，查看了文档[1](https://github.com/session-replay-tools/tcpcopy/issues/173)。现在的问题是自己已经配置了路由，看网上有文档说需要加载`ip_queue`模块。请问下，是这样吗？ @wangbin579

**Comment by lazio579** [comment]
1.0版本不需要ip queue了

**Comment by onebraveman** [comment]
我在使用过程中，intercept无法截获报文。从抓包接包开看，online机器能够发送sync包了，3S过后就发送reset包到target机器了。

部署方案是online+tcpcopy一台机器，intercept+target一台机器。target设置路由将tcpcopy请求IP转发到target机器。找了好几天文档，目前使用的临时解决方案是tcpcopy的ip设置成online机器IP，online机器iptables对返回结果DROP处理。
版本：
intercept-1.0.0
tcpcopy1.2.0

这种情况应该从哪里查呢？

**Comment by lazio579** [comment]
intercept和target在一台机器，路由设置不能路由给自己吧。

临时解决方案也可以，我经常这样用，一方面可以规避syn数据包被干掉，另外一方面需要的资源比较少，不足之处就是ip地址只能用online机器。

**Comment by onebraveman** [comment]
如果intercept和target在一台机器，如何路由呢？

目前在尝试intercept和target在两台机器，在解决RESET问题。自己尝试了以下几种方式：
- route add xxx：将online tcpcopy流量IP路由到assistant server -> 修改后仍然不能建立连接
- intercept/target增加iptables ->  无法建立连接

从日志上来看，intercept机器出现大量日志：`fd is null after session is created`. Google了很多文章，大部分都是说设置路由，我的命令是`route add -net 62.135.200.0 netmask 255.255.255.0 gw 10.120.180.206`. 这是命令有问题吗？

**Comment by xingfeng1234** [comment]
> 如果intercept和target在一台机器，如何路由呢？
> 
> 目前在尝试intercept和target在两台机器，在解决RESET问题。自己尝试了以下几种方式：
> 
> * route add xxx：将online tcpcopy流量IP路由到assistant server -> 修改后仍然不能建立连接
> * intercept/target增加iptables ->  无法建立连接
> 
> 从日志上来看，intercept机器出现大量日志：`fd is null after session is created`. Google了很多文章，大部分都是说设置路由，我的命令是`route add -net 62.135.200.0 netmask 255.255.255.0 gw 10.120.180.206`. 这是命令有问题吗？

你好，问题解决没，怎么解决的呢？
