### ISSUE TITLE
离线导流回放时总是报错slide win:too many packs

### ISSUE THREAD

**Issue by ruoya** [session-replay-tools/tcpcopy#334]
hi，你好：
   我最近在做离线导流的测试，服务是socket的接口，发布端口是9998
从线上机器用tcpdump录制了部分流量。然后到测试机器上进行回放。
录制命令：tcpdump -i eth0 tcp and port 9998 -s 0 -w online.pcap 
回放的测试机上面安装了intercept1.0和tcpcopy1.0
intercept启动命令如下：/usr/local/intercept/sbin/intercept -i eth0 -F tcp and src port 9998 -l /home/adadmin/tcpcopy/intercept.log -d
回放命令如下:/usr/local/tcpcopy/sbin/tcpcopy -i /data/adadmin/tcpcopy/online3.pcap -x 9998-*.*.*.*: 9998 -s *.*.*.* -l /data/adadmin/tcpcopy/.tcpcopy.log 

回放之后，tcpcopy的log如下：
2018/08/10 12:43:47 +182 [warn] sig 2 received
2018/08/10 12:43:47 +182 [notice] active:140,rel:1,obs del:0,tw:0
2018/08/10 12:43:47 +182 [notice] conns:141,resp:1070,c-resp:13
2018/08/10 12:43:47 +182 [notice] resp fin:1,resp rst:0
2018/08/10 12:43:47 +182 [notice] send:2261,send content:1964
2018/08/10 12:43:47 +182 [notice] send syn:141, fin:4,reset:0
2018/08/10 12:43:47 +182 [notice] reconnect:0,for no syn:137
2018/08/10 12:43:47 +182 [notice] retransmit:92
2018/08/10 12:43:47 +182 [notice] recv packs after retransmission:0
2018/08/10 12:43:47 +182 [notice] syn cnt:4,all clt:37363,clt cont:37314
2018/08/10 12:43:47 +182 [notice] total cont retransmit:0, frag:0
2018/08/10 12:43:47 +182 [notice] total captured packets:69247
2018/08/10 12:43:47 +182 [info] session table, size:65536, total:140
2018/08/10 12:43:47 +182 [warn] sig 2 received
2018/08/10 12:43:47 +182 [notice] active:140,rel:1,obs del:0,tw:0
2018/08/10 12:43:47 +182 [notice] conns:141,resp:1070,c-resp:13
2018/08/10 12:43:47 +182 [notice] resp fin:1,resp rst:0
2018/08/10 12:43:47 +182 [notice] send:2261,send content:1964
2018/08/10 12:43:47 +182 [notice] send syn:141, fin:4,reset:0
2018/08/10 12:43:47 +182 [notice] reconnect:0,for no syn:137
2018/08/10 12:43:47 +182 [notice] retransmit:92
2018/08/10 12:43:47 +182 [notice] recv packs after retransmission:0
2018/08/10 12:43:47 +182 [notice] syn cnt:4,all clt:37363,clt cont:37314
2018/08/10 12:43:47 +182 [notice] total cont retransmit:0, frag:0
2018/08/10 12:43:47 +182 [notice] total captured packets:69247
2018/08/10 12:43:47 +182 [info] session table, size:65536, total:140
2018/08/10 12:43:47 +182 [notice] tc_epoll_destroy, close fd:5
2018/08/10 12:43:47 +182 [notice] tc_epoll_destroy, close fd:6
2018/08/10 12:43:47 +182 [notice] tc_event_loop_finish over
2018/08/10 12:43:47 +182 [notice] user time used:0
2018/08/10 12:43:47 +182 [notice] sys  time used:0
2018/08/10 12:43:47 +182 [notice] max memory size:78660
2018/08/10 12:43:47 +182 [notice] Total allocated space (bytes): 368
2018/08/10 12:43:47 +182 [notice] Total free space (bytes): 253584
2018/08/10 12:43:47 +182 [notice] Top-most, releasable space (bytes): 253104
2018/08/10 12:43:55 +570 [notice] tcpcopy version:1.2.0
2018/08/10 12:43:55 +570 [notice] tcpcopy internal version:6
2018/08/10 12:43:55 +570 [notice] target:9998-10.115.132.94:9998
2018/08/10 12:43:55 +570 [notice] TC_OFFLINE mode
2018/08/10 12:43:55 +570 [notice] TC_COMBINED mode
2018/08/10 12:43:55 +570 [notice] epoll mode
2018/08/10 12:43:55 +570 [notice] session timeout:120
2018/08/10 12:43:55 +570 [notice] keepalive timeout:240
2018/08/10 12:43:55 +570 [notice] min sess pool size:608
2018/08/10 12:43:55 +570 [notice] sess pool size:1024
2018/08/10 12:43:55 +570 [notice] set global port for tcpcopy
2018/08/10 12:43:55 +570 [notice] parallel connections per target:2
2018/08/10 12:43:55 +570 [notice] accelerated 1 times,interval:0 ms
2018/08/10 12:43:55 +570 [notice] s parameter:10.115.132.94
2018/08/10 12:43:55 +570 [notice] set only ip for tcpcopy
2018/08/10 12:43:55 +570 [info] connect to remote server(10.115.132.94:36524)
2018/08/10 12:43:55 +570 [info] connect to remote server(10.115.132.94:36524)
2018/08/10 12:43:55 +570 [notice] open pcap success:/data/adadmin/tcpcopy/online.pcap
2018/08/10 12:43:55 +570 [notice] send the first packets here
2018/08/10 12:44:25 +570 [notice] active:141,rel:1,obs del:0,tw:1
2018/08/10 12:44:25 +570 [notice] conns:142,resp:1114,c-resp:7
2018/08/10 12:44:25 +570 [notice] resp fin:2,resp rst:0
2018/08/10 12:44:25 +570 [notice] send:2308,send content:2011
2018/08/10 12:44:25 +570 [notice] send syn:142, fin:5,reset:0
2018/08/10 12:44:25 +570 [notice] reconnect:0,for no syn:137
2018/08/10 12:44:25 +570 [notice] retransmit:87
2018/08/10 12:44:25 +570 [notice] recv packs after retransmission:0
2018/08/10 12:44:25 +570 [notice] syn cnt:5,all clt:51829,clt cont:51774
2018/08/10 12:44:25 +570 [notice] total cont retransmit:0, frag:0
2018/08/10 12:44:25 +570 [notice] total captured packets:96067
2018/08/10 12:44:28 +570 [warn] slide win:too many packs:511,p:40853
2018/08/10 12:44:28 +580 [warn] slide win:too many packs:823,p:47086
2018/08/10 12:44:28 +590 [warn] slide win:too many packs:923,p:41320
2018/08/10 12:44:28 +600 [warn] slide win:too many packs:266,p:40565
2018/08/10 12:44:28 +600 [warn] slide win:too many packs:342,p:51166
2018/08/10 12:44:28 +620 [warn] slide win:too many packs:735,p:43966
2018/08/10 12:44:28 +620 [warn] slide win:too many packs:677,p:55941
2018/08/10 12:44:28 +630 [warn] slide win:too many packs:261,p:55185

网络抓包的话，也能抓取到访问这个机器和这个机器回应的包。
但是服务总是报错：socket 3157 closed by peer.
请大神指点

**Comment by wangbin579** [comment]
抓个包看一下，为啥连接请求异常了，可能你们的协议不支持回放，可能需要调整认证策略等才能回放

**Comment by ruoya** [comment]
回放的时候，请求好像都失败了，很多重复，而且length也都是0

**Comment by ruoya** [comment]
我好像知道原因了，是由于我的是长连接的请求，请求处理完之后，是要给源发送返回的，而源都是线上机器，所以发送都失败了。这个能处理吗？比如忽略这个报文发送之类的。。

**Comment by chenchenmeimei** [comment]
> 我好像知道原因了，是由于我的是长连接的请求，请求处理完之后，是要给源发送返回的，而源都是线上机器，所以发送都失败了。这个能处理吗？比如忽略这个报文发送之类的。。

额  这个问题解决了吗 我也遇到这个相同的日志报的问题了 跪求

**Comment by chenchenmeimei** [comment]
> 不太理解。
> 
> 一般忽略报文，都是从应用层来做，比如对mysql进行回放，就可以采用skip-grant-tables来忽略认证过程

大神 有离线回放的操作文档吗 最近再录制流量 也遇到了这个问题

**Comment by bulabula001** [comment]
也遇到此问题，离线回放如果放大倍数过大时候会遇到快速断开的问题
