### ISSUE TITLE
mysql 回放读取不到plugin.conf中的user和password

### ISSUE THREAD

**Issue by gaoquan6297** [session-replay-tools/tcpcopy#335]
plugin.conf:
user cmdb_r@qbWoaE;

使用tcpcopy进行回放时报以下日志：
2018/08/27 20:17:50 +826 [info] state:6, con len:36,p:23417
2018/08/27 20:17:50 +826 [info] new req from clt:23417
2018/08/27 20:17:50 +826 [info] change fir auth:23417
2018/08/27 20:17:50 +826 [warn] user:,pwd is null
2018/08/27 20:17:50 +826 [warn] change fir auth unsuccessful
2018/08/27 20:17:50 +826 [info] we can not continue:23417
2018/08/27 20:17:50 +826 [debug] sess post disp:23417
2018/08/27 20:17:50 +826 [info] req unsend:23417,syn seq:1158268127,max:1158268164
2018/08/27 20:17:50 +826 [debug] pool:0x15c3110, del timer:0x15c3278
2018/08/27 20:17:50 +826 [debug] pool:0x15c3110, del timer:0x15c32c8
2018/08/27 20:17:50 +826 [debug] pool:0x15c3110, up timer:0x15c32c8
2018/08/27 20:17:56 +826 [debug] del timer:0x15c32c8
2018/08/27 20:17:56 +826 [info] last disp sess:23417
2018/08/27 20:17:56 +826 [debug] sess post disp:23417
2018/08/27 20:17:56 +826 [notice] pool occupy:2048
2018/08/27 20:18:02 +931 [debug] del timer:0x15ba1c8

**Comment by lazio579** [comment]
经过分析是用了tls/ssl方式来访问mysql导致的。
