### ISSUE TITLE
阿里云环境下的tcpcopy环境部署参考

### ISSUE THREAD

**Issue by lazio579** [session-replay-tools/tcpcopy#336]
云环境下，安全策略可能会干扰测试的进行。
采用如下步骤可以规避麻烦：
1、测试机器和intercept部署到一台机器
2、tcpcopy端-c参数采用tcpcopy所在的线上机器ip地址
3、在线上机器设置iptables黑洞来过滤掉测试服务器的响应包
     iptables -A INPUT -p tcp --sport 测试服务的端口 -j DROP -s 测试服务所在机器的ip地址
4、千万要注意在测试服务器不要设置路由了，否则会受到干扰

**Comment by wubo0067** [comment]
请教：“iptables -I INPUT -p tcp --sport 测试服务的端口 -j DROP -s 测试服务所在机器的ip地址” 这做了这个3次握手怎么能成功呢？难道tcpcopy复制的包到test不需要三次握手吗？

**Comment by wangbin579** [comment]
对于test服务器，当然需要三次握手
tcpcopy只做了服务器一侧的tcp交互，而真正的客户端这一侧则没有tcp交互

**Comment by IterableTrucks** [comment]
Thanks, it works well on Aliyun ECS.

**Comment by dumbdonkey** [comment]
> 对于test服务器，当然需要三次握手
> tcpcopy只做了服务器一侧的tcp交互，而真正的客户端这一侧则没有tcp交互

没看懂，能在详细解释下吗? 谢谢

**Comment by unlockingc** [comment]
他这个应该是intercept通过将tcp header内容发送给tcpcopy，tcpcopy的服务器可以劫持客户端，欺骗test server，让他误以为握手成功了。

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。
