### ISSUE TITLE
many connections can't be established

### ISSUE THREAD

**Issue by JeromeLiuLly** [session-replay-tools/tcpcopy#338]
一下是使用v1.0.0版本的离线方案
生产服务器：10.200.102.110
测试服务器：10.200.102.111
辅助服务器：10.200.102.99
以上的防火墙均关闭，辅助服务器的ip_forward 为 0；
tcpcopy日志
![image](https://user-images.githubusercontent.com/6087162/46857028-8a637900-ce3a-11e8-8588-bc9d7752c65a.png)

测试服务器tcpdump日志
![image](https://user-images.githubusercontent.com/6087162/46857072-ad8e2880-ce3a-11e8-82e6-bdd12c5a074b.png)

辅助服务器
![image](https://user-images.githubusercontent.com/6087162/46857238-0fe72900-ce3b-11e8-8bdf-aaca6a96ddbd.png)

一直出现测试服务器能够查到IP日志，但是，在业务系统服务为看到日志进入。

**Comment by lazio579** [comment]
路由没有生效，导致响应包都回到了真正的客户端。
如果路由不允许设置，那就参考：
https://github.com/session-replay-tools/tcpcopy/issues/336

**Comment by JeromeLiuLly** [comment]
大大你好：
         我这边是测试服务器。配置路由并无问题。先出现的情况，就是握手失败。再次说明下服务器情况。
以下是使用v1.0.0版本的离线方案
生产服务器：10.200.102.33
测试服务器：10.200.102.89
辅助服务器：10.200.102.89
以上的防火墙均关闭，辅助服务器的ip_forward 为 0；

tcplog日志信息
![image](https://user-images.githubusercontent.com/6087162/47628078-c0a93400-db6e-11e8-81d6-7273a9f13916.png)

生产服务器抓包日志：
![image](https://user-images.githubusercontent.com/6087162/47628104-e5051080-db6e-11e8-8ca1-ba0e369d85af.png)

测试服务器抓包日志：
![image](https://user-images.githubusercontent.com/6087162/47628189-4a590180-db6f-11e8-9bc2-f1158e98ec15.png)

测试服务器配置了路由规则（尝试过删除路由规则也无效）
![image](https://user-images.githubusercontent.com/6087162/47628194-50e77900-db6f-11e8-864c-96b39b4b3068.png)

**Comment by wangbin579** [comment]
现在这个问题跟之前的问题不是一个问题了，因为测试服务器和辅助服务器都是同一台机器了。
从测试服务器抓包来看，并没有抓到第二次握手数据包，可以利用netstat来看看是否有相应的tcp状态（SYNC_RECV），如果没有，则在ip层入向被干掉了，并没有到达tcp层。

还是参考
https://github.com/session-replay-tools/tcpcopy/issues/336
来做，利用tcpcopy的-c参数设置成线上服务器的ip地址，使其通过测试服务器的ip层，到达tcp层面。

**Comment by Silocean** [comment]
> 路由没有生效，导致响应包都回到了真正的客户端。
> 如果路由不允许设置，那就参考：
> #336

王工你好！昨天复制流量的时候同样遇到“many connections can't be established”这个问题，也的确是路由设置没有生效，根据您在[#336](https://github.com/session-replay-tools/tcpcopy/issues/336)中的提示也的确解决了问题。
但是把流量打回线上机然后过滤掉总觉得有些不放心。
所以请教王工，这个问题还有没有其他解决方法？

**Comment by wangbin579** [comment]
参考 https://github.com/session-replay-tools/tcpcopy/issues/279
