### ISSUE TITLE
复制线上流量模式，启动不起来

### ISSUE THREAD

**Issue by Silocean** [session-replay-tools/tcpcopy#339]
命令：/opt/tcpcopy/sbin/tcpcopy -x 9201-10.153.179.193:9201 -s 10.153.179.192 -c 10.153.1.254  

tcpcopy日志：
![image](https://user-images.githubusercontent.com/6680721/47772454-bda27500-dd21-11e8-9223-dd8fa8d88766.png)

请问这是什么问题？

之前使用没有问题，换成另一台线上服务器导流后，就启动不起来了，日志中提示这个错误。

**Comment by lazio579** [comment]
可能是MTU不匹配，发送网卡MTU小于1500，利用tcpcopy的-M参数来匹配传输MTU
-M <num>       MTU value sent to backend (default 1500)

**Comment by Silocean** [comment]
> 可能是MTU不匹配，发送网卡MTU小于1500，利用tcpcopy的-M参数来匹配传输MTU
> -M MTU value sent to backend (default 1500)

感谢王工回复！
确实是这个问题，缩小MTU参数后就没有问题了。
