### ISSUE TITLE
急切的需要支持cpu3.0及以上的tcpcopy的升级版

### ISSUE THREAD

**Issue by xiaoxiaojuan** [session-replay-tools/tcpcopy#340]
你好，Bin

我们目前在大量的使用tcpcopy，但是由于我们的服务器升级，cpu从2.0升级到了3.0，导致我们无法使用tcpcopy，我们流量比较复杂线下模拟各种情况比较难，所以急切的需要继续从线上引流下来。

非常期待和希望您能升级tcpcopy，支持cpu3.0及以上的版本

非常感谢

**Comment by wangbin579** [comment]
为啥不能使用tcpcopy呢？

**Comment by xiaoxiaojuan** [comment]
在我们cpu3.0的机器上，tcpcopy无法使用，这个怎么解决呢？

**Comment by wangbin579** [comment]
为啥无法使用，需要个原因吧，有tcpcopy的log吗？

**Comment by xiaoxiaojuan** [comment]
1. 机器内核：3.10.0_3-0-0-18               2. tcpcopy0.9.10版本，在执行./configure时，出现如下错误：
checking for linux/version.h...yes
enable nfqueue
checking for nfqueue directory... configure:error:nfqueue requeired. Install libnetfilter_queue(donwload it from http://www.netfilter.org/projects/libnetfilter_queue/index.html) or specify its path using
---with-nfqueue=/dir/
  3. 下载了指定文件：libnetfilter_queue-1.0.3和libnfnetlink-1.0.1         在安装和指定时失败

**Comment by xiaoxiaojuan** [comment]
@wangbin579 wang麻烦您再看看，需要什么日志

**Comment by wangbin579** [comment]
你的版本太老了，1.0版本默认早就放弃netfilter了

**Comment by xiaoxiaojuan** [comment]
太尴尬了😅。谢谢～～～～
