### ISSUE TITLE
请问支持在应用服务器上复制到数据库的流量吗？

### ISSUE THREAD

**Issue by somanybut** [session-replay-tools/tcpcopy#341]
由于无法在数据库服务器上运行tcpcopy，现在想在应用服务器上运行tcpcopy复制到数据库的流量，如：192.168.1.2为数据库服务器，端口为3307，192.168.2.2为应用服务器，现在能用tcpcopy在192.168.2.2上复制/回放192.168.1.2:3307的流量吗？

**Comment by wangbin579** [comment]
可以，但需要采用如下方法：
configure需要加上--pcap-capture，也即pcap来抓出去的数据包（默认ip raw socket抓包已经行不通），运行的时候需要加上-i 网卡设备（比如-i eth0）和-F参数（比如 -F 'tcp and dst port 3307'，其它都一样。
