### ISSUE TITLE
对于TCP1.2.0，configure的时候是否必须显式指定--enable-advanced

### ISSUE THREAD

**Issue by xingfeng1234** [session-replay-tools/tcpcopy#342]
对于TCP1.2.0，configure的时候是否必须显式指定--enable-advanced，如果需要显示指定，执行./configure --enable-advanced报如下错误：
./configure: error: invalid option "--enable-advanced"
@wangbin579 @lazio579 请老师帮忙指点一二。

**Comment by wangbin579** [comment]
./configure --help 可以查看支持不支持，tcpcopy已经去除了这个选项了
