### ISSUE TITLE
mac OS机器上作为测试服务器不起作用

### ISSUE THREAD

**Issue by mrproliu** [session-replay-tools/tcpcopy#346]
目前有三台服务器，tcpcopy和interceptor在同一个网段中，test server在另外的网段。
tcpcopy: 10.1.201.128
interceptor: 10.1.200.8
test server: 10.71.11.50

tcpcopy命令：
tcpcopy -x 21250-10.71.11.50:30880 -s 10.1.200.8 -c 100.100.100.100 -d -n 1
interceptor命令：
intercept -i eth0 -F tcp and src port 30880 -d
test server：
sudo route -n add -net 100.100.100.100 -netmask 255.255.255.0  10.1.200.8
并且使用go启动30880端口。
在test server中已经关闭防火墙。
![image](https://user-images.githubusercontent.com/3417650/54682134-0cbe3a80-4b49-11e9-907e-0c3872a89272.png)

向tcpcopy服务器的21250机器发送tcp消息，在test server中使用wireshark抓包如下：
![image](https://user-images.githubusercontent.com/3417650/54682044-d41e6100-4b48-11e9-8f3c-1543f73ee758.png)

**Comment by wangbin579** [comment]
test server跟intercept不在一个网段，设置路由一般没用的。
建议参考来搭建：
https://github.com/session-replay-tools/tcpcopy/issues/336

**Comment by wangbin579** [comment]
不好意思，mac os无法运行intercept的情况下，可以采用如下步骤：

1、在10.1.201.128，也即tcpcopy机器上运行intercept
    ./intercept -i eth0 -F 'tcp and src port 30880 and src host 10.71.11.50'  -d

   并设置iptables命令来干掉测试服务器返回的响应包：
  iptables -I INPUT -p tcp --sport 30880  -j DROP -s 10.71.11.50

2、tcpcopy端-c参数采用tcpcopy所在的线上机器ip地址
    tcpcopy -x 21250-10.71.11.50:30880 -s 10.1.201.128 -c 10.1.201.128 -d -n 1
    目的是利用tcpcopy的机器ip地址去访问测试机器，然后响应会回到tcpcopy机器，从而被intercept捕获，被iptables干掉。

3、测试服务器不要设置路由信息

**Comment by mliu111477** [comment]
感谢您的及时回复！

这样测试是可以的，但是我们还有一个小问题。
我们希望test server是一个集群的模式，意思就是oneline server同样是一台，现在有两种方案，不清楚哪个在tcp copy层面是可实现的？
1. tcpcopy 指定多个发送目标地址，轮训去发送。
2. 在test server前增加一个类似于nginx的反向代理服务器，让nginx来进行处理负载机制。

**Comment by wangbin579** [comment]
test server前面可以加上lvs如果能够有lvs的话或者nginx反向代理

**Comment by mliu111477** [comment]
但是有一个问题就是、就是不知道为什么没有到达test server？
在nginx上是否需要增加router或者iptables？

**Comment by wangbin579** [comment]
如果是lvs，可以参考：
https://blog.csdn.net/wangbin579/article/details/8612952

**Comment by wangbin579** [comment]
为什么没有达到test server，可以参考：


https://github.com/session-replay-tools/tcpcopy/issues/173 新架构部分
