### ISSUE TITLE
测试服务器没有收到流量

### ISSUE THREAD

**Issue by hlf426** [session-replay-tools/tcpcopy#349]
网上这个HTTP的例子是可以复制转发成功的：https://www.cnblogs.com/phennry/p/6382755.html?utm_source=itdadao&utm_medium=referral 

但是另外一个应用在相同的机器上没有成功，看日志复制流量成功了，但是测试服务器上没有收到流量，请大拿帮忙看下:

这是在线服务器上面打出来的日志：
2019/06/04 11:21:40 +540 [notice] user time used:17
2019/06/04 11:21:40 +540 [notice] sys  time used:17
2019/06/04 11:21:40 +540 [notice] max memory size:6120
2019/06/04 11:21:40 +540 [notice] Total allocated space (bytes): 1585632
2019/06/04 11:21:40 +540 [notice] Total free space (bytes): 355872
2019/06/04 11:21:40 +540 [notice] Top-most, releasable space (bytes): 57536
2019/06/04 11:21:40 +546 [notice] active:164,rel:655,obs del:1,tw:0
2019/06/04 11:21:40 +546 [notice] conns:846,resp:38237,c-resp:30257
2019/06/04 11:21:40 +546 [notice] resp fin:681,resp rst:0
2019/06/04 11:21:40 +546 [notice] send:62873,send content:30708
2019/06/04 11:21:40 +546 [notice] send syn:846, fin:654,reset:28
2019/06/04 11:21:40 +546 [notice] reconnect:27,for no syn:163
2019/06/04 11:21:40 +546 [notice] retransmit:1
2019/06/04 11:21:40 +546 [notice] recv packs after retransmission:1
2019/06/04 11:21:40 +546 [notice] syn cnt:328,all clt:16669,clt cont:15305
2019/06/04 11:21:40 +546 [notice] total cont retransmit:0, frag:0
2019/06/04 11:21:40 +546 [notice] total captured packets:868769

这是是辅助服务器的日志：
019/06/04 11:22:18 +087 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41195,len 161,seq=3517390476,ack=574661991
2019/06/04 11:22:18 +147 [notice] fd is null after session is created
2019/06/04 11:22:18 +147 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41194,len 238,seq=712618003,ack=867652883
2019/06/04 11:22:19 +580 [notice] fd is null after session is created
2019/06/04 11:22:19 +580 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41204,len 52,seq=1495401629,ack=2396521257
2019/06/04 11:22:19 +580 [notice] fd is null after session is created
2019/06/04 11:22:19 +580 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41204,len 161,seq=1495401629,ack=2396521257
2019/06/04 11:22:19 +672 [notice] fd is null after session is created
2019/06/04 11:22:19 +672 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41206,len 161,seq=1751011503,ack=2639287948
2019/06/04 11:22:20 +134 [notice] fd is null after session is created
2019/06/04 11:22:20 +134 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41211,len 161,seq=1530125983,ack=2624928402
2019/06/04 11:22:20 +146 [notice] fd is null after session is created
2019/06/04 11:22:20 +146 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41212,len 161,seq=2168002080,ack=3324786476
2019/06/04 11:22:30 +854 [notice] total resp packs:42225, all:42225, route:1032, sock write cnt:37275
2019/06/04 11:22:30 +854 [notice] cache hit:38953,missed:805,lost:2467
2019/06/04 11:22:30 +854 [notice] search:42225,extra compared:1306,all sessions:1032
2019/06/04 11:22:34 +897 [notice] fd is null after session is created
2019/06/04 11:22:34 +897 [notice] from bak:10.137.67.19:8000-->11.165.108.201:34635,len 156,seq=4081309797,ack=4134033134
2019/06/04 11:22:35 +130 [notice] fd is null after session is created
2019/06/04 11:22:35 +130 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41194,len 217,seq=712618189,ack=867652883
2019/06/04 11:22:35 +161 [notice] fd is null after session is created
2019/06/04 11:22:35 +161 [notice] from bak:10.137.84.33:8000-->11.165.108.201:41195,len 217,seq=3517390585,ack=574661991

**Comment by wangbin579** [comment]
从log来看，测试服务器收到流量了，信息不准，无法判断

**Comment by wangbin579** [comment]
测试服务器有没有收到流量，请用tcpdump来确认

**Comment by hlf426** [comment]
通过测试服务器的端口，利用tcpdump查看复制的流量确实打到测试服务器上，也到达了指定端口
01:22:48.055856 IP 11.165.108.1.65241 > mq-amqp-daily-02.et2sqa.irdmi: Flags [.], ack 1, win 8268, options [nop,nop,TS val 411680603 ecr 1198460370], length 0
01:22:48.055858 IP 11.165.108.1.65241 > mq-amqp-daily-02.et2sqa.irdmi: Flags [P.], seq 1:241, ack 1, win 8268, options [nop,nop,TS val 411680604 ecr 1198460370], length 240

11.165.108.1是伪造IP，这个IP没有跟测试服务器建立连接，从该IP过来到达测试服务器的请求，测试服务器的应用会处理么？

**Comment by wangbin579** [comment]
没有看到，不代表没有建立连接，要是没有建立连接，测试服务器TCP早就发送reset数据包了

**Comment by hlf426** [comment]
之前没有看到流量是因为复制的端口号错了，现在有流量了，下面是线上机器，出口流量（复制流量）明显比入口流量（真是流量）少很多，这个怎么排查呢?
![image](https://user-images.githubusercontent.com/6219731/59170664-457f1600-8b72-11e9-94b3-ad6d54252478.png)

**Comment by wangbin579** [comment]
首先得看线上流量，tcpcopy每隔一段时间会统计抓包情况，如果线上数据包很多，tcpcopy忙于抓包，效率就会下降，这时就应该采用其它方式，比如采用交换机镜像的方式并把流量分而治之；其次，得看测试服务器接收程度，这种可以抓包分析来分析原因，例如判断是网络延迟还是应用访问被拒绝导致

**Comment by chaoyongzhou** [comment]
我也遇到同样的问题，测试机tcpdump能抓到包，辅助机也能抓到包，在线机（tcpcopy）和辅助机之间通信正常，但是tcpcopy没有发送ack给测试机。这是为何？

**Comment by BruceLuo33** [comment]
> 我也遇到同样的问题，测试机tcpdump能抓到包，辅助机也能抓到包，在线机（tcpcopy）和辅助机之间通信正常，但是tcpcopy没有发送ack给测试机。这是为何？

请问你这个问题解决了吗？谢谢
