### ISSUE TITLE
tcpcopy stop to send packet to test server when recieve ack without content

### ISSUE THREAD

**Issue by MoZhonghua** [session-replay-tools/tcpcopy#350]
I tried to use tcpcopy to copy a gRPC stream to my test server. I found when my gRPC test server send ack packets without content, tcpcopy gets this ack from intercept but fails to process it and send new packets to test server.

This is debug log of tcpcopy:  [bad.log](https://github.com/session-replay-tools/tcpcopy/files/3353128/bad.log). 
I add a payload field which is the payload length of tcp packet to trace log. Whenever tcpcopy gets stuck, the last ack packet from test server has no payload.

I suspect this issue is related to a check statement in proc_bak_pack():

https://github.com/session-replay-tools/tcpcopy/blob/939d7d58a582885928e51044e4f2f29bb7b88748/src/tcpcopy/tc_session.c#L1484

If I disable this check(i.e, make it always return true), then tcpcopy will not get stuck.

**Comment by wangbin579** [comment]
![图片](https://user-images.githubusercontent.com/1127759/60576905-fbf7a480-9d86-11e9-83e8-556e8d945132.png)

Too many retransmission.
Check ip_forward on the assistant server or run intercept on the test server.

If tcpcopy still gets stuck， use tcpcopy '-W' parameter.

**Comment by wangbin579** [comment]
You could also configure intercept like this:
./configure --disable-combined

**Comment by MoZhonghua** [comment]
run intercept on the test server fix my problem. thanks a lot.

Why retransmissions cause tcpcopy get stuck? tcpcopy DID recieve ack from intercept  and should send more data.
