### ISSUE TITLE
tcpcopy异常退出

### ISSUE THREAD

**Issue by qq1033731787** [session-replay-tools/tcpcopy#354]
hi 流量较大时tcpcopy出现了异常退出 请问下是什么原因呢？
[warn] bak lost packs:36754,same ack:8
2019/07/31 15:17:13 +095 [warn] omit retransmit:36754
2019/07/31 15:17:13 +095 [warn] bak lost packs:36754,same ack:9
2019/07/31 15:17:13 +095 [warn] omit retransmit:36754
2019/07/31 15:17:13 +095 [warn] bak lost packs:36754,same ack:10
2019/07/31 15:17:13 +095 [warn] omit retransmit:36754
2019/07/31 15:17:13 +095 [warn] bak lost packs:36754,same ack:11
2019/07/31 15:17:13 +095 [warn] omit retransmit:36754
2019/07/31 15:17:13 +095 [warn] bak lost packs:36754,same ack:12
2019/07/31 15:17:13 +095 [warn] omit retransmit:36754
2019/07/31 15:17:13 +095 [warn] bak lost packs:36754,same ack:13
2019/07/31 15:17:13 +095 [warn] omit retransmit:36754
2019/07/31 15:17:13 +125 [notice] active:293,rel reqs:51,obs del:0
2019/07/31 15:17:13 +125 [notice] conns:57,resp packs:10891,c-resp packs:0
2019/07/31 15:17:13 +125 [notice] send Packets:16740,send content packets:16266
2019/07/31 15:17:13 +125 [notice] send fin Packets:0,send reset packets:38
2019/07/31 15:17:13 +125 [notice] reconnect for closed :0,for no syn:339
2019/07/31 15:17:13 +125 [notice] retransmit:2
2019/07/31 15:17:13 +125 [notice] successful retransmit:0
2019/07/31 15:17:13 +125 [notice] syn cnt:5,all clt packs:171395,clt cont:169731
2019/07/31 15:17:13 +125 [notice] total client content retransmit:6
2019/07/31 15:17:13 +125 [notice] total captured pakcets:171395
2019/07/31 15:17:13 +125 [notice] no responses after 5 secends
2019/07/31 15:17:13 +125 [warn] many connections can't be established
2019/07/31 15:17:13 +125 [notice] session size:293
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:2458,p:13312
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:2678,p:64512
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:2217,p:60674
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:3763,p:63234
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:4029,p:46852
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:3616,p:32774
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:3536,p:26632
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:4670,p:32012
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:2468,p:40460
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:4757,p:49932
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:4462,p:61452
2019/07/31 15:17:13 +125 [warn] unsend:candidate erased:4030,p:14862
。。。
[notice] activate_dead_sessions
然后就退出了

**Comment by wangbin579** [comment]
这是因为操作系统提供给tcpcopy的接口出现了丢包。
建议先利用交换机镜像的方式把请求数据包镜像给测试系统，然后在测试系统运行tcpcopy捕获请求。

**Comment by qq1033731787** [comment]
嗯嗯 感谢回复 但是交换机镜像这个很难实现呀

---原始邮件---
发件人: "Bin Wang"<notifications@github.com>
发送时间: 2019年8月12日(星期一) 中午11:27
收件人: "session-replay-tools/tcpcopy"<tcpcopy@noreply.github.com>;
抄送: "qq1033731787"<1033731787@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [session-replay-tools/tcpcopy] tcpcopy异常退出 (#354)



这是因为操作系统提供给tcpcopy的接口出现了丢包。
 建议先利用交换机镜像的方式把请求数据包镜像给测试系统，然后在测试系统运行tcpcopy捕获请求。

**Comment by qq1033731787** [comment]
大佬，交换机镜像这种方式岂不是很不灵活。怎么去确定哪些路由器该镜像呢，需要全量镜像吗？而且交换机镜像的话每个交换机都要空余一个物理端口出来，感觉很难维护啊。请问你们现在有在使用交换机镜像的方式吗？
