### ISSUE TITLE
tcpcopy是否支持修改http头

### ISSUE THREAD

**Issue by chaorongguo** [session-replay-tools/tcpcopy#355]
线上机器tcpdump 下来的包头：
psÞo]Ñ^ØPOST /ocr HTTP/1.0^M
Host: lineocrser3^M
Connection: close^M
Content-Length: 79259^M

离线模式下，将Host替换成在线机器的ip，则离线回放成功
在线回放模式， 通过执行-H 在线机器的ip， 或者-x 指定 在线机器ip：端口 -测试机器ip ：端口 都不行

**Comment by wangbin579** [comment]
可以通过代理去修改，tcpcopy本身不修改应用层数据

**Comment by chaorongguo** [comment]
咱们提供内置的http代理修改模块吗，如果我想在线tcpcopy导流的话， 应该怎么做？
这种Host 对不上的场景，应该挺多的？






在 2019-08-12 11:24:50，"Bin Wang" <notifications@github.com> 写道：


可以通过代理去修改，tcpcopy本身不修改应用层数据

**Comment by wangbin579** [comment]
通过类似nginx web服务器代理，就可以修改数据

**Comment by chaorongguo** [comment]
好的，谢谢
