### ISSUE TITLE
能否支持流量倍数小于 1，以实现部分流量的复制

### ISSUE THREAD

**Issue by zhenbianshu** [session-replay-tools/tcpcopy#357]
使用 tcpcopy 导入线上流量进行压测时，发现设置流量倍数很难达到服务的瓶颈，一倍流量太少，两倍流量又会太大导致服务崩溃。

**Comment by wangbin579** [comment]
可以的，tcpcopy运行参数就有

**Comment by zhenbianshu** [comment]
非常感谢，是我看文档不仔细了，  -r 参数可以实现。
