### ISSUE TITLE
tcpcopy线上业务测试问题请教

### ISSUE THREAD

**Issue by slyforever2004** [session-replay-tools/tcpcopy#359]
1、测试用的服务器是否需要一整套，例如线上架构是nginx+tomcat+数据库，复制线上Nginx的流量到测试环境，那么测试环境的nginx后端是否也需要tomcat和数据库
2、针对双网卡Nginx流量复制，请求从外网网卡进来，通过内网网卡复制到测试Nginx，路由应该如何设置呢，伪装的IP是随意吗，还是有什么要求，目前看数据是抓到了，卡在三次握手，测试服务器上全是syn_recv的半连接。
另外每台服务器上已经有172.30.145.0 和122.223.184.0的两条路由了，不知道这个有没影响。
架构如下：
online:122.223.184.22/172.30.145.21
test:122.223.184.29/172.30.145.26
assistent:122.223.184.33/172.30.145.35
online:./tcpcopy -x 80-172.30.145.26:8089 -s 172.30.145.35 -c 172.30.145.x -d
test: route add -net 172.30.145.x netmask 255.255.255.0 gw 172.30.145.35

**Comment by wangbin579** [comment]
1、必须一整套，跟是否采用tcpcopy没有关系，这是测试的基本要求
2、最好不要设置 172.30.145.x，毕竟这包括各台机器的ip地址，设置路由比较麻烦，尝试换其它网段ip，以方便设置路由
