### ISSUE TITLE
tcpcopy grpc丢包导致 后续转发或回放中断

### ISSUE THREAD

**Issue by DongtianA** [session-replay-tools/tcpcopy#361]
如果grpc请求出现丢包的情况，后面的回放或者转发就会停止，这个问题怎么解决呢？或者可以定制开发吗？

**Comment by wangbin579** [comment]
要么利用pfring等类似机制来减少丢包可能性，要么二次开发（保存登入过程进行连接登入回放）

**Comment by DongtianA** [comment]
如果是二次开发，要怎么弄呢？大概需要多久？
