### ISSUE TITLE
关于交换机镜像问题的请教

### ISSUE THREAD

**Issue by qq1033731787** [session-replay-tools/tcpcopy#363]
大佬，交换机镜像这种方式岂不是很不灵活。怎么去确定哪些路由器该镜像呢，需要全量镜像吗？而且交换机镜像的话每个交换机都要空余一个物理端口出来，感觉很难维护啊。请问你们现在有在使用交换机镜像的方式吗？

**Comment by wangbin579** [comment]
有好几个用户使用交换机镜像的，好处是可以支持大规模流量测试，而且测试独立，不需要打扰项目运维人员了

**Comment by qq1033731787** [comment]
大佬能帮忙介绍下吗 据我了解交换机很不灵活啊。
1.难以确定哪些端口开启镜像
2.交换机需要空出一个端口
大规模部署的话 这些问题是怎么解决的呢 😢
