### ISSUE TITLE
离线回放tcp包失败

### ISSUE THREAD

**Issue by sea520-coder** [session-replay-tools/tcpcopy#367]
target server: 192.168.237.128
intercept server: 192.168.237.128
tcpcopy -x 10008-192.168.237.128 -s 192.168.237.128 -c 192.168.222.1 -i 1.pcap -l tcpcopy.log
intercept -i ens33 -F tcp and src port 10008 -d -l intercept.log

tcpcopy.log
2019/11/14 19:29:05 +074 [notice] open pcap success:1.pcap
  25 2019/11/14 19:29:05 +074 [notice] send the first packets here
  26 2019/11/14 19:29:05 +074 [info] pl:18639056, p:61291
  27 2019/11/14 19:29:05 +074 [debug] pool:0x11c68d0, add timer:0x11c6a48
  28 2019/11/14 19:29:05 +074 [info] nev:18639408,p:61291
  29 2019/11/14 19:29:05 +074 [debug] pool:0x11c68d0, add timer:0x11c6a98
  30 2019/11/14 19:29:05 +074 [notice] session key:2055825550319, p:61291
  31 2019/11/14 19:29:05 +074 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 44,s     eq=394526882,ack=0
  32 2019/11/14 19:29:05 +074 [info] ln:18639720, pkt:18639648, save:394526882,p:61291
  33 2019/11/14 19:29:05 +074 [info] slide_win_packs size:1, p:61291
  34 2019/11/14 19:29:05 +074 [debug] proc clt pack:61291
  35 2019/11/14 19:29:05 +074 [debug] record rtt base:1573629847176,p:61291
  36 2019/11/14 19:29:05 +074 [debug] syn port:61291
  37 2019/11/14 19:29:05 +074 [debug] to bak:192.168.222.1:61291-->0.0.0.0:192,len 44,seq=394526882     ,ack=0
  38 2019/11/14 19:29:05 +074 [info] empty slide,p:61291
  39 2019/11/14 19:29:05 +074 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 40,s     eq=394526883,ack=748097948
  40 2019/11/14 19:29:05 +074 [info] ln:18639824, pkt:18639760, save:394526883,p:61291
  41 2019/11/14 19:29:05 +074 [info] rtt:0,p:61291
  42 2019/11/14 19:29:05 +074 [info] internal:61291
  43 2019/11/14 19:29:05 +074 [info] slide_win_packs size:2, p:61291
  44 2019/11/14 19:29:05 +074 [debug] proc clt pack:61291
  45 2019/11/14 19:29:05 +074 [debug] pool:0x11bd3d0, add timer:0x11bd590
  46 2019/11/14 19:29:05 +095 [debug] del timer:0x11bd578
  47 2019/11/14 19:29:05 +095 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 81,s     eq=394526883,ack=748097948
  48 2019/11/14 19:29:05 +095 [info] ln:18639968, pkt:18639864, save:394526883,p:61291
  49 2019/11/14 19:29:05 +095 [info] slide_win_packs size:3, p:61291
  50 2019/11/14 19:29:05 +095 [debug] proc clt pack:61291
  51 2019/11/14 19:29:05 +095 [debug] pool:0x11bd3d0, up timer:0x11bd578
  52 2019/11/14 19:29:05 +105 [debug] del timer:0x11bd578
  53 2019/11/14 19:29:05 +105 [debug] pool:0x11bd3d0, up timer:0x11bd578
  54 2019/11/14 19:29:05 +116 [debug] del timer:0x11bd578
  55 2019/11/14 19:29:05 +116 [debug] pool:0x11bd3d0, up timer:0x11bd578
  56 2019/11/14 19:29:05 +127 [debug] del timer:0x11bd578
  57 2019/11/14 19:29:05 +127 [debug] pool:0x11bd3d0, up timer:0x11bd578
  58 2019/11/14 19:29:05 +138 [debug] del timer:0x11bd578
  59 2019/11/14 19:29:05 +138 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 40,s     eq=394526924,ack=748097980
  60 2019/11/14 19:29:05 +138 [info] ln:18640168, pkt:18640008, save:394526924,p:61291
  61 2019/11/14 19:29:05 +138 [info] slide_win_packs size:4, p:61291
  62 2019/11/14 19:29:05 +138 [debug] proc clt pack:61291
  63 2019/11/14 19:29:05 +138 [debug] pool:0x11bd3d0, up timer:0x11bd578
  64 2019/11/14 19:29:05 +149 [debug] del timer:0x11bd578
  65 2019/11/14 19:29:05 +149 [debug] pool:0x11bd3d0, up timer:0x11bd578
  66 2019/11/14 19:29:05 +159 [debug] del timer:0x11bd578
  67 2019/11/14 19:29:05 +159 [debug] pool:0x11bd3d0, up timer:0x11bd578
  68 2019/11/14 19:29:05 +170 [debug] del timer:0x11bd578
  69 2019/11/14 19:29:05 +170 [debug] pool:0x11bd3d0, up timer:0x11bd578
  70 2019/11/14 19:29:05 +181 [debug] del timer:0x11bd578
  71 2019/11/14 19:29:05 +181 [debug] pool:0x11bd3d0, up timer:0x11bd578
  72 2019/11/14 19:29:05 +191 [debug] del timer:0x11bd578
  73 2019/11/14 19:29:05 +191 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 40,s     eq=394526924,ack=748097980
  74 2019/11/14 19:29:05 +191 [info] ln:18640272, pkt:18640208, save:394526924,p:61291
  75 2019/11/14 19:29:05 +191 [info] slide_win_packs size:5, p:61291
  76 2019/11/14 19:29:05 +191 [debug] proc clt pack:61291
  77 2019/11/14 19:29:05 +191 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 56,s     eq=394526924,ack=748097980
  78 2019/11/14 19:29:05 +191 [info] ln:18640392, pkt:18640312, save:394526924,p:61291
  79 2019/11/14 19:29:05 +191 [info] slide_win_packs size:6, p:61291
  80 2019/11/14 19:29:05 +191 [debug] proc clt pack:61291
  81 2019/11/14 19:29:05 +191 [debug] pool:0x11bd3d0, up timer:0x11bd578
  82 2019/11/14 19:29:05 +202 [debug] del timer:0x11bd578
  83 2019/11/14 19:29:05 +202 [debug] pool:0x11bd3d0, up timer:0x11bd578
  84 2019/11/14 19:29:05 +213 [debug] del timer:0x11bd578
  85 2019/11/14 19:29:05 +213 [debug] recv clt:192.168.222.1:61291-->192.168.237.128:10008,len 42,s     eq=394526940,ack=748097980
  86 2019/11/14 19:29:05 +213 [info] ln:18640496, pkt:18640432, save:394526940,p:61291
  87 2019/11/14 19:29:05 +213 [info] slide_win_packs size:7, p:61291
  88 2019/11/14 19:29:05 +213 [debug] proc clt pack:61291
  89 2019/11/14 19:29:05 +213 [debug] pool:0x11bd3d0, up timer:0x11bd578
  90 2019/11/14 19:29:05 +224 [debug] del timer:0x11bd578
intercept.log:
2019/11/14 19:31:57 +092 [notice] fd is null after session is created
  498 2019/11/14 19:31:57 +092 [notice] from bak:192.168.237.1:60754-->192.168.237.128:22,len 348,s      eq=4009744523,ack=3973581058
  499 2019/11/14 19:31:57 +092 [notice] fd is null after session is created
  500 2019/11/14 19:31:57 +092 [notice] from bak:192.168.237.128:22-->192.168.237.1:60754,len 180,s      eq=3973581058,ack=4009744831
  501 2019/11/14 19:31:57 +094 [debug] del timer:33408176
  502 2019/11/14 19:31:57 +094 [debug] update timer:33408176
  503 2019/11/14 19:31:57 +097 [debug] del timer:33408176
  504 2019/11/14 19:31:57 +097 [debug] update timer:33408176
  505 2019/11/14 19:31:57 +101 [debug] del timer:33408176
  506 2019/11/14 19:31:57 +101 [debug] update timer:33408176
  507 2019/11/14 19:31:57 +104 [debug] del timer:33408176
  508 2019/11/14 19:31:57 +104 [debug] update timer:33408176
  509 2019/11/14 19:31:57 +106 [debug] del timer:33408176
  510 2019/11/14 19:31:57 +106 [debug] update timer:33408176
  511 2019/11/14 19:31:57 +109 [debug] del timer:33408176
  512 2019/11/14 19:31:57 +109 [debug] update timer:33408176
  513 2019/11/14 19:31:57 +112 [debug] del timer:33408176
  514 2019/11/14 19:31:57 +112 [debug] update timer:33408176
  515 2019/11/14 19:31:57 +114 [debug] del timer:33408176
  516 2019/11/14 19:31:57 +114 [debug] update timer:33408176
  517 2019/11/14 19:31:57 +117 [debug] del timer:33408176
  518 2019/11/14 19:31:57 +117 [debug] update timer:33408176
  519 2019/11/14 19:31:57 +120 [debug] del timer:33408176
  520 2019/11/14 19:31:57 +120 [debug] update timer:33408176
  521 2019/11/14 19:31:57 +123 [debug] del timer:33408176
  522 2019/11/14 19:31:57 +123 [debug] update timer:33408176
  523 2019/11/14 19:31:57 +126 [debug] del timer:33408176
  524 2019/11/14 19:31:57 +126 [debug] update timer:33408176
  525 2019/11/14 19:31:57 +129 [debug] del timer:33408176
  526 2019/11/14 19:31:57 +129 [debug] update timer:33408176
  527 2019/11/14 19:31:57 +132 [debug] del timer:33408176
  528 2019/11/14 19:31:57 +132 [debug] update timer:33408176
  529 2019/11/14 19:31:57 +133 [notice] fd is null after session is created
  530 2019/11/14 19:31:57 +133 [notice] from bak:192.168.237.1:60754-->192.168.237.128:22,len 40,se      q=4009744831,ack=3973581198

请教下是哪里的问题？是路由设置不对吗，还是？
tcpdump没抓到包

**Comment by wangbin579** [comment]
命令要严格参考文档
