### ISSUE TITLE
TCPCOPY能做wordpress 这种的流量回放吗【这种有鉴权的系统】？

### ISSUE THREAD

**Issue by jim-zong** [session-replay-tools/tcpcopy#373]
大佬，向您请教一个问题
                   TCPCOPY能做wordpress 这种的流量回放吗【这种有鉴权的系统】？我做了这个实验，我安装了两个wordpress，用tcpdump收集了需要回放的数据，在这个过程种，编辑了一篇文章，然后我又去另外一个wordpress去回放，发现编辑的这种请求都302 或者403。我这样做的实验，是否正确？

**Comment by wangbin579** [comment]
如果因为权限问题不能回放，那得在测试系统放开权限，否则就得做类似MySQL回放的二次开发

**Comment by jim-zong** [comment]
能否实现复制流量压测、支持写接口、 支持各种中间件流量、测试回归这些功能？目前我们公司的用的，中间件列表： ZOOKEEPER REDIS  MONGODB Kafka  RPC框架：dubbo 、Spring Cloud  ，我们公司的业务是做CRM系统的，请问一下您，这种情况下,TCPCOPY适用吗？

**Comment by jim-zong** [comment]
求指点，哈哈
