### ISSUE TITLE
看实现转发的 ip 报文，长连接可以使用吗？感觉不行，有啥办法解决吗

### ISSUE THREAD

**Issue by zhisrc** [session-replay-tools/tcpcopy#374]

**Comment by wangbin579** [comment]
无状态的长连接是可以长久运行的；有状态的，如果连接被异常中断，就难以恢复，除非二次开发，例如mysql长连接复制

**Comment by zhisrc** [comment]
嗯嗯  昨天搭了环境应该是可以的。我们是长连接服务，最开始是怕没有捕获到 SYN 包，发给被测试服务器会失败。现在来看担心应该是多余的吧

**Comment by zhisrc** [comment]
> 无状态的长连接是可以长久运行的；有状态的，如果连接被异常中断，就难以恢复，除非二次开发，例如mysql长连接复制

**Comment by zhisrc** [comment]
> 无状态的长连接是可以长久运行的；有状态的，如果连接被异常中断，就难以恢复，除非二次开发，例如mysql长连接复制

嗯嗯  昨天搭了环境应该是可以的。我们是长连接服务，最开始是怕没有捕获到 SYN 包，发给被测试服务器会失败。现在来看担心应该是多余的吧

**Comment by zhisrc** [comment]
请教下:  tcpcopy启动的时候，会connect intercept  server，看着会处理 syn,rst 包，甚至会发这些包。有点不太明白为什么这样做。

**Comment by zhisrc** [comment]
应该是可以自动重新建链接的
