### ISSUE TITLE
HTTP长链接问题

### ISSUE THREAD

**Issue by yumao123** [session-replay-tools/tcpcopy#377]
您好
我们在利用tcpcopy+intercept这套系统做离线状态下的压测时，发现每次服务器返回响应后intercept都会主动发送FIN+ACK挥手，导致每次回放的请求都需要额外建立新的握手（这与预期不一致），导致压测结果偏离，请问怎么解决呢？

**Comment by wangbin579** [comment]
tcpcopy有超时机制，是不是被超时了，你可以查看tcpcopy的超时参数，设置大一点可能会解决你的问题

**Comment by wangbin579** [comment]
最好给个抓包数据，分析fin+ack是不是tcpcopy发送的
