### ISSUE TITLE
较大流量出现slide win: too many packs问题

### ISSUE THREAD

**Issue by strgrb** [session-replay-tools/tcpcopy#379]
我们有一个简单的client-server的程序，直接用的socket实现的。应用场景是dump到离线文件，然后再重发，有以下现象：
- 较小流量时（10Mbps左右）没有任何问题
- 较大流量时（100Mbps左右），出现了slide win：too many packs问题
dump的离线文件我们进行过下列验证：
- 我们已经编译了pfring中的tcpdump，并用这个进行dump
- 使用tcpflow将离线文件的流解析出来，得到的结果通过了一致性验证

对于tcpcopy程序的分析：
- 使用一个较小流量的dump文件，使用-a参数提高发送速度
- 观察到出现问题时，tcpcopy的cpu利用率峰值达到了100%

综上所述，我们这里怀疑是cpu使用率的问题，请问有什么建议吗？或者能否提供tcpcopy能够处理的流量

**Comment by wangbin579** [comment]
如果抓包文件没有丢包且流量很大的话，建议把抓包文件根据session拆分成多个文件，再利用多个tcpcopy实例来做。

btw，tcpcopy目前是单进程单线程的。
