### ISSUE TITLE
流量可以复制开始的一部分，但短时间后就只能复制少量，绝大部分无法成功复制

### ISSUE THREAD

**Issue by Grade-Two** [session-replay-tools/tcpcopy#382]
每次开始复制时可以成功复制开始的部分请求，但往后绝大部分请求都无法复制成功，但也会有零星几个请求被复制过去。
启动指令：
10.160.158.12(线上节点): ./tcpcopy -x 1111-9.181.212.142:1111 -s 9.181.212.172 -c 10.0.4.172 -p 36524 -l ${log_path}/port_36524_1111 -d
9.181.212.142(镜像节点): route add -net 10.0.4.0 netmask 255.255.255.0 gw 9.181.212.172
9.181.212.172(辅助节点): ./intercept -i bond1 -F 'tcp and src port 1111' -p 36524 -l ${log_path}/port_36524 -d

tcpcopy_log：
<img width="624" alt="截屏2020-12-22 下午4 07 21" src="https://user-images.githubusercontent.com/10093659/102865133-46d01500-4470-11eb-8e59-27f941d7911b.png">

intercept_log:
<img width="871" alt="截屏2020-12-22 下午4 11 42" src="https://user-images.githubusercontent.com/10093659/102865182-5fd8c600-4470-11eb-9f79-587fe39b1848.png">

线上节点抓包（前面正常，然后）:
<img width="1018" alt="截屏2020-12-22 下午4 14 26" src="https://user-images.githubusercontent.com/10093659/102865468-c1993000-4470-11eb-9809-6300df87be32.png">
镜像节点抓包（前面正常，然后）：
<img width="1025" alt="截屏2020-12-22 下午4 13 03" src="https://user-images.githubusercontent.com/10093659/102865325-90206480-4470-11eb-8965-9ea1b7e8c0db.png">

检查了线上节点的iptables，没有限制output：
<img width="663" alt="截屏2020-12-22 下午4 15 54" src="https://user-images.githubusercontent.com/10093659/102865594-f6a58280-4470-11eb-80ad-41506d4b0ebf.png">

请问大佬们，这是因为什么原因造成的？

**Comment by wangbin579** [comment]
应用是什么协议，可能不支持回放。

btw，需要看镜像节点单个session会话过程，才能准确分析

**Comment by Grade-Two** [comment]
我们用的thrift，全是短链接，每次请求都会建立tcp链接，然后释放。
镜像节点的session过程如下：
一开始的正常session：
<img width="1460" alt="截屏2020-12-23 上午10 08 32" src="https://user-images.githubusercontent.com/10093659/102950997-cdcfcc80-4506-11eb-9308-f8d7e7264ee4.png">
然后情况逐渐变化：
<img width="1432" alt="截屏2020-12-23 上午10 09 35" src="https://user-images.githubusercontent.com/10093659/102951080-f3f56c80-4506-11eb-858f-be19e3efa9ce.png">
最后完全gg：
<img width="1446" alt="截屏2020-12-23 上午10 10 32" src="https://user-images.githubusercontent.com/10093659/102951143-15565880-4507-11eb-9d1e-3a12a5ec2c8b.png">
跪求大佬指导。。。

**Comment by wangbin579** [comment]
从抓包来推测，应该是被干扰了。

可以同时在线上节点和镜像节点抓包，对同一个session（在抓包文件通过客户端端口号来过滤）进行对比，看看reset数据包是不是中途设备干的。

最可疑的地方：
同时发送fin和reset数据包（相差7us），不正常，tcpcopy没有发送这么快

**Comment by Grade-Two** [comment]
线上节点：
<img width="1349" alt="截屏2020-12-23 下午2 14 02" src="https://user-images.githubusercontent.com/10093659/102965594-1b5d3100-4529-11eb-9a1a-6ef62f6038ce.png">

镜像节点：
<img width="1457" alt="截屏2020-12-23 下午2 12 50" src="https://user-images.githubusercontent.com/10093659/102965519-efda4680-4528-11eb-9514-7eac00a1c90e.png">

两边都抓到了，可以对应上。
后续那些整个stream只包含一条reset包的session也是两边各有一条，可以对应上，跪。。。
这可能是什么原因造成的ORZ。。。

**Comment by Grade-Two** [comment]
@wangbin579 在CSDN联系您了，万望大佬回复T_T

**Comment by wangbin579** [comment]
不好意思，才回复。

csdn已经丢失账号，无法回复。

tcpcopy编译的时候，加上--with-debug选项，详细输出debug日志看看吧。
也只能从debug日志来查看，为什么连续发送要reset（其实是不相信tcpcopy有这么快的发送速度，需要debug日志来确认）。


qq群联系也行（521824702）

**Comment by wangbin579** [comment]
这个问题是集中发送大量路由消息，导致用户定制的os报fd错误，导致后续无法发送

**Comment by Grade-Two** [comment]
感谢大佬 @wangbin579 ～就是这个原因，此问题已解决～

**Comment by bi-xiaohu** [comment]
@Grade-Two 您好，我在使用TcpCOPY复制流量的时候遇到了类似的问题，方便请教下解决方法吗？谢谢

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。
