### ISSUE TITLE
模拟线上的音视频流传输，测试机上的服务在三分钟左右连接被reset，请教一下这是为什么

### ISSUE THREAD

**Issue by teddywarm** [session-replay-tools/tcpcopy#383]
case：online server上部署的是一个音视频流传输的服务，我用./tcpcopy -x xxx-9.130.94.xx:xxx -s 9.130.94.xx -c 9.130.2.254 -p xxx -l /var/log/tcpcopy.log -d 这个命令监听了这个音视频流传输的端口，把数据复制到测试机上，但是在三分钟左右，测试机上的服务的连接发现被重置了，相当于被tcpcopy重置了，可以帮忙解惑一下吗？

**Comment by wangbin579** [comment]
最好先抓包确认一下，连接被重置，是不是tcpcopy发送的，检测方法：
在测试机器和tcpcopy所在机器都抓包，如果都有重置数据包，那说明是tcpcopy发送的。

如果确实是tcpcopy发送的，请贴出相关数据包信息，查看重置原因
