### ISSUE TITLE
-c 参数使用 192.168.1.x 能成功导流，但是 192.18.1.x 反而不行，这是为什么呢？

### ISSUE THREAD

**Issue by BruceLuo33** [session-replay-tools/tcpcopy#385]
> -c参数用-c 192.18.1.x，不要用-c 192.18.1.0

请问大佬，我设置的 -c 192.168.1.x 可以正常导入流量，但是设置 -c 192.18.1.x 测试机器就收不到导入的流量。请问这是怎么回事呢？

_Originally posted by @BruceLuo33 in https://github.com/session-replay-tools/tcpcopy/issues/323#issuecomment-870335279_

**Comment by BruceLuo33** [comment]
![image](https://user-images.githubusercontent.com/38673091/123753718-bd047700-d8ec-11eb-8304-6c2560fa4383.png)

**Comment by wangbin579** [comment]
192.168是内网地址，192.18是外网地址
不同类型的IP地址，受到的安全限制是不一样的。

可以采用抓包分析的方法，去查看具体原因。

**Comment by PretDB** [comment]
Cause there may be no such machine of which IP is started with "192.18" in your local network.
