### ISSUE TITLE
docker容器中运行tcpcopy很短时间后tcpcopy命令自动退出

### ISSUE THREAD

**Issue by pengai** [session-replay-tools/tcpcopy#388]
hi 你好：
我的环境如下：
docker： online-server: 10.100.198.x 节点
docker：辅助节点：10.100.224.x节点
docker:  测试节点： 10.100.226.x  ---》对应宿主机是10.100.224.y 和辅助节点10.100.224.x是同一网段

tcpcopy运行异常日志内容如下：
2021/09/07 20:30:18 +891 [notice] tcpcopy version:1.2.0
2021/09/07 20:30:18 +891 [notice] tcpcopy internal version:6
2021/09/07 20:30:18 +891 [notice] target:8080-10.100.226.x:8080
2021/09/07 20:30:18 +891 [notice] TC_COMBINED mode
2021/09/07 20:30:18 +891 [notice] epoll mode
2021/09/07 20:30:18 +891 [notice] session timeout:120
2021/09/07 20:30:18 +891 [notice] keepalive timeout:240
2021/09/07 20:30:18 +891 [notice] min sess pool size:608
2021/09/07 20:30:18 +891 [notice] sess pool size:1024
2021/09/07 20:30:18 +891 [notice] set global port for tcpcopy
2021/09/07 20:30:18 +891 [notice] raw_clt_tf_ip:192.168.1.x
2021/09/07 20:30:18 +891 [notice] parallel connections per target:2
2021/09/07 20:30:18 +891 [notice] s parameter:10.100.224.x
2021/09/07 20:30:18 +891 [notice] set only ip for tcpcopy
2021/09/07 20:30:18 +891 [info] connect to remote server(10.100.224.x:36524)
2021/09/07 20:30:18 +891 [info] connect to remote server(10.100.224.x:36524)
2021/09/07 20:30:48 +588 [error] raw fd:7 (Message too long)
2021/09/07 20:30:48 +588 [warn] to bak:192.168.1.7:56704-->10.100.226.209:8080,len 1500,seq=2471100662,ack=4129532670
2021/09/07 20:30:48 +588 [error] send to back error,tot_len is:1500
2021/09/07 20:30:48 +588 [warn] sig 64 received
2021/09/07 20:30:48 +588 [notice] active:121,rel:599,obs del:0,tw:55
2021/09/07 20:30:48 +588 [notice] conns:19,resp:130,c-resp:61
2021/09/07 20:30:48 +588 [notice] resp fin:3,resp rst:0
2021/09/07 20:30:48 +588 [notice] send:1487,send content:56
2021/09/07 20:30:48 +588 [notice] send syn:720, fin:3,reset:652
2021/09/07 20:30:48 +588 [notice] reconnect:0,for no syn:491
2021/09/07 20:30:48 +588 [notice] retransmit:0
2021/09/07 20:30:48 +588 [notice] recv packs after retransmission:0
2021/09/07 20:30:48 +588 [notice] syn cnt:229,all clt:30521,clt cont:13202
2021/09/07 20:30:48 +588 [notice] total cont retransmit:0, frag:0
2021/09/07 20:30:48 +588 [notice] total captured packets:79489
2021/09/07 20:30:48 +588 [warn] many connections can't be established
2021/09/07 20:30:48 +588 [info] session table, size:65536, total:121
2021/09/07 20:30:48 +588 [notice] tc_epoll_destroy, close fd:5
2021/09/07 20:30:48 +588 [notice] tc_epoll_destroy, close fd:6
2021/09/07 20:30:48 +588 [notice] tc_epoll_destroy, close fd:8
2021/09/07 20:30:48 +588 [notice] tc_event_loop_finish over
2021/09/07 20:30:48 +588 [notice] user time used:0
2021/09/07 20:30:48 +588 [notice] sys  time used:0
2021/09/07 20:30:48 +588 [notice] max memory size:9140
2021/09/07 20:30:48 +588 [notice] Total allocated space (bytes): 368
2021/09/07 20:30:48 +588 [notice] Total free space (bytes): 188048
2021/09/07 20:30:48 +588 [notice] Top-most, releasable space (bytes): 187568
2021/09/07 20:33:19 +606 [notice] tcpcopy version:1.2.0
2021/09/07 20:33:19 +606 [notice] tcpcopy internal version:6
2021/09/07 20:33:19 +606 [notice] target:8080-10.100.226.209:8080
2021/09/07 20:33:19 +606 [notice] TC_COMBINED mode
2021/09/07 20:33:19 +606 [notice] epoll mode
2021/09/07 20:33:19 +606 [notice] session timeout:120
2021/09/07 20:33:19 +606 [notice] keepalive timeout:240
2021/09/07 20:33:19 +606 [notice] min sess pool size:608
2021/09/07 20:33:19 +606 [notice] sess pool size:1024
2021/09/07 20:33:19 +606 [notice] set global port for tcpcopy
2021/09/07 20:33:19 +606 [notice] raw_clt_tf_ip:192.168.1.x
2021/09/07 20:33:19 +606 [notice] parallel connections per target:2
2021/09/07 20:33:19 +606 [notice] s parameter:10.100.224.5
2021/09/07 20:33:19 +606 [notice] set only ip for tcpcopy
2021/09/07 20:33:19 +606 [info] connect to remote server(10.100.224.5:36524)
2021/09/07 20:33:19 +606 [info] connect to remote server(10.100.224.5:36524)
2021/09/07 20:33:19 +700 [error] raw fd:7 (Message too long)
2021/09/07 20:33:19 +700 [warn] to bak:192.168.1.3:40860-->10.100.226.x:8080,len 1500,seq=1452463759,ack=2657834484
2021/09/07 20:33:19 +700 [error] send to back error,tot_len is:1500
2021/09/07 20:33:19 +700 [warn] sig 64 received
2021/09/07 20:33:19 +700 [notice] active:24,rel:0,obs del:0,tw:0
2021/09/07 20:33:19 +700 [notice] conns:24,resp:80,c-resp:28
2021/09/07 20:33:19 +700 [notice] resp fin:0,resp rst:0
2021/09/07 20:33:19 +700 [notice] send:105,send content:36
2021/09/07 20:33:19 +700 [notice] send syn:24, fin:0,reset:0
2021/09/07 20:33:19 +700 [notice] reconnect:0,for no syn:24
2021/09/07 20:33:19 +700 [notice] retransmit:0
2021/09/07 20:33:19 +700 [notice] recv packs after retransmission:0
2021/09/07 20:33:19 +700 [notice] syn cnt:0,all clt:48,clt cont:44
2021/09/07 20:33:19 +700 [notice] total cont retransmit:0, frag:0
2021/09/07 20:33:19 +700 [notice] total captured packets:356
2021/09/07 20:33:19 +700 [info] session table, size:65536, total:24
2021/09/07 20:33:19 +700 [notice] tc_epoll_destroy, close fd:5
2021/09/07 20:33:19 +700 [notice] tc_epoll_destroy, close fd:6
2021/09/07 20:33:19 +700 [notice] tc_epoll_destroy, close fd:8
2021/09/07 20:33:19 +700 [notice] tc_event_loop_finish over
2021/09/07 20:33:19 +700 [notice] user time used:0
2021/09/07 20:33:19 +700 [notice] sys  time used:0
2021/09/07 20:33:19 +700 [notice] max memory size:4644
2021/09/07 20:33:19 +700 [notice] Total allocated space (bytes): 368
2021/09/07 20:33:19 +700 [notice] Total free space (bytes): 134800
2021/09/07 20:33:19 +700 [notice] Top-most, releasable space (bytes): 134320

辛苦作者给解答下！！！！

**Comment by wangbin579** [comment]
主要看error级别的log：
显示Message too long，说明tcpcopy默认的1500大小不匹配发送的mtu。
可以通过tcpcopy的-M参数来调整大小，以适应发送mtu。
