### ISSUE TITLE
我希望使用tcpcopy的离线模式、流量重放和放大功能，但是希望不需要上游服务

### ISSUE THREAD

**Issue by FireSpoonYZ** [session-replay-tools/tcpcopy#392]
我希望用tcpcopy的离线模式、流量复制和放大功能，不希望上游服务返回response包。有什么解决办法吗？

**Comment by wangbin579** [comment]
不理解“不希望上游服务返回response包”具体是啥意思，能够具体一点吗？

**Comment by FireSpoonYZ** [comment]
简单来说，我想测试的是抓包工具，所以这里的场景是没有上游服务的。我希望可以以指定的流量大小来重放.pcap文件

**Comment by wangbin579** [comment]
tcpcopy只能针对上游服务，少了，无法回放
