### ISSUE TITLE
 我本地使用docker进行2个redis的流量复制，也是minikube进行模拟，都不行，谁能帮帮我。

### ISSUE THREAD

**Issue by rulinma** [session-replay-tools/tcpcopy#395]
online-server[172.17.0.2]：在线服务器(redis-online)
assistant-server[172.17.0.3]： 使用一个linux即可(mysql-8026)
target-server[172.17.0.5]： 测试服务器(redis-test)

编译命令都是./configure --with-debug

172.17.0.3#/usr/local/intercept/sbin/intercept -i eth0 -l /var/log/intercept.log -F 'tcp and src port 6379' -d

172.17.0.2#/usr/local/tcpcopy/sbin/tcpcopy -x 6379-172.17.0.5:6379 -s 172.17.0.3 -l /var/log/tcpcopy.log -d

我使用VM是可以的。

谁有成功的经验，不胜感谢！rulinma@qq.com，联系或者15026906099。

**Comment by wangbin579** [comment]
多看看之前的issue，99%都是有类似答案的。


如果实在搞不定，请给出详细的信息
