### ISSUE TITLE
经过nginx转发后tcpcopy异常，去掉nginx正常复制

### ISSUE THREAD

**Issue by mltneal** [session-replay-tools/tcpcopy#396]
1、按照文档要求部署后，监听生产服务器可以正常复制到测试端
2、但是在生产服务器前加了个nginx（nginx部署在另外一台服务器），请求经nginx正常转发到生产服务器，但是测试端收不到需要复制的http请求

**Comment by mltneal** [comment]
路由配置好就正常了，跟nginx无关

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。
