### ISSUE TITLE
无法转发数据包到测试服务器，只有sync包到测试服务器

### ISSUE THREAD

**Issue by cyflhn** [session-replay-tools/tcpcopy#401]
tcpcopy版本是1.2.0，日志如下

2023/08/31 10:40:50 +439 [notice] user time used:0
2023/08/31 10:40:50 +439 [notice] sys  time used:0
2023/08/31 10:40:50 +439 [notice] max memory size:4020
2023/08/31 10:40:50 +439 [notice] Total allocated space (bytes): 53792
2023/08/31 10:40:50 +439 [notice] Total free space (bytes): 81376
2023/08/31 10:40:50 +439 [notice] Top-most, releasable space (bytes): 80896
2023/08/31 10:41:50 +439 [notice] user time used:0
2023/08/31 10:41:50 +439 [notice] sys  time used:0
2023/08/31 10:41:50 +439 [notice] max memory size:4020
2023/08/31 10:41:50 +439 [notice] Total allocated space (bytes): 53792
2023/08/31 10:41:50 +439 [notice] Total free space (bytes): 81376
2023/08/31 10:41:50 +439 [notice] Top-most, releasable space (bytes): 80896
2023/08/31 10:41:50 +439 [notice] active:0,rel:1,obs del:0,tw:0
2023/08/31 10:41:50 +439 [notice] conns:0,resp:0,c-resp:0
2023/08/31 10:41:50 +439 [notice] resp fin:0,resp rst:0
2023/08/31 10:41:50 +439 [notice] send:2,send content:0
2023/08/31 10:41:50 +439 [notice] send syn:1, fin:0,reset:1
2023/08/31 10:41:50 +439 [notice] reconnect:0,for no syn:0
2023/08/31 10:41:50 +439 [notice] retransmit:0
2023/08/31 10:41:50 +439 [notice] recv packs after retransmission:0
2023/08/31 10:41:50 +439 [notice] syn cnt:1,all clt:6,clt cont:1
2023/08/31 10:41:50 +439 [notice] total cont retransmit:0, frag:0
2023/08/31 10:41:50 +439 [notice] total captured packets:15737
2023/08/31 10:42:20 +439 [notice] active:0,rel:1,obs del:0,tw:0
2023/08/31 10:42:20 +439 [notice] conns:0,resp:0,c-resp:0
2023/08/31 10:42:20 +439 [notice] resp fin:0,resp rst:0
2023/08/31 10:42:20 +439 [notice] send:2,send content:0
2023/08/31 10:42:20 +439 [notice] send syn:1, fin:0,reset:1
2023/08/31 10:42:20 +439 [notice] reconnect:0,for no syn:0
2023/08/31 10:42:20 +439 [notice] retransmit:0
2023/08/31 10:42:20 +439 [notice] recv packs after retransmission:0
2023/08/31 10:42:20 +439 [notice] syn cnt:1,all clt:6,clt cont:1
2023/08/31 10:42:20 +439 [notice] total cont retransmit:0, frag:0
2023/08/31 10:42:20 +439 [notice] total captured packets:19855

用tcpdump抓包，发现只有sync包到测试服务器，请问下是怎么回事

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。
