### ISSUE TITLE
离线丢包问题

### ISSUE THREAD

**Issue by lighter6174** [session-replay-tools/tcpcopy#403]
大神你好，在使用这个工具的时候，有些问题还无法查明，烦请帮忙看下：

按照新架构的部署方式离线回放，tcpcopy使用的版本是1.2.0，intercept使用的版本是1.0.0，测试服务器也能收到转发的数据包：
1、从intercept日志来看，貌似存在丢包问题？回放的文件是1.7G，回放大约会建立300个左右的TCP连接，没有加速，没有放大流量。
2、另外离线回放数据包存在重复回放的问题，应用层面发现存在session重复现象。
部分tcpcopy和intercept日志如下：

tcpcopy:
2024/03/25 14:30:19 +102 [notice] user time used:0
2024/03/25 14:30:19 +102 [notice] sys  time used:0
2024/03/25 14:30:19 +102 [notice] max memory size:7200
2024/03/25 14:30:19 +102 [notice] Total allocated space (bytes): 1080480
2024/03/25 14:30:19 +102 [notice] Total free space (bytes): 1643360
2024/03/25 14:30:19 +102 [notice] Top-most, releasable space (bytes): 134912
2024/03/25 14:30:19 +102 [notice] active:127,rel:19990,obs del:5,tw:3
2024/03/25 14:30:19 +102 [notice] conns:19696,resp:63193,c-resp:24996
2024/03/25 14:30:19 +102 [notice] resp fin:1761,resp rst:1547
2024/03/25 14:30:19 +102 [notice] send:77844,send content:15989
2024/03/25 14:30:19 +102 [notice] send syn:20118, fin:1075,reset:17416
2024/03/25 14:30:19 +102 [notice] reconnect:1,for no syn:1620
2024/03/25 14:30:19 +102 [notice] retransmit:0
2024/03/25 14:30:19 +102 [notice] recv packs after retransmission:0
2024/03/25 14:30:19 +102 [notice] syn cnt:18512,all clt:39919,clt cont:16467
2024/03/25 14:30:19 +102 [notice] total cont retransmit:252, frag:11616
2024/03/25 14:30:19 +102 [notice] total captured packets:62599
2024/03/25 14:30:49 +102 [notice] active:128,rel:20013,obs del:5,tw:2
2024/03/25 14:30:49 +102 [notice] conns:19712,resp:64886,c-resp:25929
2024/03/25 14:30:49 +102 [notice] resp fin:1761,resp rst:1562
2024/03/25 14:30:49 +102 [notice] send:79541,send content:16733
2024/03/25 14:30:49 +102 [notice] send syn:20142, fin:1075,reset:17423
2024/03/25 14:30:49 +102 [notice] reconnect:1,for no syn:1643
2024/03/25 14:30:49 +102 [notice] retransmit:0
2024/03/25 14:30:49 +102 [notice] recv packs after retransmission:0
2024/03/25 14:30:49 +102 [notice] syn cnt:18513,all clt:40673,clt cont:17209
2024/03/25 14:30:49 +102 [notice] total cont retransmit:252, frag:11692
2024/03/25 14:30:49 +102 [notice] total captured packets:64316

intercept:

2024/03/25 14:30:25 +642 [notice] total resp packs:63919, all:63919, route:20123, sock write cnt:56478
2024/03/25 14:30:25 +642 [notice] cache hit:56713,missed:128,lost:7078
2024/03/25 14:30:25 +642 [notice] search:63919,extra compared:3203,all sessions:20123
2024/03/25 14:30:55 +642 [notice] total resp packs:65588, all:65588, route:20148, sock write cnt:58126
2024/03/25 14:30:55 +642 [notice] cache hit:58382,missed:128,lost:7078
2024/03/25 14:30:55 +642 [notice] search:65588,extra compared:3203,all sessions:20148
2024/03/25 14:31:25 +642 [notice] total resp packs:67295, all:67295, route:20169, sock write cnt:59812
2024/03/25 14:31:25 +642 [notice] cache hit:60089,missed:128,lost:7078
2024/03/25 14:31:25 +642 [notice] search:67295,extra compared:3203,all sessions:20169
2024/03/25 14:31:55 +643 [notice] total resp packs:69145, all:69145, route:20193, sock write cnt:61525
2024/03/25 14:31:55 +643 [notice] cache hit:61939,missed:128,lost:7078
2024/03/25 14:31:55 +643 [notice] search:69145,extra compared:3203,all sessions:20193
2024/03/25 14:32:25 +643 [notice] total resp packs:71005, all:71005, route:20215, sock write cnt:63244
2024/03/25 14:32:25 +643 [notice] cache hit:63799,missed:128,lost:7078
2024/03/25 14:32:25 +643 [notice] search:71005,extra compared:3203,all sessions:20215
2024/03/25 14:32:55 +644 [notice] total resp packs:72723, all:72723, route:20239, sock write cnt:64942
2024/03/25 14:32:55 +644 [notice] cache hit:65517,missed:128,lost:7078
2024/03/25 14:32:55 +644 [notice] search:72723,extra compared:3203,all sessions:20239
2024/03/25 14:33:25 +644 [notice] total resp packs:74415, all:74415, route:20260, sock write cnt:66617
2024/03/25 14:33:25 +644 [notice] cache hit:67209,missed:128,lost:7078
2024/03/25 14:33:25 +644 [notice] search:74415,extra compared:3203,all sessions:20260
2024/03/25 14:33:55 +644 [notice] total resp packs:76156, all:76156, route:20285, sock write cnt:68333
2024/03/25 14:33:55 +644 [notice] cache hit:68950,missed:128,lost:7078
2024/03/25 14:33:55 +644 [notice] search:76156,extra compared:3203,all sessions:20285
2024/03/25 14:34:25 +644 [notice] total resp packs:77889, all:77889, route:20308, sock write cnt:70051
2024/03/25 14:34:25 +644 [notice] cache hit:70683,missed:128,lost:7078
2024/03/25 14:34:25 +644 [notice] search:77889,extra compared:3203,all sessions:20308
2024/03/25 14:34:55 +644 [notice] total resp packs:79667, all:79667, route:20331, sock write cnt:71810
2024/03/25 14:34:55 +644 [notice] cache hit:72461,missed:128,lost:7078
2024/03/25 14:34:55 +644 [notice] search:79667,extra compared:3203,all sessions:20331
2024/03/25 14:35:25 +644 [notice] total resp packs:81428, all:81428, route:20354, sock write cnt:73553
2024/03/25 14:35:25 +644 [notice] cache hit:74222,missed:128,lost:7078
2024/03/25 14:35:25 +644 [notice] search:81428,extra compared:3203,all sessions:20354
2024/03/25 14:35:55 +644 [notice] total resp packs:83491, all:83491, route:20377, sock write cnt:75367
2024/03/25 14:35:55 +644 [notice] cache hit:76285,missed:128,lost:7078
2024/03/25 14:35:55 +644 [notice] search:83491,extra compared:3203,all sessions:20377

为方便排查问题，已将全量日志上传至附件，麻烦看下，不胜感激！
[intercept13.log](https://github.com/session-replay-tools/tcpcopy/files/14742454/intercept13.log)
[tcpcopy13.log](https://github.com/session-replay-tools/tcpcopy/files/14742456/tcpcopy13.log)

**Comment by wangbin579** [comment]
丢失问题分析，还得有初始的抓包文件才能分析，log只是统计数据。
