### ISSUE TITLE
tcp1.2.0版本提示无-i参数

### ISSUE THREAD

**Issue by 1450793561** [session-replay-tools/tcpcopy#404]
tcpcopy版本1.2.0,提示无-i参数，1.0.0也没有
[root@xxxx-sit2-xxx-nginx-131-14 ~]# tcpcopy -l /data/tcplog.log  -x 80-10.2.137.231:80 -s 10.2.137.232  -c  192.168.2.254 -i test.pcap 
tcpcopy: illegal argument "i"
[root@xxxx-sit2-xxx-nginx-131-14~]#

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。

**Comment by 1450793561** [comment]
[root@xxxx-xxx-xxxx-nginx-131-14 ~]# tcpcopy -h
tcpcopy 1.2.0
-x <transfer,> use <transfer,> to specify the IPs and ports of the source and target
               servers. Suppose 'sourceIP' and 'sourcePort' are the IP and port 
               number of the source server you want to copy from, 'targetIP' and 
               'targetPort' are the IP and port number of the target server you want
               to send requests to, the format of <transfer,> could be as follows:
               'sourceIP:sourcePort-targetIP:targetPort,...'. Most of the time,
               sourceIP could be omitted and thus <transfer,> could also be:
               'sourcePort-targetIP:targetPort,...'. As seen, the IP address and the
               port number are segmented by ':' (colon), the sourcePort and the
               targetIP are segmented by '-', and two 'transfer's are segmented by
               ',' (comma). For example, './tcpcopy -x 80-192.168.0.2:18080' would
               copy requests from port '80' on current server to the target port
               '18080' of the target IP '192.168.0.2'.
-H <ip_addr>   change the localhost IP address to the given IP address
-c <ip_addr,>  change the client IP to one of IP addresses when sending to the
               target server. For example,
               './tcpcopy -x 8080-192.168.0.2:8080 -c 62.135.200.x' would copy
               requests from port '8080' of current online server to the target port
               '8080' of target server '192.168.0.2' and modify the client IP to be
               one of net 62.135.200.0/24.
-n <num>       use <num> to set the replication times when you want to get a 
               copied data stream that is several times as large as the online data.
               The maximum value allowed is 1023. As multiple copying is based on 
               port number modification, the ports may conflict with each other,
               in particular in intranet applications where there are few source IPs
               and most connections are short. Thus, tcpcopy would perform better 
               when less copies are specified. For example, 
               './tcpcopy -x 80-192.168.0.2:8080 -n 3' would copy data flows from 
               port 80 on the current server, generate data stream that is three
               times as large as the source data, and send these requests to the
               target port 8080 on '192.168.0.2'.
-f <num>       use this parameter to control the port number modification process
               and reduce port conflications when multiple tcpcopy instances are
               running. The value of <num> should be different for different tcpcopy
               instances. The maximum value allowed is 1023.
-m <num>       set the maximum memory allowed to use for tcpcopy in megabytes, 
               to prevent tcpcopy occupying too much memory and influencing the
               online system. When the memory exceeds this limit, tcpcopy would quit
               automatically. The parameter is effective only when the kernel 
               version is 2.6.32 or above. The default value is 1024.
-M <num>       MTU value sent to backend (default 1500)
-D <num>       MSS value sent back(default 1460)
-R <num>       set default rtt value
-U <num>       set user session pool size in kilobytes(default 1).
               The maximum value allowed is 63.
-C <num>       parallel connections between tcpcopy and intercept.
               The maximum value allowed is 11(default 2 connections).
-s <server,>   intercept server list
               Format:
               ip_addr1:port1, ip_addr2:port2, ...
-t <num>       set the session timeout limit. If tcpcopy does not receive response
               from the target server within the timeout limit, the session would 
               be dropped by tcpcopy. When the response from the target server is
               slow or the application protocol is context based, the value should 
               be set larger. The default value is 120 seconds.
-k <num>       set the session keepalive timeout limit.
-l <file>      save the log information in <file>
-r <num>       set the percentage of sessions transfered (integer range:1~100)
-p <num>       set the target server listening port. The default value is 36524.
-P <file>      save PID in <file>, only used with -d option
-O             only replay full session
-g             gradully replay
-W             don't wait response when having a new req
-L             lonely for tcpcopy when intercept is closed
-h             print this help and exit
-v             version
-d             run as a daemon

**Comment by wangbin579** [comment]
编译configure不对吧

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。
