### ISSUE TITLE
tcpcopy 同步几秒钟后就没反应了 是什么问题呢

### ISSUE THREAD

**Issue by blackhat1989** [session-replay-tools/tcpcopy#46]
请教一下 刚在线上测试了一下tcpcopy  ，每次程序启动以后 数据传输接近1分钟左右就停止了，很奇怪连续测试了20次都是同样的问题。
测试环境 Cent os 6.3 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
 两台机器都一样，分别部署在不同机房。
使用的都是nginx 服务.
tcpcopy 服务器IP 182.118.23.5
client 服务器IP 125.39.31.146
以下是tcpcopy 的一部分 error.log
2012/12/11 22:22:57 +554 [notice] active:283,rel reqs:52,obs del:18
2012/12/11 22:22:57 +554 [notice] conns:184,resp packs:42205,c-resp packs:41832
2012/12/11 22:22:57 +554 [notice] send Packets:42676,send content packets:242
2012/12/11 22:22:57 +554 [notice] reconnect for closed :0,for no syn:112
2012/12/11 22:22:57 +554 [notice] retransmit:0
2012/12/11 22:22:57 +554 [notice] successful retransmit:0
2012/12/11 22:22:57 +554 [notice] syn cnt:224,all clt packs:344025,clt cont:427
2012/12/11 22:22:57 +554 [warn] many connections can't be established
2012/12/11 22:22:57 +554 [notice] session size:283
2012/12/11 22:22:57 +554 [warn] unsend:too many packets:292,p:1382
2012/12/11 22:22:57 +554 [warn] unsend:candidate erased:270,p:7605
2012/12/11 22:22:57 +554 [warn] unsend:too many packets:283,p:59829
2012/12/11 22:22:57 +554 [warn] unsend:too many packets:306,p:1213
2012/12/11 22:22:57 +554 [warn] unsend:candidate erased:281,p:52157
2012/12/11 22:22:57 +554 [notice] activate_dead_sessions
2012/12/11 22:23:03 +054 [notice] active:272,rel reqs:75,obs del:41
2012/12/11 22:23:03 +054 [notice] conns:184,resp packs:42205,c-resp packs:41832
2012/12/11 22:23:03 +054 [notice] send Packets:42713,send content packets:242
2012/12/11 22:23:03 +054 [notice] reconnect for closed :0,for no syn:121
2012/12/11 22:23:03 +054 [notice] retransmit:0
2012/12/11 22:23:03 +054 [notice] successful retransmit:0
2012/12/11 22:23:03 +054 [notice] syn cnt:227,all clt packs:354132,clt cont:439
2012/12/11 22:23:03 +054 [warn] many connections can't be established
2012/12/11 22:23:03 +054 [notice] session size:272
2012/12/11 22:23:03 +054 [warn] unsend:candidate erased:260,p:10777
2012/12/11 22:23:03 +054 [warn] unsend:candidate erased:285,p:2445
2012/12/11 22:23:03 +054 [warn] unsend:too many packets:293,p:7605
2012/12/11 22:23:03 +054 [warn] unsend:too many packets:304,p:52157
2012/12/11 22:23:03 +054 [warn] unsend:candidate erased:257,p:1988
2012/12/11 22:23:03 +054 [warn] unsend:candidate erased:260,p:25054
2012/12/11 22:23:03 +054 [notice] activate_dead_sessions
2012/12/11 22:23:08 +354 [notice] active:260,rel reqs:100,obs del:65
2012/12/11 22:23:08 +354 [notice] conns:184,resp packs:42205,c-resp packs:41832
2012/12/11 22:23:08 +354 [notice] send Packets:42745,send content packets:242
2012/12/11 22:23:08 +354 [notice] reconnect for closed :0,for no syn:127
2012/12/11 22:23:08 +354 [notice] retransmit:0
2012/12/11 22:23:08 +354 [notice] successful retransmit:0
2012/12/11 22:23:08 +354 [notice] syn cnt:234,all clt packs:362966,clt cont:450
2012/12/11 22:23:08 +354 [warn] many connections can't be established
2012/12/11 22:23:08 +354 [notice] session size:260
2012/12/11 22:23:08 +354 [warn] unsend:too many packets:270,p:10777
2012/12/11 22:23:08 +354 [warn] unsend:too many packets:290,p:2445
2012/12/11 22:23:08 +354 [warn] unsend:candidate erased:274,p:27047
2012/12/11 22:23:08 +354 [warn] unsend:too many packets:268,p:1988
2012/12/11 22:23:08 +354 [warn] unsend:too many packets:275,p:25054
2012/12/11 22:23:08 +354 [notice] activate_dead_sessions
2012/12/11 22:23:13 +534 [notice] active:253,rel reqs:121,obs del:86
2012/12/11 22:23:13 +534 [notice] conns:184,resp packs:42205,c-resp packs:41832
2012/12/11 22:23:13 +534 [notice] send Packets:42780,send content packets:242
2012/12/11 22:23:13 +534 [notice] reconnect for closed :0,for no syn:134
2012/12/11 22:23:13 +534 [notice] retransmit:0
2012/12/11 22:23:13 +534 [notice] successful retransmit:0
2012/12/11 22:23:13 +534 [notice] syn cnt:241,all clt packs:375002,clt cont:464
2012/12/11 22:23:13 +534 [warn] many connections can't be established
2012/12/11 22:23:13 +534 [notice] session size:253
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:268,p:59426
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:277,p:4901
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:265,p:58154
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:263,p:3943
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:261,p:1654
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:278,p:1924
2012/12/11 22:23:13 +534 [warn] unsend:too many packets:296,p:27047
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:273,p:2491
2012/12/11 22:23:13 +534 [warn] unsend:candidate erased:276,p:35551
2012/12/11 22:23:13 +534 [notice] activate_dead_sessions
2012/12/11 22:23:19 +554 [notice] active:173,rel reqs:202,obs del:167
2012/12/11 22:23:19 +554 [notice] conns:184,resp packs:42205,c-resp packs:41832
2012/12/11 22:23:19 +554 [notice] send Packets:42862,send content packets:242
2012/12/11 22:23:19 +554 [notice] reconnect for closed :0,for no syn:134
2012/12/11 22:23:19 +554 [notice] retransmit:0
2012/12/11 22:23:19 +554 [notice] successful retransmit:0
2012/12/11 22:23:19 +554 [notice] syn cnt:242,all clt packs:377003,clt cont:464
2012/12/11 22:23:19 +554 [notice] session size:173
2012/12/11 22:23:19 +554 [warn] unsend:too many packets:271,p:59426
2012/12/11 22:23:19 +554 [warn] unsend:too many packets:278,p:4901
2012/12/11 22:23:19 +554 [warn] unsend:too many packets:267,p:58154
2012/12/11 22:23:19 +554 [warn] unsend:too many packets:267,p:3943
2012/12/11 22:23:19 +554 [warn] unsend:too many packets:283,p:1924
2012/12/11 22:23:19 +554 [warn] unsend:too many packets:280,p:35551
2012/12/11 22:23:19 +554 [notice] activate_dead_sessions
2012/12/11 22:23:25 +554 [notice] active:160,rel reqs:220,obs del:185
2012/12/11 22:23:25 +554 [notice] conns:184,resp packs:42205,c-resp packs:41832
2012/12/11 22:23:25 +554 [notice] send Packets:42885,send content packets:242
2012/12/11 22:23:25 +554 [notice] reconnect for closed :0,for no syn:139
2012/12/11 22:23:25 +554 [notice] retransmit:0
2012/12/11 22:23:25 +554 [notice] successful retransmit:0
2012/12/11 22:23:25 +554 [notice] syn cnt:242,all clt packs:379676,clt cont:470
2012/12/11 22:23:25 +554 [notice] session size:160
2012/12/11 22:23:25 +554 [notice] activate_dead_sessions

下面是 client server 的 intercept 的error.log 
2012/12/11 22:22:30 +305 [notice] total response packets:469664
2012/12/11 22:22:30 +305 [notice] router size:215
2012/12/11 22:22:30 +305 [notice] router delete obsolete:1
2012/12/11 22:22:30 +305 [notice] delay total:77
2012/12/11 22:22:30 +305 [notice] delay delete obsolete :31
2012/12/11 22:22:36 +305 [notice] fd is null after session is created
2012/12/11 22:22:36 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2467,len 40,seq=3462026735,ack=1269695713,win:29440
2012/12/11 22:22:36 +305 [notice] fd is null after session is created
2012/12/11 22:22:36 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2466,len 40,seq=2428322404,ack=2240552728,win:29440
2012/12/11 22:22:36 +305 [notice] fd is null after session is created
2012/12/11 22:22:36 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2465,len 40,seq=4029497908,ack=2883825381,win:29440
2012/12/11 22:22:36 +305 [notice] fd is null after session is created
2012/12/11 22:22:36 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2464,len 40,seq=2161412811,ack=3876925621,win:29440
2012/12/11 22:22:46 +305 [notice] total response packets:470002
2012/12/11 22:22:46 +305 [notice] router size:259
2012/12/11 22:22:46 +305 [notice] router delete obsolete:1
2012/12/11 22:22:46 +305 [notice] delay total:54
2012/12/11 22:22:46 +305 [notice] delay delete obsolete :24
2012/12/11 22:22:52 +305 [notice] fd is null after session is created
2012/12/11 22:22:52 +305 [notice] from bak:125.39.31.146:80-->125.44.225.145:3085,len 40,seq=2038616683,ack=1744867950,win:29440
2012/12/11 22:22:52 +305 [notice] fd is null after session is created
2012/12/11 22:22:52 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2467,len 40,seq=3462026735,ack=1269695713,win:29440
2012/12/11 22:22:52 +305 [notice] fd is null after session is created
2012/12/11 22:22:52 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2466,len 40,seq=2428322404,ack=2240552728,win:29440
2012/12/11 22:22:52 +305 [notice] fd is null after session is created
2012/12/11 22:22:52 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2465,len 40,seq=4029497908,ack=2883825381,win:29440
2012/12/11 22:22:52 +305 [notice] fd is null after session is created
2012/12/11 22:22:52 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2464,len 40,seq=2161412811,ack=3876925621,win:29440
2012/12/11 22:22:53 +305 [notice] fd is null after session is created
2012/12/11 22:22:53 +305 [notice] from bak:125.39.31.146:80-->125.44.225.145:3085,len 40,seq=2038616683,ack=1744867950,win:29440
2012/12/11 22:22:55 +305 [notice] fd is null after session is created
2012/12/11 22:22:55 +305 [notice] from bak:125.39.31.146:80-->125.44.225.145:3085,len 40,seq=2038616683,ack=1744867950,win:29440
2012/12/11 22:23:02 +305 [notice] total response packets:470241
2012/12/11 22:23:02 +305 [notice] router size:266
2012/12/11 22:23:02 +305 [notice] router delete obsolete:0
2012/12/11 22:23:02 +305 [notice] delay total:55
2012/12/11 22:23:02 +305 [notice] delay delete obsolete :19
2012/12/11 22:23:02 +305 [notice] fd is null after session is created
2012/12/11 22:23:02 +305 [notice] from bak:125.39.31.146:80-->115.60.41.244:51456,len 40,seq=3900251137,ack=1196114717,win:31488
2012/12/11 22:23:07 +305 [notice] fd is null after session is created
2012/12/11 22:23:07 +305 [notice] from bak:125.39.31.146:80-->219.157.188.8:1140,len 40,seq=1409076880,ack=1129932192,win:59456
2012/12/11 22:23:19 +305 [notice] total response packets:470378
2012/12/11 22:23:19 +305 [notice] router size:178
2012/12/11 22:23:19 +305 [notice] router delete obsolete:0
2012/12/11 22:23:19 +305 [notice] delay total:51
2012/12/11 22:23:19 +305 [notice] delay delete obsolete :5
2012/12/11 22:23:21 +305 [notice] fd is null after session is created
2012/12/11 22:23:21 +305 [notice] from bak:125.39.31.146:80-->182.119.119.66:62775,len 40,seq=2701393524,ack=841231623,win:47164
2012/12/11 22:23:26 +305 [notice] fd is null after session is created
2012/12/11 22:23:26 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2467,len 40,seq=3462026735,ack=1269695713,win:29440
2012/12/11 22:23:26 +305 [notice] fd is null after session is created
2012/12/11 22:23:26 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2466,len 40,seq=2428322404,ack=2240552728,win:29440
2012/12/11 22:23:26 +305 [notice] fd is null after session is created
2012/12/11 22:23:26 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2465,len 40,seq=4029497908,ack=2883825381,win:29440
2012/12/11 22:23:26 +305 [notice] fd is null after session is created
2012/12/11 22:23:26 +305 [notice] from bak:125.39.31.146:80-->125.40.234.255:2464,len 40,seq=2161412811,ack=3876925621,win:29440
2012/12/11 22:23:39 +305 [notice] total response packets:470399
2012/12/11 22:23:39 +305 [notice] router size:148
2012/12/11 22:23:39 +305 [notice] router delete obsolete:0
2012/12/11 22:23:39 +305 [notice] delay total:54
2012/12/11 22:23:39 +305 [notice] delay delete obsolete :37
2012/12/11 22:23:51 +305 [notice] fd is null after session is created
2012/12/11 22:23:51 +305 [notice] from bak:125.39.31.146:80-->219.157.188.8:1140,len 40,seq=1409076880,ack=1129932192,win:59456
2012/12/11 22:23:55 +305 [notice] total response packets:470420
2012/12/11 22:23:55 +305 [notice] router size:148
2012/12/11 22:23:55 +305 [notice] router delete obsolete:0
2012/12/11 22:23:55 +305 [notice] delay total:21
2012/12/11 22:23:55 +305 [notice] delay delete obsolete :12
2012/12/11 22:24:39 +305 [notice] total response packets:470426
2012/12/11 22:24:39 +305 [notice] router size:148
2012/12/11 22:24:39 +305 [notice] router delete obsolete:44
2012/12/11 22:24:39 +305 [notice] delay total:10
2012/12/11 22:24:39 +305 [notice] delay delete obsolete :9
2012/12/11 22:24:55 +305 [notice] total response packets:470458
2012/12/11 22:24:55 +305 [notice] router size:104
2012/12/11 22:24:55 +305 [notice] router delete obsolete:40
2012/12/11 22:24:55 +305 [notice] delay total:6
2012/12/11 22:24:55 +305 [notice] delay delete obsolete :0
2012/12/11 22:25:39 +305 [notice] total response packets:470464
2012/12/11 22:25:39 +305 [notice] router size:64
2012/12/11 22:25:39 +305 [notice] router delete obsolete:64
2012/12/11 22:25:39 +305 [notice] delay total:7
2012/12/11 22:25:39 +305 [notice] delay delete obsolete :6
2012/12/11 22:25:55 +305 [notice] total response packets:470487
2012/12/11 22:25:55 +305 [notice] router size:0
2012/12/11 22:25:55 +305 [notice] router delete obsolete:0
2012/12/11 22:25:55 +305 [notice] delay total:6
2012/12/11 22:25:55 +305 [notice] delay delete obsolete :0
2012/12/11 22:26:39 +305 [notice] total response packets:470504
2012/12/11 22:26:39 +305 [notice] router size:0
2012/12/11 22:26:39 +305 [notice] router delete obsolete:0
2012/12/11 22:26:39 +305 [notice] delay total:7
2012/12/11 22:26:39 +305 [notice] delay delete obsolete :6
2012/12/11 22:26:55 +305 [notice] total response packets:470528
2012/12/11 22:26:55 +305 [notice] router size:0
2012/12/11 22:26:55 +305 [notice] router delete obsolete:0
2012/12/11 22:26:55 +305 [notice] delay total:6
2012/12/11 22:26:55 +305 [notice] delay delete obsolete :0
2012/12/11 22:27:39 +305 [notice] total response packets:470546
2012/12/11 22:27:39 +305 [notice] router size:0
2012/12/11 22:27:39 +305 [notice] router delete obsolete:0
2012/12/11 22:27:39 +305 [notice] delay total:7
2012/12/11 22:27:39 +305 [notice] delay delete obsolete :6
2012/12/11 22:27:55 +305 [notice] total response packets:470570
2012/12/11 22:27:55 +305 [notice] router size:0
2012/12/11 22:27:55 +305 [notice] router delete obsolete:0
2012/12/11 22:27:55 +305 [notice] delay total:6
2012/12/11 22:27:55 +305 [notice] delay delete obsolete :0
2012/12/11 22:28:39 +305 [notice] total response packets:470588
2012/12/11 22:28:39 +305 [notice] router size:0
2012/12/11 22:28:39 +305 [notice] router delete obsolete:0
2012/12/11 22:28:39 +305 [notice] delay total:7
2012/12/11 22:28:39 +305 [notice] delay delete obsolete :6
2012/12/11 22:28:55 +305 [notice] total response packets:470612
2012/12/11 22:28:55 +305 [notice] router size:0
2012/12/11 22:28:55 +305 [notice] router delete obsolete:0
2012/12/11 22:28:55 +305 [notice] delay total:6
2012/12/11 22:28:55 +305 [notice] delay delete obsolete :0
2012/12/11 22:29:39 +305 [notice] total response packets:470630
2012/12/11 22:29:39 +305 [notice] router size:0
2012/12/11 22:29:39 +305 [notice] router delete obsolete:0
2012/12/11 22:29:39 +305 [notice] delay total:7
2012/12/11 22:29:39 +305 [notice] delay delete obsolete :6
2012/12/11 22:30:39 +305 [notice] total response packets:470652
2012/12/11 22:30:39 +305 [notice] router size:0
2012/12/11 22:30:39 +305 [notice] router delete obsolete:0
2012/12/11 22:30:39 +305 [notice] delay total:5
2012/12/11 22:30:39 +305 [notice] delay delete obsolete :4
2012/12/11 22:30:55 +305 [notice] total response packets:470676
2012/12/11 22:30:55 +305 [notice] router size:0
2012/12/11 22:30:55 +305 [notice] router delete obsolete:0
2012/12/11 22:30:55 +305 [notice] delay total:6
2012/12/11 22:30:55 +305 [notice] delay delete obsolete :0
2012/12/11 22:31:39 +305 [notice] total response packets:470694
2012/12/11 22:31:39 +305 [notice] router size:0
2012/12/11 22:31:39 +305 [notice] router delete obsolete:0
2012/12/11 22:31:39 +305 [notice] delay total:7
2012/12/11 22:31:39 +305 [notice] delay delete obsolete :6
2012/12/11 22:31:55 +305 [notice] total response packets:470726
2012/12/11 22:31:55 +305 [notice] router size:0
2012/12/11 22:31:55 +305 [notice] router delete obsolete:0
2012/12/11 22:31:55 +305 [notice] delay total:6
2012/12/11 22:31:55 +305 [notice] delay delete obsolete :0

还请wangbin 帮忙看看是啥问题导致的。
另外机房上层初步分析有强制cache 设备不知道是不是由于上层cache 设备导致的 情况。

**Comment by huangjunque** [comment]
看看试试 我也有类似问题.

**Comment by bulabula001** [comment]
感谢 有参考
